// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_email.sql

package dbgen

import (
	"context"
)

const adoptProviderEmail = `-- name: AdoptProviderEmail :exec
UPDATE users SET email = $1::citext, email_confirmed_at = now()
WHERE id = $2::uuid
  AND NOT EXISTS (SELECT 1 FROM users other WHERE other.email = $1::citext)
`

type AdoptProviderEmailParams struct {
	Address string
	ID      string
}

// AdoptProviderEmail takes a provider's verified address as confirmed,
// unless another account holds it.
func (q *Queries) AdoptProviderEmail(ctx context.Context, arg AdoptProviderEmailParams) error {
	_, err := q.db.Exec(ctx, adoptProviderEmail, arg.Address, arg.ID)
	return err
}

const clearPendingEmail = `-- name: ClearPendingEmail :exec
UPDATE users SET pending_email = NULL, pending_email_at = NULL WHERE id = $1
`

func (q *Queries) ClearPendingEmail(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearPendingEmail, id)
	return err
}

const clearUserEmail = `-- name: ClearUserEmail :exec
UPDATE users
SET email = NULL, email_confirmed_at = NULL, pending_email = NULL, pending_email_at = NULL
WHERE id = $1
`

// ClearUserEmail drops both addresses, on removal and on deletion.
func (q *Queries) ClearUserEmail(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearUserEmail, id)
	return err
}

const confirmPendingEmail = `-- name: ConfirmPendingEmail :exec
UPDATE users
SET email = pending_email, email_confirmed_at = now(), pending_email = NULL, pending_email_at = NULL
WHERE id = $1 AND pending_email IS NOT NULL
`

// ConfirmPendingEmail makes the pending address the account's address.
func (q *Queries) ConfirmPendingEmail(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, confirmPendingEmail, id)
	return err
}

const emailConfirmedElsewhere = `-- name: EmailConfirmedElsewhere :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = $1::citext AND id <> $2::uuid
)
`

type EmailConfirmedElsewhereParams struct {
	Address string
	UserID  string
}

// EmailConfirmedElsewhere: another account already holds the address.
func (q *Queries) EmailConfirmedElsewhere(ctx context.Context, arg EmailConfirmedElsewhereParams) (bool, error) {
	row := q.db.QueryRow(ctx, emailConfirmedElsewhere, arg.Address, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setPendingEmail = `-- name: SetPendingEmail :exec

UPDATE users SET pending_email = $1::citext, pending_email_at = now()
WHERE id = $2::uuid
`

type SetPendingEmailParams struct {
	Address string
	ID      string
}

// Account email addresses on users. Owned by the auth module.
// Only internal/auth may use these queries.
func (q *Queries) SetPendingEmail(ctx context.Context, arg SetPendingEmailParams) error {
	_, err := q.db.Exec(ctx, setPendingEmail, arg.Address, arg.ID)
	return err
}
