// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package dbgen

import (
	"context"
	"time"
)

const countUnreadActivity = `-- name: CountUnreadActivity :one
SELECT count(*) FROM activity_items WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadActivity(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadActivity, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityItem = `-- name: CreateActivityItem :one

INSERT INTO activity_items (id, user_id, kind, space_id, channel_id, message_id, actor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, kind, space_id, channel_id, message_id, actor_id, created_at, read_at
`

type CreateActivityItemParams struct {
	ID        string
	UserID    string
	Kind      string
	SpaceID   *string
	ChannelID string
	MessageID *string
	ActorID   string
}

// Activity items. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) CreateActivityItem(ctx context.Context, arg CreateActivityItemParams) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, createActivityItem,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.SpaceID,
		arg.ChannelID,
		arg.MessageID,
		arg.ActorID,
	)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SpaceID,
		&i.ChannelID,
		&i.MessageID,
		&i.ActorID,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const deleteReadActivityBefore = `-- name: DeleteReadActivityBefore :execrows
DELETE FROM activity_items WHERE read_at IS NOT NULL AND read_at < $1::timestamptz
`

// DeleteReadActivityBefore drops read items older than the
// retention window; unread ones stay however old (see chat.SweepActivity).
func (q *Queries) DeleteReadActivityBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReadActivityBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUnreadActivityForChannel = `-- name: GetUnreadActivityForChannel :one
SELECT id, user_id, kind, space_id, channel_id, message_id, actor_id, created_at, read_at FROM activity_items
WHERE user_id = $1 AND channel_id = $2 AND kind = $3 AND read_at IS NULL
ORDER BY id DESC
LIMIT 1
`

type GetUnreadActivityForChannelParams struct {
	UserID    string
	ChannelID string
	Kind      string
}

// The unread activity item of one kind for a channel, if any: a DM's
// alerts coalesce into it instead of piling up (see chat.recordDM).
func (q *Queries) GetUnreadActivityForChannel(ctx context.Context, arg GetUnreadActivityForChannelParams) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, getUnreadActivityForChannel, arg.UserID, arg.ChannelID, arg.Kind)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SpaceID,
		&i.ChannelID,
		&i.MessageID,
		&i.ActorID,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listActivity = `-- name: ListActivity :many
SELECT a.id, a.user_id, a.kind, a.space_id, a.channel_id, a.message_id, a.actor_id, a.created_at, a.read_at, m.content AS message_content,
    COALESCE((SELECT f.file_id::text FROM message_attachments f WHERE f.message_id = m.id ORDER BY f.position LIMIT 1), '')::text AS message_first_file_id,
    (EXISTS (SELECT 1 FROM channel_mutes cm WHERE cm.user_id = a.user_id AND cm.channel_id = a.channel_id)
        OR EXISTS (SELECT 1 FROM space_mutes sm WHERE sm.user_id = a.user_id AND sm.space_id = a.space_id))::bool AS muted
FROM activity_items a
LEFT JOIN messages m ON m.id = a.message_id
WHERE a.user_id = $1
  AND ($3::uuid IS NULL OR a.id < $3::uuid)
ORDER BY a.id DESC
LIMIT $2
`

type ListActivityParams struct {
	UserID   string
	Limit    int32
	BeforeID *string
}

type ListActivityRow struct {
	ActivityItem       ActivityItem
	MessageContent     *string
	MessageFirstFileID string
	Muted              bool
}

// ListActivity returns newest first with the message text for a
// preview (NULL if the message has since been deleted), and the
// recipient's effective mute for where each item happened.
func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity, arg.UserID, arg.Limit, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityRow
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ActivityItem.ID,
			&i.ActivityItem.UserID,
			&i.ActivityItem.Kind,
			&i.ActivityItem.SpaceID,
			&i.ActivityItem.ChannelID,
			&i.ActivityItem.MessageID,
			&i.ActivityItem.ActorID,
			&i.ActivityItem.CreatedAt,
			&i.ActivityItem.ReadAt,
			&i.MessageContent,
			&i.MessageFirstFileID,
			&i.Muted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActivityRead = `-- name: MarkActivityRead :exec
UPDATE activity_items SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL AND id = ANY($2::uuid[])
`

type MarkActivityReadParams struct {
	UserID string
	Ids    []string
}

func (q *Queries) MarkActivityRead(ctx context.Context, arg MarkActivityReadParams) error {
	_, err := q.db.Exec(ctx, markActivityRead, arg.UserID, arg.Ids)
	return err
}

const markAllActivityRead = `-- name: MarkAllActivityRead :exec
UPDATE activity_items SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllActivityRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllActivityRead, userID)
	return err
}

const refreshActivityItem = `-- name: RefreshActivityItem :one
UPDATE activity_items SET message_id = $2, actor_id = $3, created_at = now()
WHERE id = $1
RETURNING id, user_id, kind, space_id, channel_id, message_id, actor_id, created_at, read_at
`

type RefreshActivityItemParams struct {
	ID        string
	MessageID *string
	ActorID   string
}

// RefreshActivityItem points an existing item at a newer message
// and stamps it now, so the entry reads as the latest activity.
func (q *Queries) RefreshActivityItem(ctx context.Context, arg RefreshActivityItemParams) (ActivityItem, error) {
	row := q.db.QueryRow(ctx, refreshActivityItem, arg.ID, arg.MessageID, arg.ActorID)
	var i ActivityItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SpaceID,
		&i.ChannelID,
		&i.MessageID,
		&i.ActorID,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}
