// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package dbgen

import (
	"context"
	"time"
)

const countUnreadActivity = `-- name: CountUnreadActivity :one
SELECT count(*) FROM activity_items WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadActivity(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadActivity, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityItems = `-- name: CreateActivityItems :many

INSERT INTO activity_items (id, user_id, kind, space_id, channel_id, message_id, actor_id)
SELECT unnest($1::uuid[]), unnest($2::uuid[]), $3::text,
    $4::uuid, $5::uuid, $6::uuid, $7::uuid
RETURNING id, user_id, kind, space_id, channel_id, message_id, actor_id, created_at, read_at
`

type CreateActivityItemsParams struct {
	Ids       []string
	UserIds   []string
	Kind      string
	SpaceID   *string
	ChannelID string
	MessageID string
	ActorID   string
}

// Activity items. Owned by the chat module.
// Only internal/chat may use these queries.
// CreateActivityItems writes one item of a kind for each recipient of
// a message, in one statement (see chat.notify).
func (q *Queries) CreateActivityItems(ctx context.Context, arg CreateActivityItemsParams) ([]ActivityItem, error) {
	rows, err := q.db.Query(ctx, createActivityItems,
		arg.Ids,
		arg.UserIds,
		arg.Kind,
		arg.SpaceID,
		arg.ChannelID,
		arg.MessageID,
		arg.ActorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityItem
	for rows.Next() {
		var i ActivityItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.SpaceID,
			&i.ChannelID,
			&i.MessageID,
			&i.ActorID,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteActivityForBlocked = `-- name: DeleteActivityForBlocked :execrows
DELETE FROM activity_items a
WHERE a.user_id = $1
  AND (a.actor_id = $2
    OR EXISTS (
      SELECT 1 FROM dm_members d
      WHERE d.channel_id = a.channel_id AND d.user_id = $2
    ))
`

type DeleteActivityForBlockedParams struct {
	UserID    string
	BlockedID string
}

// DeleteActivityForBlocked drops the alerts a block is meant to silence:
// anything the blocked person caused, and anything in a direct message
// they are part of. Without it a block leaves a badge nobody can clear —
// the conversation is hidden from the blocker's list, so there is nothing
// left to open and mark read.
func (q *Queries) DeleteActivityForBlocked(ctx context.Context, arg DeleteActivityForBlockedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivityForBlocked, arg.UserID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReadActivityBefore = `-- name: DeleteReadActivityBefore :execrows
DELETE FROM activity_items WHERE read_at IS NOT NULL AND read_at < $1::timestamptz
`

// DeleteReadActivityBefore drops read items older than the
// retention window; unread ones stay however old (see chat.SweepActivity).
func (q *Queries) DeleteReadActivityBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReadActivityBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActivity = `-- name: ListActivity :many
SELECT a.id, a.user_id, a.kind, a.space_id, a.channel_id, a.message_id, a.actor_id, a.created_at, a.read_at, m.content AS message_content, m.thread_root_id AS message_thread_root_id,
    COALESCE((SELECT f.file_id::text FROM message_attachments f WHERE f.message_id = m.id ORDER BY f.position LIMIT 1), '')::text AS message_first_file_id,
    (EXISTS (SELECT 1 FROM channel_mutes cm WHERE cm.user_id = a.user_id AND cm.channel_id = a.channel_id)
        OR EXISTS (SELECT 1 FROM space_mutes sm WHERE sm.user_id = a.user_id AND sm.space_id = a.space_id)
        OR EXISTS (SELECT 1 FROM thread_mutes tm WHERE tm.user_id = a.user_id AND tm.root_message_id = m.thread_root_id))::bool AS muted
FROM activity_items a
LEFT JOIN messages m ON m.id = a.message_id
WHERE a.user_id = $1
  AND ($3::uuid IS NULL OR a.id < $3::uuid)
ORDER BY a.id DESC
LIMIT $2
`

type ListActivityParams struct {
	UserID   string
	Limit    int32
	BeforeID *string
}

type ListActivityRow struct {
	ActivityItem        ActivityItem
	MessageContent      *string
	MessageThreadRootID *string
	MessageFirstFileID  string
	Muted               bool
}

// ListActivity returns newest first with the message text for a
// preview (NULL if the message has since been deleted), and the
// recipient's effective mute for where each item happened.
func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity, arg.UserID, arg.Limit, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityRow
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ActivityItem.ID,
			&i.ActivityItem.UserID,
			&i.ActivityItem.Kind,
			&i.ActivityItem.SpaceID,
			&i.ActivityItem.ChannelID,
			&i.ActivityItem.MessageID,
			&i.ActivityItem.ActorID,
			&i.ActivityItem.CreatedAt,
			&i.ActivityItem.ReadAt,
			&i.MessageContent,
			&i.MessageThreadRootID,
			&i.MessageFirstFileID,
			&i.Muted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActivityRead = `-- name: MarkActivityRead :exec
UPDATE activity_items SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL AND id = ANY($2::uuid[])
`

type MarkActivityReadParams struct {
	UserID string
	Ids    []string
}

func (q *Queries) MarkActivityRead(ctx context.Context, arg MarkActivityReadParams) error {
	_, err := q.db.Exec(ctx, markActivityRead, arg.UserID, arg.Ids)
	return err
}

const markAllActivityRead = `-- name: MarkAllActivityRead :exec
UPDATE activity_items SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllActivityRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllActivityRead, userID)
	return err
}

const upsertUnreadActivityItems = `-- name: UpsertUnreadActivityItems :many
WITH recipient AS (
    SELECT unnest($1::uuid[]) AS id, unnest($2::uuid[]) AS user_id
), unread AS (
    SELECT DISTINCT ON (a.user_id) a.id, a.user_id
    FROM activity_items a
    WHERE a.user_id = ANY($2::uuid[])
      AND a.channel_id = $3::uuid
      AND a.kind = $4::text
      AND a.read_at IS NULL
      AND ($5::uuid IS NULL
           OR EXISTS (SELECT 1 FROM messages m
                      WHERE m.id = a.message_id AND m.thread_root_id = $5::uuid))
    ORDER BY a.user_id, a.id DESC
), refreshed AS (
    UPDATE activity_items a
    SET message_id = $6::uuid, actor_id = $7::uuid, created_at = now()
    FROM unread u
    WHERE a.id = u.id
    RETURNING a.id, a.user_id, a.kind, a.space_id, a.channel_id, a.message_id, a.actor_id, a.created_at, a.read_at
), created AS (
    INSERT INTO activity_items (id, user_id, kind, space_id, channel_id, message_id, actor_id)
    SELECT r.id, r.user_id, $4::text, $8::uuid,
        $3::uuid, $6::uuid, $7::uuid
    FROM recipient r
    WHERE NOT EXISTS (SELECT 1 FROM unread u WHERE u.user_id = r.user_id)
    RETURNING id, user_id, kind, space_id, channel_id, message_id, actor_id, created_at, read_at
)
SELECT id, user_id, kind, space_id, channel_id, message_id, actor_id, created_at, read_at FROM refreshed
UNION ALL
SELECT id, user_id, kind, space_id, channel_id, message_id, actor_id, created_at, read_at FROM created
`

type UpsertUnreadActivityItemsParams struct {
	Ids          []string
	UserIds      []string
	ChannelID    string
	Kind         string
	ThreadRootID *string
	MessageID    string
	ActorID      string
	SpaceID      *string
}

type UpsertUnreadActivityItemsRow struct {
	ID        string
	UserID    string
	Kind      string
	SpaceID   *string
	ChannelID string
	MessageID *string
	ActorID   string
	CreatedAt time.Time
	ReadAt    *time.Time
}

// UpsertUnreadActivityItems is CreateActivityItems for a kind that
// coalesces per channel, as a DM's alerts do (see chat.recordDM), or per
// thread when thread_root_id is set: a recipient's newest unread item of
// the kind there is pointed at the new message and stamped now; a
// recipient without one gets a new item.
func (q *Queries) UpsertUnreadActivityItems(ctx context.Context, arg UpsertUnreadActivityItemsParams) ([]UpsertUnreadActivityItemsRow, error) {
	rows, err := q.db.Query(ctx, upsertUnreadActivityItems,
		arg.Ids,
		arg.UserIds,
		arg.ChannelID,
		arg.Kind,
		arg.ThreadRootID,
		arg.MessageID,
		arg.ActorID,
		arg.SpaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertUnreadActivityItemsRow
	for rows.Next() {
		var i UpsertUnreadActivityItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.SpaceID,
			&i.ChannelID,
			&i.MessageID,
			&i.ActorID,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
