// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package dbgen

import (
	"context"
)

const insertMessageAttachment = `-- name: InsertMessageAttachment :exec

INSERT INTO message_attachments (message_id, file_id, position)
VALUES ($1, $2, $3)
`

type InsertMessageAttachmentParams struct {
	MessageID string
	FileID    string
	Position  int32
}

// Message attachments: which files a message carries. Owned by the chat
// module; file metadata (name, type, size) comes from the files module
// through a port. Only internal/chat may use these queries.
func (q *Queries) InsertMessageAttachment(ctx context.Context, arg InsertMessageAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertMessageAttachment, arg.MessageID, arg.FileID, arg.Position)
	return err
}

const isAttachmentReadable = `-- name: IsAttachmentReadable :one
SELECT EXISTS (
    SELECT 1
    FROM message_attachments a
    JOIN messages m ON m.id = a.message_id
    JOIN channels c ON c.id = m.channel_id
    LEFT JOIN space_members sm ON sm.space_id = c.space_id AND sm.user_id = $2
    LEFT JOIN dm_members d ON d.channel_id = c.id AND d.user_id = $2
    WHERE a.file_id = $1 AND (sm.user_id IS NOT NULL OR d.user_id IS NOT NULL)
) AS readable
`

type IsAttachmentReadableParams struct {
	FileID string
	UserID string
}

// IsAttachmentReadable: the file is attached to a message in a channel
// the user can read (space member or DM participant). Files' download
// rule for attachments that have no space.
func (q *Queries) IsAttachmentReadable(ctx context.Context, arg IsAttachmentReadableParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAttachmentReadable, arg.FileID, arg.UserID)
	var readable bool
	err := row.Scan(&readable)
	return readable, err
}

const listAttachmentFileIDsForMessage = `-- name: ListAttachmentFileIDsForMessage :many
SELECT file_id FROM message_attachments WHERE message_id = $1 ORDER BY position
`

func (q *Queries) ListAttachmentFileIDsForMessage(ctx context.Context, messageID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttachmentFileIDsForMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_id string
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForMessages = `-- name: ListAttachmentsForMessages :many
SELECT message_id, file_id, position FROM message_attachments
WHERE message_id = ANY($1::uuid[])
ORDER BY message_id, position
`

func (q *Queries) ListAttachmentsForMessages(ctx context.Context, dollar_1 []string) ([]MessageAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAttachment
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(&i.MessageID, &i.FileID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const referencedFileIDs = `-- name: ReferencedFileIDs :many
SELECT a.file_id::uuid AS id FROM message_attachments a WHERE a.file_id = ANY($1::uuid[])
UNION
SELECT p.image_file_id::uuid FROM link_previews p WHERE p.image_file_id = ANY($1::uuid[])
UNION
SELECT s.icon_file_id::uuid FROM spaces s WHERE s.icon_file_id = ANY($1::uuid[])
`

// ReferencedFileIDs: which of these files chat still points at — an
// attachment on a message, a link preview's image, a space's icon. The
// files module's sweep asks through its port; anything else is an orphan.
func (q *Queries) ReferencedFileIDs(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, referencedFileIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
