// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bans.sql

package dbgen

import (
	"context"
)

const banUser = `-- name: BanUser :exec

INSERT INTO space_bans (space_id, user_id, banned_by, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (space_id, user_id) DO UPDATE
SET banned_by = EXCLUDED.banned_by, reason = EXCLUDED.reason, created_at = now()
`

type BanUserParams struct {
	SpaceID  string
	UserID   string
	BannedBy *string
	Reason   string
}

// Space bans. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser,
		arg.SpaceID,
		arg.UserID,
		arg.BannedBy,
		arg.Reason,
	)
	return err
}

const isBanned = `-- name: IsBanned :one
SELECT EXISTS (
    SELECT 1 FROM space_bans WHERE space_id = $1 AND user_id = $2
) AS banned
`

type IsBannedParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) IsBanned(ctx context.Context, arg IsBannedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBanned, arg.SpaceID, arg.UserID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const listBans = `-- name: ListBans :many
SELECT space_id, user_id, banned_by, reason, created_at FROM space_bans WHERE space_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBans(ctx context.Context, spaceID string) ([]SpaceBan, error) {
	rows, err := q.db.Query(ctx, listBans, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpaceBan
	for rows.Next() {
		var i SpaceBan
		if err := rows.Scan(
			&i.SpaceID,
			&i.UserID,
			&i.BannedBy,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanUser = `-- name: UnbanUser :execrows
DELETE FROM space_bans WHERE space_id = $1 AND user_id = $2
`

type UnbanUserParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) UnbanUser(ctx context.Context, arg UnbanUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unbanUser, arg.SpaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
