// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package dbgen

import (
	"context"
)

const blockUser = `-- name: BlockUser :exec

INSERT INTO user_blocks (blocker_id, blocked_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID string
	BlockedID string
}

// User blocks. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const blockedEitherWay = `-- name: BlockedEitherWay :one
SELECT EXISTS (
    SELECT 1 FROM user_blocks
    WHERE (blocker_id = $1 AND blocked_id = $2) OR (blocker_id = $2 AND blocked_id = $1)
) AS blocked
`

type BlockedEitherWayParams struct {
	BlockerID string
	BlockedID string
}

// BlockedEitherWay: does either of the two block the other?
func (q *Queries) BlockedEitherWay(ctx context.Context, arg BlockedEitherWayParams) (bool, error) {
	row := q.db.QueryRow(ctx, blockedEitherWay, arg.BlockerID, arg.BlockedID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const blockersAmong = `-- name: BlockersAmong :many
SELECT blocker_id FROM user_blocks
WHERE blocked_id = $1 AND blocker_id = ANY($2::uuid[])
`

type BlockersAmongParams struct {
	UserID string
	Ids    []string
}

// BlockersAmong: which of these users have blocked the given user (so a
// activity item from them is not written).
func (q *Queries) BlockersAmong(ctx context.Context, arg BlockersAmongParams) ([]string, error) {
	rows, err := q.db.Query(ctx, blockersAmong, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blocker_id string
		if err := rows.Scan(&blocker_id); err != nil {
			return nil, err
		}
		items = append(items, blocker_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasBlocked = `-- name: HasBlocked :one
SELECT EXISTS (
    SELECT 1 FROM user_blocks WHERE blocker_id = $1 AND blocked_id = $2
) AS blocked
`

type HasBlockedParams struct {
	BlockerID string
	BlockedID string
}

// HasBlocked: has blocker blocked blocked?
func (q *Queries) HasBlocked(ctx context.Context, arg HasBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasBlocked, arg.BlockerID, arg.BlockedID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listBlockedUserIDs = `-- name: ListBlockedUserIDs :many
SELECT blocked_id FROM user_blocks WHERE blocker_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBlockedUserIDs(ctx context.Context, blockerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listBlockedUserIDs, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blocked_id string
		if err := rows.Scan(&blocked_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :execrows
DELETE FROM user_blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID string
	BlockedID string
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
