// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package dbgen

import (
	"context"
	"time"
)

const addCredentialChannelBound = `-- name: AddCredentialChannelBound :exec
INSERT INTO credential_bounds (credential_id, channel_id)
VALUES ($1::uuid, $2::uuid)
`

type AddCredentialChannelBoundParams struct {
	CredentialID string
	ChannelID    string
}

func (q *Queries) AddCredentialChannelBound(ctx context.Context, arg AddCredentialChannelBoundParams) error {
	_, err := q.db.Exec(ctx, addCredentialChannelBound, arg.CredentialID, arg.ChannelID)
	return err
}

const countBotCredentials = `-- name: CountBotCredentials :one
SELECT count(*) FROM credentials WHERE holder_id = $1 AND kind IN ('bot_token', 'incoming_hook')
`

func (q *Queries) CountBotCredentials(ctx context.Context, holderID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBotCredentials, holderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBot = `-- name: CreateBot :one

INSERT INTO users (id, username, display_name, password_hash, role, kind)
VALUES ($1, $2, $3, NULL, 'member', 'bot')
RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type CreateBotParams struct {
	ID          string
	Username    string
	DisplayName string
}

// Bots and the credentials they hold. Owned by the auth module.
// Only internal/auth may use these queries.
func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (User, error) {
	row := q.db.QueryRow(ctx, createBot, arg.ID, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const createBotCredential = `-- name: CreateBotCredential :one
INSERT INTO credentials (id, holder_id, kind, token_hash, name, grants, bounded, created_by, hint)
SELECT $1::uuid, u.id, $2::text, $3::bytea,
       $4::text, $5::text[], $6::boolean,
       $7::uuid, $8::text
FROM users u
WHERE u.id = $9::uuid AND u.kind = 'bot' AND u.deactivated_at IS NULL
RETURNING id, holder_id, kind, token_hash, name, grants, bounded, created_by, created_at, expires_at, last_used_at, hint, user_agent
`

type CreateBotCredentialParams struct {
	ID        string
	Kind      string
	TokenHash []byte
	Name      string
	Grants    []string
	Bounded   bool
	CreatedBy *string
	Hint      string
	HolderID  string
}

// CreateBotCredential mints a bot token or hook token; the holder must be
// a bot, or no row is inserted.
func (q *Queries) CreateBotCredential(ctx context.Context, arg CreateBotCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createBotCredential,
		arg.ID,
		arg.Kind,
		arg.TokenHash,
		arg.Name,
		arg.Grants,
		arg.Bounded,
		arg.CreatedBy,
		arg.Hint,
		arg.HolderID,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.HolderID,
		&i.Kind,
		&i.TokenHash,
		&i.Name,
		&i.Grants,
		&i.Bounded,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Hint,
		&i.UserAgent,
	)
	return i, err
}

const deleteBotCredential = `-- name: DeleteBotCredential :many
DELETE FROM credentials
WHERE id = $1 AND kind IN ('bot_token', 'incoming_hook')
RETURNING id, holder_id
`

type DeleteBotCredentialRow struct {
	ID       string
	HolderID string
}

func (q *Queries) DeleteBotCredential(ctx context.Context, id string) ([]DeleteBotCredentialRow, error) {
	rows, err := q.db.Query(ctx, deleteBotCredential, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteBotCredentialRow
	for rows.Next() {
		var i DeleteBotCredentialRow
		if err := rows.Scan(&i.ID, &i.HolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBotCredentials = `-- name: GetBotCredentials :many
SELECT c.id, c.holder_id, c.kind, c.name, c.grants, c.bounded, c.created_at, c.last_used_at, c.hint,
       coalesce(array_agg(b.space_id) FILTER (WHERE b.space_id IS NOT NULL), '{}')::uuid[] AS bound_spaces,
       coalesce(array_agg(b.channel_id) FILTER (WHERE b.channel_id IS NOT NULL), '{}')::uuid[] AS bound_channels
FROM credentials c
LEFT JOIN credential_bounds b ON b.credential_id = c.id
WHERE c.kind IN ('bot_token', 'incoming_hook') AND c.id = ANY($1::uuid[])
GROUP BY c.id
`

type GetBotCredentialsRow struct {
	ID            string
	HolderID      string
	Kind          string
	Name          string
	Grants        []string
	Bounded       bool
	CreatedAt     time.Time
	LastUsedAt    *time.Time
	Hint          string
	BoundSpaces   []string
	BoundChannels []string
}

func (q *Queries) GetBotCredentials(ctx context.Context, ids []string) ([]GetBotCredentialsRow, error) {
	rows, err := q.db.Query(ctx, getBotCredentials, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBotCredentialsRow
	for rows.Next() {
		var i GetBotCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.HolderID,
			&i.Kind,
			&i.Name,
			&i.Grants,
			&i.Bounded,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Hint,
			&i.BoundSpaces,
			&i.BoundChannels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotCredentials = `-- name: ListBotCredentials :many
SELECT c.id, c.holder_id, c.kind, c.name, c.grants, c.bounded, c.created_at, c.last_used_at, c.hint,
       coalesce(array_agg(b.space_id) FILTER (WHERE b.space_id IS NOT NULL), '{}')::uuid[] AS bound_spaces,
       coalesce(array_agg(b.channel_id) FILTER (WHERE b.channel_id IS NOT NULL), '{}')::uuid[] AS bound_channels
FROM credentials c
LEFT JOIN credential_bounds b ON b.credential_id = c.id
WHERE c.kind IN ('bot_token', 'incoming_hook')
  AND (cardinality($1::uuid[]) = 0 OR c.holder_id = ANY($1::uuid[]))
GROUP BY c.id
ORDER BY c.created_at, c.id
`

type ListBotCredentialsRow struct {
	ID            string
	HolderID      string
	Kind          string
	Name          string
	Grants        []string
	Bounded       bool
	CreatedAt     time.Time
	LastUsedAt    *time.Time
	Hint          string
	BoundSpaces   []string
	BoundChannels []string
}

// ListBotCredentials is every token and hook credential, for the given
// holders or, with an empty list, for every bot.
func (q *Queries) ListBotCredentials(ctx context.Context, holderIds []string) ([]ListBotCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listBotCredentials, holderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotCredentialsRow
	for rows.Next() {
		var i ListBotCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.HolderID,
			&i.Kind,
			&i.Name,
			&i.Grants,
			&i.Bounded,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Hint,
			&i.BoundSpaces,
			&i.BoundChannels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBots = `-- name: ListBots :many
SELECT id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner FROM users WHERE kind = 'bot' ORDER BY created_at, id
`

func (q *Queries) ListBots(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.Role,
			&i.DeactivatedAt,
			&i.AvatarFileID,
			&i.UsernamePending,
			&i.UsernameFrozen,
			&i.Pronouns,
			&i.Bio,
			&i.Kind,
			&i.Dnd,
			&i.DndUntil,
			&i.DeletedAt,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBotCredentialGrants = `-- name: SetBotCredentialGrants :execrows
UPDATE credentials SET grants = $2
WHERE id = $1 AND kind IN ('bot_token', 'incoming_hook')
`

type SetBotCredentialGrantsParams struct {
	ID     string
	Grants []string
}

func (q *Queries) SetBotCredentialGrants(ctx context.Context, arg SetBotCredentialGrantsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBotCredentialGrants, arg.ID, arg.Grants)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
