// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package dbgen

import (
	"context"
)

const countChannelsInSpace = `-- name: CountChannelsInSpace :one
SELECT count(*) FROM channels WHERE space_id = $1::uuid
`

func (q *Queries) CountChannelsInSpace(ctx context.Context, spaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelsInSpace, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :one

INSERT INTO channels (id, space_id, name, kind, position)
VALUES ($1, $2::uuid, $3, $4, $5)
RETURNING id, space_id, name, kind, position, created_at, last_message_id, dm_key, topic
`

type CreateChannelParams struct {
	ID       string
	SpaceID  string
	Name     string
	Kind     int16
	Position int32
}

// Channels within a space. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.SpaceID,
		arg.Name,
		arg.Kind,
		arg.Position,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Kind,
		&i.Position,
		&i.CreatedAt,
		&i.LastMessageID,
		&i.DmKey,
		&i.Topic,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, space_id, name, kind, position, created_at, last_message_id, dm_key, topic FROM channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Kind,
		&i.Position,
		&i.CreatedAt,
		&i.LastMessageID,
		&i.DmKey,
		&i.Topic,
	)
	return i, err
}

const listChannelIDsByKind = `-- name: ListChannelIDsByKind :many
SELECT id FROM channels WHERE space_id = $1::uuid AND kind = $2
ORDER BY position, created_at
`

type ListChannelIDsByKindParams struct {
	SpaceID string
	Kind    int16
}

// ListChannelIDsByKind lists a space's channels of one kind. Voice channel
// ids are also their LiveKit room names, so this is what a kick has to
// clear someone out of.
func (q *Queries) ListChannelIDsByKind(ctx context.Context, arg ListChannelIDsByKindParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listChannelIDsByKind, arg.SpaceID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsBySpace = `-- name: ListChannelsBySpace :many
SELECT c.id, c.space_id, c.name, c.kind, c.position, c.created_at, c.last_message_id, c.dm_key, c.topic, r.last_read_message_id,
    EXISTS (SELECT 1 FROM channel_mutes cm WHERE cm.channel_id = c.id AND cm.user_id = $1) AS muted,
    (SELECT count(*) FROM messages m
     WHERE m.channel_id = c.id
       AND (r.last_read_message_id IS NULL OR m.id > r.last_read_message_id)) AS unread_count
FROM channels c
LEFT JOIN channel_reads r ON r.channel_id = c.id AND r.user_id = $1
WHERE c.space_id = $2::uuid
ORDER BY c.position, c.created_at
`

type ListChannelsBySpaceParams struct {
	UserID  string
	SpaceID string
}

type ListChannelsBySpaceRow struct {
	Channel           Channel
	LastReadMessageID *string
	Muted             bool
	UnreadCount       int64
}

// ListChannelsBySpace includes the caller's read marker, how many
// messages are newer than it (all of them if they've never opened it),
// and whether they muted it.
func (q *Queries) ListChannelsBySpace(ctx context.Context, arg ListChannelsBySpaceParams) ([]ListChannelsBySpaceRow, error) {
	rows, err := q.db.Query(ctx, listChannelsBySpace, arg.UserID, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsBySpaceRow
	for rows.Next() {
		var i ListChannelsBySpaceRow
		if err := rows.Scan(
			&i.Channel.ID,
			&i.Channel.SpaceID,
			&i.Channel.Name,
			&i.Channel.Kind,
			&i.Channel.Position,
			&i.Channel.CreatedAt,
			&i.Channel.LastMessageID,
			&i.Channel.DmKey,
			&i.Channel.Topic,
			&i.LastReadMessageID,
			&i.Muted,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelLastMessage = `-- name: SetChannelLastMessage :exec
UPDATE channels SET last_message_id = $2 WHERE id = $1
`

type SetChannelLastMessageParams struct {
	ID            string
	LastMessageID *string
}

func (q *Queries) SetChannelLastMessage(ctx context.Context, arg SetChannelLastMessageParams) error {
	_, err := q.db.Exec(ctx, setChannelLastMessage, arg.ID, arg.LastMessageID)
	return err
}

const setChannelPosition = `-- name: SetChannelPosition :exec
UPDATE channels SET position = $1 WHERE id = $2 AND space_id = $3::uuid
`

type SetChannelPositionParams struct {
	Position int32
	ID       string
	SpaceID  string
}

func (q *Queries) SetChannelPosition(ctx context.Context, arg SetChannelPositionParams) error {
	_, err := q.db.Exec(ctx, setChannelPosition, arg.Position, arg.ID, arg.SpaceID)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = COALESCE($2, name),
    position = COALESCE($3, position),
    topic = COALESCE($4, topic)
WHERE id = $1
RETURNING id, space_id, name, kind, position, created_at, last_message_id, dm_key, topic
`

type UpdateChannelParams struct {
	ID       string
	Name     *string
	Position *int32
	Topic    *string
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Position,
		arg.Topic,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Kind,
		&i.Position,
		&i.CreatedAt,
		&i.LastMessageID,
		&i.DmKey,
		&i.Topic,
	)
	return i, err
}

const upsertChannelRead = `-- name: UpsertChannelRead :exec
INSERT INTO channel_reads (user_id, channel_id, last_read_message_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, channel_id) DO UPDATE
SET last_read_message_id = GREATEST(channel_reads.last_read_message_id, EXCLUDED.last_read_message_id),
    updated_at = now()
`

type UpsertChannelReadParams struct {
	UserID            string
	ChannelID         string
	LastReadMessageID string
}

// UpsertChannelRead moves a user's marker forward; it never goes backwards
// (UUIDv7 IDs are time-ordered, so GREATEST is "newest").
func (q *Queries) UpsertChannelRead(ctx context.Context, arg UpsertChannelReadParams) error {
	_, err := q.db.Exec(ctx, upsertChannelRead, arg.UserID, arg.ChannelID, arg.LastReadMessageID)
	return err
}
