// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_members.sql

package dbgen

import (
	"context"
)

const addChannelMembers = `-- name: AddChannelMembers :many
INSERT INTO channel_members (channel_id, space_id, user_id, added_by)
SELECT c.id, c.space_id, sm.user_id, $1::uuid
FROM channels c
JOIN space_members sm ON sm.space_id = c.space_id
WHERE c.id = $2::uuid
  AND sm.user_id = ANY($3::uuid[])
ON CONFLICT DO NOTHING
RETURNING user_id
`

type AddChannelMembersParams struct {
	AddedBy   *string
	ChannelID string
	UserIds   []string
}

// AddChannelMembers adds the people named who are in the channel's space
// and not yet in the channel, and returns who that was.
func (q *Queries) AddChannelMembers(ctx context.Context, arg AddChannelMembersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, addChannelMembers, arg.AddedBy, arg.ChannelID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addEveryoneToChannel = `-- name: AddEveryoneToChannel :many
INSERT INTO channel_members (channel_id, space_id, user_id, added_by)
SELECT c.id, c.space_id, sm.user_id, $1::uuid
FROM channels c
JOIN space_members sm ON sm.space_id = c.space_id
WHERE c.id = $2::uuid
ON CONFLICT DO NOTHING
RETURNING user_id
`

type AddEveryoneToChannelParams struct {
	AddedBy   *string
	ChannelID string
}

func (q *Queries) AddEveryoneToChannel(ctx context.Context, arg AddEveryoneToChannelParams) ([]string, error) {
	rows, err := q.db.Query(ctx, addEveryoneToChannel, arg.AddedBy, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isInChannel = `-- name: IsInChannel :one

SELECT EXISTS (
    SELECT 1 FROM channel_members WHERE channel_id = $1 AND user_id = $2
) AS is_in
`

type IsInChannelParams struct {
	ChannelID string
	UserID    string
}

// Who is in a text channel. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) IsInChannel(ctx context.Context, arg IsInChannelParams) (bool, error) {
	row := q.db.QueryRow(ctx, isInChannel, arg.ChannelID, arg.UserID)
	var is_in bool
	err := row.Scan(&is_in)
	return is_in, err
}

const listChannelMemberIDs = `-- name: ListChannelMemberIDs :many
SELECT user_id FROM channel_members WHERE channel_id = $1
`

func (q *Queries) ListChannelMemberIDs(ctx context.Context, channelID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listChannelMemberIDs, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMembers = `-- name: ListChannelMembers :many
SELECT sm.space_id, sm.user_id, sm.joined_at, sm.role FROM space_members sm
JOIN channel_members cm ON cm.space_id = sm.space_id AND cm.user_id = sm.user_id
WHERE cm.channel_id = $1
ORDER BY CASE sm.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END, sm.joined_at
`

// ListChannelMembers orders as ListSpaceMembers does.
func (q *Queries) ListChannelMembers(ctx context.Context, channelID string) ([]SpaceMember, error) {
	rows, err := q.db.Query(ctx, listChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpaceMember
	for rows.Next() {
		var i SpaceMember
		if err := rows.Scan(
			&i.SpaceID,
			&i.UserID,
			&i.JoinedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelReadFor = `-- name: MarkChannelReadFor :exec
INSERT INTO channel_reads (user_id, channel_id, last_read_message_id)
SELECT u.id, $1::uuid, $2::uuid
FROM unnest($3::uuid[]) AS u(id)
ON CONFLICT (user_id, channel_id) DO UPDATE
SET last_read_message_id = GREATEST(channel_reads.last_read_message_id, EXCLUDED.last_read_message_id),
    updated_at = now()
`

type MarkChannelReadForParams struct {
	ChannelID         string
	LastReadMessageID string
	UserIds           []string
}

// MarkChannelReadFor moves several people's markers to one message, for
// people put in a channel who should not find its whole history unread.
func (q *Queries) MarkChannelReadFor(ctx context.Context, arg MarkChannelReadForParams) error {
	_, err := q.db.Exec(ctx, markChannelReadFor, arg.ChannelID, arg.LastReadMessageID, arg.UserIds)
	return err
}

const removeChannelMember = `-- name: RemoveChannelMember :execrows
DELETE FROM channel_members WHERE channel_id = $1 AND user_id = $2
`

type RemoveChannelMemberParams struct {
	ChannelID string
	UserID    string
}

func (q *Queries) RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeChannelMember, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
