// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package dbgen

import (
	"context"
	"time"
)

const addCredentialSpaceBound = `-- name: AddCredentialSpaceBound :exec
INSERT INTO credential_bounds (credential_id, space_id)
VALUES ($1::uuid, $2::uuid)
`

type AddCredentialSpaceBoundParams struct {
	CredentialID string
	SpaceID      string
}

func (q *Queries) AddCredentialSpaceBound(ctx context.Context, arg AddCredentialSpaceBoundParams) error {
	_, err := q.db.Exec(ctx, addCredentialSpaceBound, arg.CredentialID, arg.SpaceID)
	return err
}

const countPersonalTokensByHolder = `-- name: CountPersonalTokensByHolder :many
SELECT holder_id, count(*) AS n FROM credentials WHERE kind = 'personal_token' GROUP BY holder_id
`

type CountPersonalTokensByHolderRow struct {
	HolderID string
	N        int64
}

func (q *Queries) CountPersonalTokensByHolder(ctx context.Context) ([]CountPersonalTokensByHolderRow, error) {
	rows, err := q.db.Query(ctx, countPersonalTokensByHolder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPersonalTokensByHolderRow
	for rows.Next() {
		var i CountPersonalTokensByHolderRow
		if err := rows.Scan(&i.HolderID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPersonalToken = `-- name: CreatePersonalToken :one
INSERT INTO credentials (id, holder_id, kind, token_hash, name, grants, bounded, created_by, expires_at, hint)
VALUES ($1::uuid, $2::uuid, 'personal_token', $3::bytea,
        $4::text, $5::text[], $6::boolean, $2::uuid,
        $7::timestamptz, $8::text)
RETURNING id, holder_id, kind, token_hash, name, grants, bounded, created_by, created_at, expires_at, last_used_at, hint, user_agent
`

type CreatePersonalTokenParams struct {
	ID        string
	HolderID  string
	TokenHash []byte
	Name      string
	Grants    []string
	Bounded   bool
	ExpiresAt *time.Time
	Hint      string
}

func (q *Queries) CreatePersonalToken(ctx context.Context, arg CreatePersonalTokenParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createPersonalToken,
		arg.ID,
		arg.HolderID,
		arg.TokenHash,
		arg.Name,
		arg.Grants,
		arg.Bounded,
		arg.ExpiresAt,
		arg.Hint,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.HolderID,
		&i.Kind,
		&i.TokenHash,
		&i.Name,
		&i.Grants,
		&i.Bounded,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Hint,
		&i.UserAgent,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO credentials (id, holder_id, kind, token_hash, expires_at, user_agent)
SELECT $1::uuid, u.id, 'session', $2::bytea, $3::timestamptz,
       $4::text
FROM users u
WHERE u.id = $5::uuid AND u.kind = 'person'
RETURNING id
`

type CreateSessionParams struct {
	ID        string
	TokenHash []byte
	ExpiresAt time.Time
	UserAgent string
	HolderID  string
}

// Credentials. Owned by the auth module.
// Only internal/auth may use these queries.
//
// Until the contract migration drops sessions, every revocation also clears
// the matching legacy rows, so rolling back to the previous release can't
// bring a revoked session back. Every revocation returns what it removed,
// so auth can tell the gateway to close the sockets opened with it.
// CreateSession mints a session for a person. A bot never gets one: the
// insert finds no holder and returns no row.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.HolderID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteCredential = `-- name: DeleteCredential :many
WITH legacy AS (DELETE FROM sessions WHERE sessions.id = $1)
DELETE FROM credentials WHERE credentials.id = $1
RETURNING id, holder_id
`

type DeleteCredentialRow struct {
	ID       string
	HolderID string
}

func (q *Queries) DeleteCredential(ctx context.Context, id string) ([]DeleteCredentialRow, error) {
	rows, err := q.db.Query(ctx, deleteCredential, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteCredentialRow
	for rows.Next() {
		var i DeleteCredentialRow
		if err := rows.Scan(&i.ID, &i.HolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :many
WITH legacy AS (DELETE FROM sessions WHERE user_id = $1 AND sessions.id <> $2)
DELETE FROM credentials
WHERE holder_id = $1 AND kind = 'session' AND credentials.id <> $2
RETURNING id, holder_id
`

type DeleteOtherSessionsParams struct {
	HolderID string
	ID       string
}

type DeleteOtherSessionsRow struct {
	ID       string
	HolderID string
}

// DeleteOtherSessions signs a person out everywhere except the calling
// session (used after a password change).
func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) ([]DeleteOtherSessionsRow, error) {
	rows, err := q.db.Query(ctx, deleteOtherSessions, arg.HolderID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteOtherSessionsRow
	for rows.Next() {
		var i DeleteOtherSessionsRow
		if err := rows.Scan(&i.ID, &i.HolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePersonalToken = `-- name: DeletePersonalToken :many
DELETE FROM credentials
WHERE id = $1::uuid AND holder_id = $2::uuid AND kind = 'personal_token'
RETURNING id, holder_id
`

type DeletePersonalTokenParams struct {
	ID       string
	HolderID string
}

type DeletePersonalTokenRow struct {
	ID       string
	HolderID string
}

func (q *Queries) DeletePersonalToken(ctx context.Context, arg DeletePersonalTokenParams) ([]DeletePersonalTokenRow, error) {
	rows, err := q.db.Query(ctx, deletePersonalToken, arg.ID, arg.HolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletePersonalTokenRow
	for rows.Next() {
		var i DeletePersonalTokenRow
		if err := rows.Scan(&i.ID, &i.HolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserCredentials = `-- name: DeleteUserCredentials :many
WITH legacy AS (DELETE FROM sessions WHERE user_id = $1)
DELETE FROM credentials WHERE holder_id = $1
RETURNING id, holder_id
`

type DeleteUserCredentialsRow struct {
	ID       string
	HolderID string
}

// DeleteUserCredentials revokes everything an account holds, on
// deactivation and on an admin password reset.
func (q *Queries) DeleteUserCredentials(ctx context.Context, holderID string) ([]DeleteUserCredentialsRow, error) {
	rows, err := q.db.Query(ctx, deleteUserCredentials, holderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteUserCredentialsRow
	for rows.Next() {
		var i DeleteUserCredentialsRow
		if err := rows.Scan(&i.ID, &i.HolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserPersonalTokens = `-- name: DeleteUserPersonalTokens :many
DELETE FROM credentials WHERE holder_id = $1 AND kind = 'personal_token'
RETURNING id, holder_id
`

type DeleteUserPersonalTokensRow struct {
	ID       string
	HolderID string
}

func (q *Queries) DeleteUserPersonalTokens(ctx context.Context, holderID string) ([]DeleteUserPersonalTokensRow, error) {
	rows, err := q.db.Query(ctx, deleteUserPersonalTokens, holderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteUserPersonalTokensRow
	for rows.Next() {
		var i DeleteUserPersonalTokensRow
		if err := rows.Scan(&i.ID, &i.HolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialByTokenHash = `-- name: GetCredentialByTokenHash :one
SELECT c.id, c.holder_id, c.kind, c.grants, c.bounded, c.last_used_at,
       u.role AS holder_role, u.kind AS holder_kind,
       coalesce(array_agg(b.space_id) FILTER (WHERE b.space_id IS NOT NULL), '{}')::uuid[] AS bound_spaces,
       coalesce(array_agg(b.channel_id) FILTER (WHERE b.channel_id IS NOT NULL), '{}')::uuid[] AS bound_channels
FROM credentials c
JOIN users u ON u.id = c.holder_id
LEFT JOIN credential_bounds b ON b.credential_id = c.id
WHERE c.token_hash = $1
  AND (c.expires_at IS NULL OR c.expires_at > now())
  AND u.deactivated_at IS NULL
GROUP BY c.id, u.role, u.kind
`

type GetCredentialByTokenHashRow struct {
	ID            string
	HolderID      string
	Kind          string
	Grants        []string
	Bounded       bool
	LastUsedAt    *time.Time
	HolderRole    string
	HolderKind    string
	BoundSpaces   []string
	BoundChannels []string
}

// GetCredentialByTokenHash is the whole of verification: the credential,
// its holder's role and kind, and its bounds.
func (q *Queries) GetCredentialByTokenHash(ctx context.Context, tokenHash []byte) (GetCredentialByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByTokenHash, tokenHash)
	var i GetCredentialByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.HolderID,
		&i.Kind,
		&i.Grants,
		&i.Bounded,
		&i.LastUsedAt,
		&i.HolderRole,
		&i.HolderKind,
		&i.BoundSpaces,
		&i.BoundChannels,
	)
	return i, err
}

const getCredentialCreatedAt = `-- name: GetCredentialCreatedAt :one
SELECT created_at FROM credentials WHERE id = $1
`

func (q *Queries) GetCredentialCreatedAt(ctx context.Context, id string) (time.Time, error) {
	row := q.db.QueryRow(ctx, getCredentialCreatedAt, id)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listPersonalTokens = `-- name: ListPersonalTokens :many
SELECT c.id, c.name, c.grants, c.bounded, c.created_at, c.last_used_at, c.expires_at, c.hint,
       coalesce(array_agg(b.space_id) FILTER (WHERE b.space_id IS NOT NULL), '{}')::uuid[] AS bound_spaces
FROM credentials c
LEFT JOIN credential_bounds b ON b.credential_id = c.id
WHERE c.holder_id = $1 AND c.kind = 'personal_token'
GROUP BY c.id
ORDER BY c.created_at DESC
`

type ListPersonalTokensRow struct {
	ID          string
	Name        string
	Grants      []string
	Bounded     bool
	CreatedAt   time.Time
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	Hint        string
	BoundSpaces []string
}

// ListPersonalTokens is one account's tokens, expired ones included.
func (q *Queries) ListPersonalTokens(ctx context.Context, holderID string) ([]ListPersonalTokensRow, error) {
	rows, err := q.db.Query(ctx, listPersonalTokens, holderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonalTokensRow
	for rows.Next() {
		var i ListPersonalTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grants,
			&i.Bounded,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.Hint,
			&i.BoundSpaces,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, created_at, last_used_at, expires_at, user_agent
FROM credentials
WHERE holder_id = $1 AND kind = 'session' AND expires_at > now()
ORDER BY coalesce(last_used_at, created_at) DESC
`

type ListSessionsRow struct {
	ID         string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	ExpiresAt  *time.Time
	UserAgent  string
}

// ListSessions is one person's live sessions, most recently used first.
func (q *Queries) ListSessions(ctx context.Context, holderID string) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, holderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepCredentials = `-- name: SweepCredentials :many
WITH legacy AS (DELETE FROM sessions WHERE sessions.expires_at <= now())
DELETE FROM credentials
WHERE (kind = 'session' AND expires_at <= now())
   OR (kind <> 'session' AND expires_at <= $1::timestamptz)
RETURNING id, holder_id
`

type SweepCredentialsRow struct {
	ID       string
	HolderID string
}

// SweepCredentials deletes sessions once they expire, and other credentials
// once they expired before expired_before, so a list can still explain a
// recently expired token.
func (q *Queries) SweepCredentials(ctx context.Context, expiredBefore time.Time) ([]SweepCredentialsRow, error) {
	rows, err := q.db.Query(ctx, sweepCredentials, expiredBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweepCredentialsRow
	for rows.Next() {
		var i SweepCredentialsRow
		if err := rows.Scan(&i.ID, &i.HolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCredential = `-- name: TouchCredential :exec
UPDATE credentials SET last_used_at = now() WHERE id = $1
`

// TouchCredential records a token's use. The caller throttles it.
func (q *Queries) TouchCredential(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchCredential, id)
	return err
}
