// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package dbgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one

INSERT INTO credentials (id, holder_id, kind, token_hash, expires_at)
SELECT $1::uuid, u.id, 'session', $2::bytea, $3::timestamptz
FROM users u
WHERE u.id = $4::uuid AND u.kind = 'person'
RETURNING id
`

type CreateSessionParams struct {
	ID        string
	TokenHash []byte
	ExpiresAt time.Time
	HolderID  string
}

// Credentials. Owned by the auth module.
// Only internal/auth may use these queries.
//
// Until the contract migration drops sessions, every revocation also clears
// the matching legacy rows, so rolling back to the previous release can't
// bring a revoked session back.
// CreateSession mints a session for a person. A bot never gets one: the
// insert finds no holder and returns no row.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.HolderID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteCredential = `-- name: DeleteCredential :exec
WITH legacy AS (DELETE FROM sessions WHERE sessions.id = $1)
DELETE FROM credentials WHERE credentials.id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCredential, id)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
WITH legacy AS (DELETE FROM sessions WHERE user_id = $1 AND sessions.id <> $2)
DELETE FROM credentials
WHERE holder_id = $1 AND kind = 'session' AND credentials.id <> $2
`

type DeleteOtherSessionsParams struct {
	HolderID string
	ID       string
}

// DeleteOtherSessions signs a person out everywhere except the calling
// session (used after a password change).
func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessions, arg.HolderID, arg.ID)
	return err
}

const deleteUserCredentials = `-- name: DeleteUserCredentials :exec
WITH legacy AS (DELETE FROM sessions WHERE user_id = $1)
DELETE FROM credentials WHERE holder_id = $1
`

// DeleteUserCredentials revokes everything an account holds, on
// deactivation and on an admin password reset.
func (q *Queries) DeleteUserCredentials(ctx context.Context, holderID string) error {
	_, err := q.db.Exec(ctx, deleteUserCredentials, holderID)
	return err
}

const getCredentialByTokenHash = `-- name: GetCredentialByTokenHash :one
SELECT c.id, c.holder_id, c.kind, c.grants, c.bounded,
       u.role AS holder_role, u.kind AS holder_kind,
       coalesce(array_agg(b.space_id) FILTER (WHERE b.space_id IS NOT NULL), '{}')::uuid[] AS bound_spaces,
       coalesce(array_agg(b.channel_id) FILTER (WHERE b.channel_id IS NOT NULL), '{}')::uuid[] AS bound_channels
FROM credentials c
JOIN users u ON u.id = c.holder_id
LEFT JOIN credential_bounds b ON b.credential_id = c.id
WHERE c.token_hash = $1
  AND (c.expires_at IS NULL OR c.expires_at > now())
  AND u.deactivated_at IS NULL
GROUP BY c.id, u.role, u.kind
`

type GetCredentialByTokenHashRow struct {
	ID            string
	HolderID      string
	Kind          string
	Grants        []string
	Bounded       bool
	HolderRole    string
	HolderKind    string
	BoundSpaces   []string
	BoundChannels []string
}

// GetCredentialByTokenHash is the whole of verification: the credential,
// its holder's role and kind, and its bounds.
func (q *Queries) GetCredentialByTokenHash(ctx context.Context, tokenHash []byte) (GetCredentialByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByTokenHash, tokenHash)
	var i GetCredentialByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.HolderID,
		&i.Kind,
		&i.Grants,
		&i.Bounded,
		&i.HolderRole,
		&i.HolderKind,
		&i.BoundSpaces,
		&i.BoundChannels,
	)
	return i, err
}
