// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_stats.sql

package dbgen

import (
	"context"
	"time"
)

const deliveryStats = `-- name: DeliveryStats :one

SELECT
    count(*) FILTER (WHERE finished_at IS NOT NULL
        AND (status_code IS NULL OR status_code NOT BETWEEN 200 AND 299))::bigint AS dead,
    count(*) FILTER (WHERE finished_at IS NOT NULL
        AND (status_code IS NULL OR status_code NOT BETWEEN 200 AND 299)
        AND finished_at >= $1::timestamptz)::bigint AS dead_last_hour,
    (SELECT count(*) FROM outgoing_webhooks)::bigint AS hooks
FROM webhook_deliveries
`

type DeliveryStatsRow struct {
	Dead         int64
	DeadLastHour int64
	Hooks        int64
}

// The Background work panel's view of the delivery log, in one pass. A
// finished delivery is dead unless its status was 2xx, the reading
// settleDead makes. The hook count is for the OFF state. Queued and
// in-flight counts come from the jobs module. See
// docs/architecture/diagnostics.md.
func (q *Queries) DeliveryStats(ctx context.Context, since time.Time) (DeliveryStatsRow, error) {
	row := q.db.QueryRow(ctx, deliveryStats, since)
	var i DeliveryStatsRow
	err := row.Scan(&i.Dead, &i.DeadLastHour, &i.Hooks)
	return i, err
}
