// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package dbgen

import (
	"context"
	"time"
)

const ackDelivery = `-- name: AckDelivery :exec
UPDATE webhook_deliveries
SET finished_at = now(), leased_until = NULL, body = NULL, status_code = $2, response = $3
WHERE id = $1
`

type AckDeliveryParams struct {
	ID         string
	StatusCode *int32
	Response   string
}

func (q *Queries) AckDelivery(ctx context.Context, arg AckDeliveryParams) error {
	_, err := q.db.Exec(ctx, ackDelivery, arg.ID, arg.StatusCode, arg.Response)
	return err
}

const deadDelivery = `-- name: DeadDelivery :exec
UPDATE webhook_deliveries
SET finished_at = now(), leased_until = NULL, status_code = $2, response = $3, error = $4
WHERE id = $1
`

type DeadDeliveryParams struct {
	ID         string
	StatusCode *int32
	Response   string
	Error      string
}

func (q *Queries) DeadDelivery(ctx context.Context, arg DeadDeliveryParams) error {
	_, err := q.db.Exec(ctx, deadDelivery,
		arg.ID,
		arg.StatusCode,
		arg.Response,
		arg.Error,
	)
	return err
}

const enqueueDelivery = `-- name: EnqueueDelivery :exec

INSERT INTO webhook_deliveries (id, lane, event_type, sequence, body, not_before)
VALUES ($1, $2, $3, $4, $5, $6)
`

type EnqueueDeliveryParams struct {
	ID        string
	Lane      string
	EventType string
	Sequence  int64
	Body      []byte
	NotBefore time.Time
}

// Webhook deliveries: the Postgres implementation of the Queue port.
// Owned by the integrations module; only internal/integrations may use
// these queries. See docs/proposals/webhooks.md → The queue contract.
func (q *Queries) EnqueueDelivery(ctx context.Context, arg EnqueueDeliveryParams) error {
	_, err := q.db.Exec(ctx, enqueueDelivery,
		arg.ID,
		arg.Lane,
		arg.EventType,
		arg.Sequence,
		arg.Body,
		arg.NotBefore,
	)
	return err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, lane, event_type, sequence, body, attempts, not_before, leased_until, finished_at, status_code, response, error, created_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id string) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.EventType,
		&i.Sequence,
		&i.Body,
		&i.Attempts,
		&i.NotBefore,
		&i.LeasedUntil,
		&i.FinishedAt,
		&i.StatusCode,
		&i.Response,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const leaseDeliveries = `-- name: LeaseDeliveries :many
UPDATE webhook_deliveries d
SET leased_until = $1::timestamptz, attempts = d.attempts + 1
WHERE d.id IN (
    SELECT c.id FROM webhook_deliveries c
    WHERE c.finished_at IS NULL
      AND c.not_before <= now()
      AND (c.leased_until IS NULL OR c.leased_until < now())
      AND NOT EXISTS (
          SELECT 1 FROM webhook_deliveries o
          WHERE o.lane = c.lane AND o.finished_at IS NULL
            AND o.leased_until IS NOT NULL AND o.leased_until >= now()
      )
    ORDER BY c.not_before, c.sequence
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING d.id, d.lane, d.event_type, d.sequence, d.body, d.attempts, d.not_before, d.leased_until, d.finished_at, d.status_code, d.response, d.error, d.created_at
`

type LeaseDeliveriesParams struct {
	Until time.Time
	Limit int32
}

// LeaseDeliveries claims due, unfinished, unleased items whose lane has
// nothing in flight, oldest first.
func (q *Queries) LeaseDeliveries(ctx context.Context, arg LeaseDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, leaseDeliveries, arg.Until, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.Lane,
			&i.EventType,
			&i.Sequence,
			&i.Body,
			&i.Attempts,
			&i.NotBefore,
			&i.LeasedUntil,
			&i.FinishedAt,
			&i.StatusCode,
			&i.Response,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByLane = `-- name: ListDeliveriesByLane :many
SELECT id, lane, event_type, sequence, body, attempts, not_before, leased_until, finished_at, status_code, response, error, created_at FROM webhook_deliveries WHERE lane = $1 ORDER BY created_at DESC LIMIT $2
`

type ListDeliveriesByLaneParams struct {
	Lane  string
	Limit int32
}

func (q *Queries) ListDeliveriesByLane(ctx context.Context, arg ListDeliveriesByLaneParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByLane, arg.Lane, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.Lane,
			&i.EventType,
			&i.Sequence,
			&i.Body,
			&i.Attempts,
			&i.NotBefore,
			&i.LeasedUntil,
			&i.FinishedAt,
			&i.StatusCode,
			&i.Response,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nackDelivery = `-- name: NackDelivery :exec
UPDATE webhook_deliveries
SET leased_until = NULL, not_before = $2, status_code = $3, response = $4, error = $5
WHERE id = $1
`

type NackDeliveryParams struct {
	ID         string
	NotBefore  time.Time
	StatusCode *int32
	Response   string
	Error      string
}

func (q *Queries) NackDelivery(ctx context.Context, arg NackDeliveryParams) error {
	_, err := q.db.Exec(ctx, nackDelivery,
		arg.ID,
		arg.NotBefore,
		arg.StatusCode,
		arg.Response,
		arg.Error,
	)
	return err
}

const sweepFinishedDeliveries = `-- name: SweepFinishedDeliveries :execrows
DELETE FROM webhook_deliveries WHERE finished_at IS NOT NULL AND finished_at < $1
`

func (q *Queries) SweepFinishedDeliveries(ctx context.Context, finishedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepFinishedDeliveries, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
