// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package dbgen

import (
	"context"
	"time"
)

const deleteDelivery = `-- name: DeleteDelivery :exec
DELETE FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) DeleteDelivery(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDelivery, id)
	return err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, webhook_id, event_type, sequence, body, attempts, finished_at, status_code, response, error, created_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id string) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Sequence,
		&i.Body,
		&i.Attempts,
		&i.FinishedAt,
		&i.StatusCode,
		&i.Response,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :exec

INSERT INTO webhook_deliveries (id, webhook_id, event_type, sequence, body, created_at)
VALUES ($1, $2, $3, $4, $5, $6::timestamptz)
`

type InsertDeliveryParams struct {
	ID        string
	WebhookID string
	EventType string
	Sequence  int64
	Body      []byte
	Now       time.Time
}

// The delivery log: one row per outgoing delivery, inserted before its job
// is queued and updated by the deliver_webhook job after each attempt.
// Owned by the integrations module; only internal/integrations may use
// these queries. See docs/architecture/integrations.md → Outgoing.
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery,
		arg.ID,
		arg.WebhookID,
		arg.EventType,
		arg.Sequence,
		arg.Body,
		arg.Now,
	)
	return err
}

const listDeliveriesByWebhook = `-- name: ListDeliveriesByWebhook :many
SELECT id, webhook_id, event_type, sequence, body, attempts, finished_at, status_code, response, error, created_at FROM webhook_deliveries WHERE webhook_id = $1 ORDER BY created_at DESC, sequence DESC LIMIT $2
`

type ListDeliveriesByWebhookParams struct {
	WebhookID string
	Limit     int32
}

func (q *Queries) ListDeliveriesByWebhook(ctx context.Context, arg ListDeliveriesByWebhookParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByWebhook, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Sequence,
			&i.Body,
			&i.Attempts,
			&i.FinishedAt,
			&i.StatusCode,
			&i.Response,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDeliveryAttempt = `-- name: RecordDeliveryAttempt :exec
UPDATE webhook_deliveries
SET attempts = $1, status_code = $2,
    response = $3, error = $4,
    finished_at = $5::timestamptz,
    body = CASE WHEN $6::boolean THEN NULL ELSE body END
WHERE id = $7
`

type RecordDeliveryAttemptParams struct {
	Attempts   int32
	StatusCode *int32
	Response   string
	Error      string
	FinishedAt *time.Time
	Delivered  bool
	ID         string
}

// RecordDeliveryAttempt writes what one try learned; finished_at is set
// once the delivery is delivered or dead, and a delivered body is not kept.
func (q *Queries) RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, recordDeliveryAttempt,
		arg.Attempts,
		arg.StatusCode,
		arg.Response,
		arg.Error,
		arg.FinishedAt,
		arg.Delivered,
		arg.ID,
	)
	return err
}

const sweepFinishedDeliveries = `-- name: SweepFinishedDeliveries :execrows
DELETE FROM webhook_deliveries WHERE finished_at IS NOT NULL AND finished_at < $1::timestamptz
`

func (q *Queries) SweepFinishedDeliveries(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepFinishedDeliveries, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
