// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagnostics.sql

package dbgen

import (
	"context"
	"time"
)

const queueStats = `-- name: QueueStats :one

SELECT
    count(*) FILTER (WHERE finished_at IS NULL
        AND (leased_until IS NULL OR leased_until < $1::timestamptz))::bigint AS queued,
    count(*) FILTER (WHERE finished_at IS NULL
        AND leased_until >= $1::timestamptz)::bigint AS leased,
    count(*) FILTER (WHERE finished_at IS NOT NULL
        AND (status_code IS NULL OR status_code NOT BETWEEN 200 AND 299))::bigint AS dead,
    count(*) FILTER (WHERE finished_at IS NOT NULL
        AND (status_code IS NULL OR status_code NOT BETWEEN 200 AND 299)
        AND finished_at >= $2::timestamptz)::bigint AS dead_last_hour,
    (SELECT count(*) FROM outgoing_webhooks)::bigint AS hooks
FROM webhook_deliveries
`

type QueueStatsParams struct {
	Now   time.Time
	Since time.Time
}

type QueueStatsRow struct {
	Queued       int64
	Leased       int64
	Dead         int64
	DeadLastHour int64
	Hooks        int64
}

// The Background work panel's view of the queue, in one pass over
// webhook_deliveries. A finished delivery is dead unless its status was
// 2xx, the reading settleDead makes. The hook count is for the OFF state.
// See docs/proposals/diagnostics.md.
func (q *Queries) QueueStats(ctx context.Context, arg QueueStatsParams) (QueueStatsRow, error) {
	row := q.db.QueryRow(ctx, queueStats, arg.Now, arg.Since)
	var i QueueStatsRow
	err := row.Scan(
		&i.Queued,
		&i.Leased,
		&i.Dead,
		&i.DeadLastHour,
		&i.Hooks,
	)
	return i, err
}
