// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagnostics.sql

package dbgen

import (
	"context"
)

const getDatabaseFacts = `-- name: GetDatabaseFacts :one

SELECT
  pg_database_size(current_database())::bigint AS database_bytes,
  (SELECT count(*) FROM pg_catalog.pg_stat_activity
    WHERE datname = current_database() AND state = 'active')::int AS backends_active,
  (SELECT count(*) FROM pg_catalog.pg_stat_activity
    WHERE datname = current_database() AND state LIKE 'idle%')::int AS backends_idle,
  coalesce((SELECT (extract(epoch FROM max(now() - xact_start)) * 1000)::bigint
    FROM pg_catalog.pg_stat_activity
    WHERE datname = current_database() AND state = 'active'), 0)::bigint AS oldest_transaction_ms,
  current_setting('server_version')::text AS server_version,
  (SELECT coalesce(max(version_id), 0) FROM goose_db_version)::bigint AS schema_version,
  (SELECT coalesce(min(min_migration), 0) FROM schema_floor)::bigint AS schema_floor
`

type GetDatabaseFactsRow struct {
	DatabaseBytes       int64
	BackendsActive      int32
	BackendsIdle        int32
	OldestTransactionMs int64
	ServerVersion       string
	SchemaVersion       int64
	SchemaFloor         int64
}

// The Diagnostics tab's Database panel: one round trip, this database
// only. Owned by the instance module.
func (q *Queries) GetDatabaseFacts(ctx context.Context) (GetDatabaseFactsRow, error) {
	row := q.db.QueryRow(ctx, getDatabaseFacts)
	var i GetDatabaseFactsRow
	err := row.Scan(
		&i.DatabaseBytes,
		&i.BackendsActive,
		&i.BackendsIdle,
		&i.OldestTransactionMs,
		&i.ServerVersion,
		&i.SchemaVersion,
		&i.SchemaFloor,
	)
	return i, err
}
