// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_token_use.sql

package dbgen

import (
	"context"
	"time"
)

const deleteAllUserEmailTokens = `-- name: DeleteAllUserEmailTokens :exec
DELETE FROM email_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAllUserEmailTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllUserEmailTokens, userID)
	return err
}

const deleteOtherEmailTokens = `-- name: DeleteOtherEmailTokens :exec
DELETE FROM email_tokens
WHERE user_id = $1::uuid AND purpose = $2::text AND id <> $3::uuid
`

type DeleteOtherEmailTokensParams struct {
	UserID  string
	Purpose string
	KeepID  string
}

func (q *Queries) DeleteOtherEmailTokens(ctx context.Context, arg DeleteOtherEmailTokensParams) error {
	_, err := q.db.Exec(ctx, deleteOtherEmailTokens, arg.UserID, arg.Purpose, arg.KeepID)
	return err
}

const deleteUserEmailTokens = `-- name: DeleteUserEmailTokens :exec
DELETE FROM email_tokens WHERE user_id = $1::uuid AND purpose = $2::text
`

type DeleteUserEmailTokensParams struct {
	UserID  string
	Purpose string
}

func (q *Queries) DeleteUserEmailTokens(ctx context.Context, arg DeleteUserEmailTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserEmailTokens, arg.UserID, arg.Purpose)
	return err
}

const getConfirmableEmailToken = `-- name: GetConfirmableEmailToken :one

SELECT t.id, t.user_id, t.address, u.email AS previous_email
FROM email_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1::bytea
  AND t.purpose = $2::text
  AND t.used_at IS NULL
  AND t.expires_at > now()
  AND u.deactivated_at IS NULL
  AND u.pending_email = t.address
FOR UPDATE OF t, u
`

type GetConfirmableEmailTokenParams struct {
	TokenHash []byte
	Purpose   string
}

type GetConfirmableEmailTokenRow struct {
	ID            string
	UserID        string
	Address       string
	PreviousEmail *string
}

// Using and clearing email link tokens. Owned by the auth module.
// Only internal/auth may use these queries.
// GetConfirmableEmailToken is a live token whose address is still the
// account's pending one, on an active account. Both rows are locked.
func (q *Queries) GetConfirmableEmailToken(ctx context.Context, arg GetConfirmableEmailTokenParams) (GetConfirmableEmailTokenRow, error) {
	row := q.db.QueryRow(ctx, getConfirmableEmailToken, arg.TokenHash, arg.Purpose)
	var i GetConfirmableEmailTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.PreviousEmail,
	)
	return i, err
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :exec
UPDATE email_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markEmailTokenUsed, id)
	return err
}

const sweepEmailTokens = `-- name: SweepEmailTokens :execrows
DELETE FROM email_tokens
WHERE expires_at <= $1::timestamptz OR used_at <= $1::timestamptz
`

// SweepEmailTokens deletes tokens that expired or were used before the
// cutoff.
func (q *Queries) SweepEmailTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepEmailTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
