// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_tokens_mint.sql

package dbgen

import (
	"context"
	"time"
)

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_tokens (id, user_id, purpose, token_hash, address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEmailTokenParams struct {
	ID        string
	UserID    string
	Purpose   string
	TokenHash []byte
	Address   string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.Address,
		arg.ExpiresAt,
	)
	return err
}

const getEmailRecipient = `-- name: GetEmailRecipient :one

SELECT username, email, pending_email, kind, (deactivated_at IS NOT NULL)::bool AS deactivated
FROM users
WHERE id = $1
`

type GetEmailRecipientRow struct {
	Username     string
	Email        *string
	PendingEmail *string
	Kind         string
	Deactivated  bool
}

// Email link tokens, minting side. Owned by the auth module.
// Only internal/auth may use these queries.
// GetEmailRecipient is what a send_email builder needs about the user.
func (q *Queries) GetEmailRecipient(ctx context.Context, id string) (GetEmailRecipientRow, error) {
	row := q.db.QueryRow(ctx, getEmailRecipient, id)
	var i GetEmailRecipientRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.PendingEmail,
		&i.Kind,
		&i.Deactivated,
	)
	return i, err
}
