// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package dbgen

import (
	"context"
	"time"
)

const countExpiringAttachments = `-- name: CountExpiringAttachments :one
SELECT count(*)::bigint AS files, COALESCE(SUM(size), 0)::bigint AS bytes FROM files
WHERE kind = 'attachment' AND expired_at IS NULL
  AND created_at < $1
  AND NOT (id = ANY($2::uuid[]))
`

type CountExpiringAttachmentsParams struct {
	Before time.Time
	Keep   []string
}

type CountExpiringAttachmentsRow struct {
	Files int64
	Bytes int64
}

func (q *Queries) CountExpiringAttachments(ctx context.Context, arg CountExpiringAttachmentsParams) (CountExpiringAttachmentsRow, error) {
	row := q.db.QueryRow(ctx, countExpiringAttachments, arg.Before, arg.Keep)
	var i CountExpiringAttachmentsRow
	err := row.Scan(&i.Files, &i.Bytes)
	return i, err
}

const createFile = `-- name: CreateFile :one

INSERT INTO files (id, kind, owner_id, space_id, content_type, size, sha256, storage_key, name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name, expired_at
`

type CreateFileParams struct {
	ID          string
	Kind        string
	OwnerID     string
	SpaceID     *string
	ContentType string
	Size        int64
	Sha256      []byte
	StorageKey  string
	Name        string
}

// Stored file metadata. Owned by the files module.
// Only internal/files may use these queries.
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.Kind,
		arg.OwnerID,
		arg.SpaceID,
		arg.ContentType,
		arg.Size,
		arg.Sha256,
		arg.StorageKey,
		arg.Name,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.SpaceID,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.StorageKey,
		&i.CreatedAt,
		&i.Name,
		&i.ExpiredAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :one
DELETE FROM files WHERE id = $1 RETURNING id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name, expired_at
`

func (q *Queries) DeleteFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRow(ctx, deleteFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.SpaceID,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.StorageKey,
		&i.CreatedAt,
		&i.Name,
		&i.ExpiredAt,
	)
	return i, err
}

const deleteFilesByIDs = `-- name: DeleteFilesByIDs :many
DELETE FROM files WHERE id = ANY($1::uuid[]) RETURNING id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name, expired_at
`

func (q *Queries) DeleteFilesByIDs(ctx context.Context, dollar_1 []string) ([]File, error) {
	rows, err := q.db.Query(ctx, deleteFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OwnerID,
			&i.SpaceID,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.StorageKey,
			&i.CreatedAt,
			&i.Name,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireFiles = `-- name: ExpireFiles :exec
UPDATE files SET expired_at = now(), name = '' WHERE id = ANY($1::uuid[])
`

// ExpireFiles marks files expired and drops their names; the blobs are
// already gone.
func (q *Queries) ExpireFiles(ctx context.Context, ids []string) error {
	_, err := q.db.Exec(ctx, expireFiles, ids)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name, expired_at FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.SpaceID,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.StorageKey,
		&i.CreatedAt,
		&i.Name,
		&i.ExpiredAt,
	)
	return i, err
}

const getFilesByIDs = `-- name: GetFilesByIDs :many
SELECT id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name, expired_at FROM files WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetFilesByIDs(ctx context.Context, dollar_1 []string) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OwnerID,
			&i.SpaceID,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.StorageKey,
			&i.CreatedAt,
			&i.Name,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringAttachments = `-- name: ListExpiringAttachments :many
SELECT id, storage_key FROM files
WHERE kind = 'attachment' AND expired_at IS NULL
  AND created_at < $1
  AND NOT (id = ANY($2::uuid[]))
ORDER BY created_at
LIMIT $3
`

type ListExpiringAttachmentsParams struct {
	Before time.Time
	Keep   []string
	Limit  int32
}

type ListExpiringAttachmentsRow struct {
	ID         string
	StorageKey string
}

// Attachment retention: attachments uploaded before the cutoff that
// haven't expired, less the ones kept (pinned messages' files), oldest
// first.
func (q *Queries) ListExpiringAttachments(ctx context.Context, arg ListExpiringAttachmentsParams) ([]ListExpiringAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringAttachments, arg.Before, arg.Keep, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringAttachmentsRow
	for rows.Next() {
		var i ListExpiringAttachmentsRow
		if err := rows.Scan(&i.ID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesOlderThan = `-- name: ListFilesOlderThan :many
SELECT id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name, expired_at FROM files
WHERE created_at < $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListFilesOlderThanParams struct {
	Before  time.Time
	AfterID string
	Limit   int32
}

// The sweep pages through files older than a grace period by id.
func (q *Queries) ListFilesOlderThan(ctx context.Context, arg ListFilesOlderThanParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesOlderThan, arg.Before, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OwnerID,
			&i.SpaceID,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.StorageKey,
			&i.CreatedAt,
			&i.Name,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageKeysAmong = `-- name: ListStorageKeysAmong :many
SELECT storage_key FROM files WHERE storage_key = ANY($1::text[])
`

func (q *Queries) ListStorageKeysAmong(ctx context.Context, keys []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listStorageKeysAmong, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStorageQuota = `-- name: LockStorageQuota :exec
SELECT pg_advisory_xact_lock(4207011)
`

// LockStorageQuota serialises quota-checked inserts for the transaction
// (see files.recordFile). The key is arbitrary and only used here.
func (q *Queries) LockStorageQuota(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockStorageQuota)
	return err
}

const storageUsage = `-- name: StorageUsage :one
SELECT COALESCE(SUM(size), 0)::bigint AS bytes, count(*)::bigint AS files FROM files
WHERE expired_at IS NULL
`

type StorageUsageRow struct {
	Bytes int64
	Files int64
}

func (q *Queries) StorageUsage(ctx context.Context) (StorageUsageRow, error) {
	row := q.db.QueryRow(ctx, storageUsage)
	var i StorageUsageRow
	err := row.Scan(&i.Bytes, &i.Files)
	return i, err
}
