// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package dbgen

import (
	"context"
	"time"
)

const createFile = `-- name: CreateFile :one

INSERT INTO files (id, kind, owner_id, space_id, content_type, size, sha256, storage_key, name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name
`

type CreateFileParams struct {
	ID          string
	Kind        string
	OwnerID     string
	SpaceID     *string
	ContentType string
	Size        int64
	Sha256      []byte
	StorageKey  string
	Name        string
}

// Stored file metadata. Owned by the files module.
// Only internal/files may use these queries.
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.Kind,
		arg.OwnerID,
		arg.SpaceID,
		arg.ContentType,
		arg.Size,
		arg.Sha256,
		arg.StorageKey,
		arg.Name,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.SpaceID,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.StorageKey,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :one
DELETE FROM files WHERE id = $1 RETURNING id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name
`

func (q *Queries) DeleteFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRow(ctx, deleteFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.SpaceID,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.StorageKey,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const deleteFilesByIDs = `-- name: DeleteFilesByIDs :many
DELETE FROM files WHERE id = ANY($1::uuid[]) RETURNING id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name
`

func (q *Queries) DeleteFilesByIDs(ctx context.Context, dollar_1 []string) ([]File, error) {
	rows, err := q.db.Query(ctx, deleteFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OwnerID,
			&i.SpaceID,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.StorageKey,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFile = `-- name: GetFile :one
SELECT id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.SpaceID,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.StorageKey,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getFilesByIDs = `-- name: GetFilesByIDs :many
SELECT id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name FROM files WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetFilesByIDs(ctx context.Context, dollar_1 []string) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OwnerID,
			&i.SpaceID,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.StorageKey,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesOlderThan = `-- name: ListFilesOlderThan :many
SELECT id, kind, owner_id, space_id, content_type, size, sha256, storage_key, created_at, name FROM files
WHERE created_at < $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListFilesOlderThanParams struct {
	Before  time.Time
	AfterID string
	Limit   int32
}

// The sweep pages through files older than a grace period by id.
func (q *Queries) ListFilesOlderThan(ctx context.Context, arg ListFilesOlderThanParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesOlderThan, arg.Before, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OwnerID,
			&i.SpaceID,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.StorageKey,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageKeysAmong = `-- name: ListStorageKeysAmong :many
SELECT storage_key FROM files WHERE storage_key = ANY($1::text[])
`

func (q *Queries) ListStorageKeysAmong(ctx context.Context, keys []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listStorageKeysAmong, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStorageQuota = `-- name: LockStorageQuota :exec
SELECT pg_advisory_xact_lock(4207011)
`

// LockStorageQuota serialises quota-checked inserts for the transaction
// (see files.recordFile). The key is arbitrary and only used here.
func (q *Queries) LockStorageQuota(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockStorageQuota)
	return err
}

const storageUsage = `-- name: StorageUsage :one
SELECT COALESCE(SUM(size), 0)::bigint AS bytes, count(*)::bigint AS files FROM files
`

type StorageUsageRow struct {
	Bytes int64
	Files int64
}

func (q *Queries) StorageUsage(ctx context.Context) (StorageUsageRow, error) {
	row := q.db.QueryRow(ctx, storageUsage)
	var i StorageUsageRow
	err := row.Scan(&i.Bytes, &i.Files)
	return i, err
}
