// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package dbgen

import (
	"context"
)

const countUserIdentities = `-- name: CountUserIdentities :one
SELECT count(*) FROM user_identities WHERE user_id = $1
`

func (q *Queries) CountUserIdentities(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserIdentities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO user_identities (provider, subject, user_id, email)
VALUES ($1, $2, $3, $4)
RETURNING provider, subject, user_id, email, created_at
`

type CreateIdentityParams struct {
	Provider string
	Subject  string
	UserID   string
	Email    string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.Provider,
		arg.Subject,
		arg.UserID,
		arg.Email,
	)
	var i UserIdentity
	err := row.Scan(
		&i.Provider,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserIdentity = `-- name: DeleteUserIdentity :execrows
DELETE FROM user_identities WHERE user_id = $1 AND provider = $2
`

type DeleteUserIdentityParams struct {
	UserID   string
	Provider string
}

func (q *Queries) DeleteUserIdentity(ctx context.Context, arg DeleteUserIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserIdentity, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByIdentity = `-- name: GetUserByIdentity :one

SELECT u.id, u.username, u.display_name, u.password_hash, u.created_at, u.role, u.deactivated_at, u.avatar_file_id, u.username_pending, u.username_frozen, u.pronouns, u.bio FROM users u
JOIN user_identities i ON i.user_id = u.id
WHERE i.provider = $1 AND i.subject = $2
`

type GetUserByIdentityParams struct {
	Provider string
	Subject  string
}

// Linked sign-in identities (login providers). Owned by the auth module.
// Only internal/auth may use these queries.
func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
	)
	return i, err
}

const listUserIdentities = `-- name: ListUserIdentities :many
SELECT provider, subject, user_id, email, created_at FROM user_identities WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListUserIdentities(ctx context.Context, userID string) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listUserIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.Provider,
			&i.Subject,
			&i.UserID,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
