// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incoming_webhooks.sql

package dbgen

import (
	"context"
)

const countIncomingWebhooksBySpace = `-- name: CountIncomingWebhooksBySpace :one
SELECT count(*) FROM incoming_webhooks WHERE space_id = $1
`

func (q *Queries) CountIncomingWebhooksBySpace(ctx context.Context, spaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countIncomingWebhooksBySpace, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncomingWebhook = `-- name: CreateIncomingWebhook :one

INSERT INTO incoming_webhooks (id, space_id, channel_id, bot_user_id, credential_id, name, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, space_id, channel_id, bot_user_id, credential_id, name, created_by, created_at, disabled_at, disabled_reason
`

type CreateIncomingWebhookParams struct {
	ID           string
	SpaceID      string
	ChannelID    string
	BotUserID    string
	CredentialID *string
	Name         string
	CreatedBy    string
}

// Incoming webhooks. Owned by the integrations module.
// Only internal/integrations may use these queries.
func (q *Queries) CreateIncomingWebhook(ctx context.Context, arg CreateIncomingWebhookParams) (IncomingWebhook, error) {
	row := q.db.QueryRow(ctx, createIncomingWebhook,
		arg.ID,
		arg.SpaceID,
		arg.ChannelID,
		arg.BotUserID,
		arg.CredentialID,
		arg.Name,
		arg.CreatedBy,
	)
	var i IncomingWebhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.BotUserID,
		&i.CredentialID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const deleteIncomingWebhook = `-- name: DeleteIncomingWebhook :one
DELETE FROM incoming_webhooks WHERE id = $1 RETURNING id, space_id, channel_id, bot_user_id, credential_id, name, created_by, created_at, disabled_at, disabled_reason
`

func (q *Queries) DeleteIncomingWebhook(ctx context.Context, id string) (IncomingWebhook, error) {
	row := q.db.QueryRow(ctx, deleteIncomingWebhook, id)
	var i IncomingWebhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.BotUserID,
		&i.CredentialID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const disableIncomingWebhook = `-- name: DisableIncomingWebhook :exec
UPDATE incoming_webhooks SET disabled_at = now(), disabled_reason = $2 WHERE id = $1
`

type DisableIncomingWebhookParams struct {
	ID             string
	DisabledReason string
}

func (q *Queries) DisableIncomingWebhook(ctx context.Context, arg DisableIncomingWebhookParams) error {
	_, err := q.db.Exec(ctx, disableIncomingWebhook, arg.ID, arg.DisabledReason)
	return err
}

const getIncomingWebhook = `-- name: GetIncomingWebhook :one
SELECT id, space_id, channel_id, bot_user_id, credential_id, name, created_by, created_at, disabled_at, disabled_reason FROM incoming_webhooks WHERE id = $1
`

func (q *Queries) GetIncomingWebhook(ctx context.Context, id string) (IncomingWebhook, error) {
	row := q.db.QueryRow(ctx, getIncomingWebhook, id)
	var i IncomingWebhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.BotUserID,
		&i.CredentialID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const getIncomingWebhookByCredential = `-- name: GetIncomingWebhookByCredential :one
SELECT id, space_id, channel_id, bot_user_id, credential_id, name, created_by, created_at, disabled_at, disabled_reason FROM incoming_webhooks WHERE credential_id = $1
`

func (q *Queries) GetIncomingWebhookByCredential(ctx context.Context, credentialID *string) (IncomingWebhook, error) {
	row := q.db.QueryRow(ctx, getIncomingWebhookByCredential, credentialID)
	var i IncomingWebhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.BotUserID,
		&i.CredentialID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const listIncomingWebhooks = `-- name: ListIncomingWebhooks :many
SELECT id, space_id, channel_id, bot_user_id, credential_id, name, created_by, created_at, disabled_at, disabled_reason FROM incoming_webhooks ORDER BY space_id, created_at, id
`

func (q *Queries) ListIncomingWebhooks(ctx context.Context) ([]IncomingWebhook, error) {
	rows, err := q.db.Query(ctx, listIncomingWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomingWebhook
	for rows.Next() {
		var i IncomingWebhook
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.BotUserID,
			&i.CredentialID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingWebhooksBySpace = `-- name: ListIncomingWebhooksBySpace :many
SELECT id, space_id, channel_id, bot_user_id, credential_id, name, created_by, created_at, disabled_at, disabled_reason FROM incoming_webhooks WHERE space_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListIncomingWebhooksBySpace(ctx context.Context, spaceID string) ([]IncomingWebhook, error) {
	rows, err := q.db.Query(ctx, listIncomingWebhooksBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomingWebhook
	for rows.Next() {
		var i IncomingWebhook
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.BotUserID,
			&i.CredentialID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameIncomingWebhook = `-- name: RenameIncomingWebhook :exec
UPDATE incoming_webhooks SET name = $2 WHERE id = $1
`

type RenameIncomingWebhookParams struct {
	ID   string
	Name string
}

func (q *Queries) RenameIncomingWebhook(ctx context.Context, arg RenameIncomingWebhookParams) error {
	_, err := q.db.Exec(ctx, renameIncomingWebhook, arg.ID, arg.Name)
	return err
}

const setIncomingWebhookCredential = `-- name: SetIncomingWebhookCredential :exec
UPDATE incoming_webhooks SET credential_id = $2, disabled_at = NULL, disabled_reason = '' WHERE id = $1
`

type SetIncomingWebhookCredentialParams struct {
	ID           string
	CredentialID *string
}

// SetIncomingWebhookCredential rotates the token; the old credential is
// revoked by auth.
func (q *Queries) SetIncomingWebhookCredential(ctx context.Context, arg SetIncomingWebhookCredentialParams) error {
	_, err := q.db.Exec(ctx, setIncomingWebhookCredential, arg.ID, arg.CredentialID)
	return err
}
