// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package dbgen

import (
	"context"
	"time"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites
SET use_count = use_count + 1
WHERE code = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses IS NULL OR use_count < max_uses)
RETURNING id, space_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at, role
`

func (q *Queries) ConsumeInvite(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, consumeInvite, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO invites (id, space_id, code, created_by, expires_at, max_uses, role)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, space_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at, role
`

type CreateInviteParams struct {
	ID        string
	SpaceID   string
	Code      string
	CreatedBy string
	ExpiresAt *time.Time
	MaxUses   *int32
	Role      string
}

// Invites: redeemable codes granting space membership. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.SpaceID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.Role,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, space_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at, role FROM invites WHERE id = $1
`

func (q *Queries) GetInvite(ctx context.Context, id string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, space_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at, role FROM invites WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const listInvitesBySpace = `-- name: ListInvitesBySpace :many
SELECT id, space_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at, role FROM invites WHERE space_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListInvitesBySpace(ctx context.Context, spaceID string) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvitesBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Code,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupInviteByCode = `-- name: LookupInviteByCode :one
SELECT i.id, i.space_id, i.code, i.created_by, i.expires_at, i.max_uses, i.use_count, i.revoked_at, i.created_at, i.role,
    s.name AS space_name,
    s.description AS space_description,
    s.icon_file_id AS space_icon_file_id,
    (SELECT count(*) FROM space_members m WHERE m.space_id = s.id) AS member_count
FROM invites i
JOIN spaces s ON s.id = i.space_id
WHERE i.code = $1
`

type LookupInviteByCodeRow struct {
	Invite           Invite
	SpaceName        string
	SpaceDescription string
	SpaceIconFileID  *string
	MemberCount      int64
}

// LookupInviteByCode backs the public invite preview: the code with its
// space's public face and size, so a stranger can see what they are being
// asked to join. The space's welcome text is deliberately not selected.
func (q *Queries) LookupInviteByCode(ctx context.Context, code string) (LookupInviteByCodeRow, error) {
	row := q.db.QueryRow(ctx, lookupInviteByCode, code)
	var i LookupInviteByCodeRow
	err := row.Scan(
		&i.Invite.ID,
		&i.Invite.SpaceID,
		&i.Invite.Code,
		&i.Invite.CreatedBy,
		&i.Invite.ExpiresAt,
		&i.Invite.MaxUses,
		&i.Invite.UseCount,
		&i.Invite.RevokedAt,
		&i.Invite.CreatedAt,
		&i.Invite.Role,
		&i.SpaceName,
		&i.SpaceDescription,
		&i.SpaceIconFileID,
		&i.MemberCount,
	)
	return i, err
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE invites
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
RETURNING id, space_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at, role
`

func (q *Queries) RevokeInvite(ctx context.Context, id string) (Invite, error) {
	row := q.db.QueryRow(ctx, revokeInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}
