// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_schedules.sql

package dbgen

import (
	"context"
	"time"
)

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE job_schedules SET next_due = $1::timestamptz, last_job_id = $2
WHERE kind = $3
`

type AdvanceScheduleParams struct {
	NextDue   time.Time
	LastJobID *string
	Kind      string
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.Exec(ctx, advanceSchedule, arg.NextDue, arg.LastJobID, arg.Kind)
	return err
}

const disableSchedule = `-- name: DisableSchedule :exec
UPDATE job_schedules SET enabled = false WHERE kind = $1
`

// DisableSchedule turns a row off whose kind no dispatcher performs any
// more, so it stops reading as due.
func (q *Queries) DisableSchedule(ctx context.Context, kind string) error {
	_, err := q.db.Exec(ctx, disableSchedule, kind)
	return err
}

const dueSchedules = `-- name: DueSchedules :many
SELECT kind, interval_ms, enabled, next_due, last_job_id FROM job_schedules
WHERE enabled AND next_due <= $1::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM jobs WHERE jobs.kind = job_schedules.kind AND jobs.state IN ('queued', 'running')
  )
ORDER BY kind
FOR UPDATE SKIP LOCKED
`

// DueSchedules locks the due rows for the caller's transaction; SKIP
// LOCKED keeps two dispatchers from inserting the same run. A kind with a
// run still queued or running waits for the next tick.
func (q *Queries) DueSchedules(ctx context.Context, now time.Time) ([]JobSchedule, error) {
	rows, err := q.db.Query(ctx, dueSchedules, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobSchedule
	for rows.Next() {
		var i JobSchedule
		if err := rows.Scan(
			&i.Kind,
			&i.IntervalMs,
			&i.Enabled,
			&i.NextDue,
			&i.LastJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT kind, interval_ms, enabled, next_due, last_job_id FROM job_schedules ORDER BY kind
`

func (q *Queries) ListSchedules(ctx context.Context) ([]JobSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobSchedule
	for rows.Next() {
		var i JobSchedule
		if err := rows.Scan(
			&i.Kind,
			&i.IntervalMs,
			&i.Enabled,
			&i.NextDue,
			&i.LastJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSchedule = `-- name: UpsertSchedule :exec

INSERT INTO job_schedules (kind, interval_ms, enabled, next_due)
VALUES ($1, $2, $3, $4::timestamptz)
ON CONFLICT (kind) DO UPDATE
SET interval_ms = EXCLUDED.interval_ms,
    enabled = EXCLUDED.enabled,
    next_due = CASE WHEN EXCLUDED.enabled
                    THEN LEAST(job_schedules.next_due, $5::timestamptz)
                    ELSE job_schedules.next_due END
`

type UpsertScheduleParams struct {
	Kind       string
	IntervalMs int64
	Enabled    bool
	FirstDue   time.Time
	MovedDue   time.Time
}

// Periodic kinds. Owned by the jobs module.
// UpsertSchedule creates a row due at first_due, or updates one and pulls
// its next_due forward to moved_due when that comes first.
func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) error {
	_, err := q.db.Exec(ctx, upsertSchedule,
		arg.Kind,
		arg.IntervalMs,
		arg.Enabled,
		arg.FirstDue,
		arg.MovedDue,
	)
	return err
}
