// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_dispatchers.sql

package dbgen

import (
	"context"
	"time"
)

const deleteDispatcher = `-- name: DeleteDispatcher :exec
DELETE FROM job_dispatchers WHERE id = $1
`

func (q *Queries) DeleteDispatcher(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDispatcher, id)
	return err
}

const listDispatchers = `-- name: ListDispatchers :many
SELECT id, host, workers, started_at, seen_at FROM job_dispatchers ORDER BY seen_at DESC, id
`

func (q *Queries) ListDispatchers(ctx context.Context) ([]JobDispatcher, error) {
	rows, err := q.db.Query(ctx, listDispatchers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobDispatcher
	for rows.Next() {
		var i JobDispatcher
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Workers,
			&i.StartedAt,
			&i.SeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepDispatchers = `-- name: SweepDispatchers :execrows
DELETE FROM job_dispatchers WHERE seen_at < $1::timestamptz
`

func (q *Queries) SweepDispatchers(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepDispatchers, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDispatcher = `-- name: UpsertDispatcher :exec

INSERT INTO job_dispatchers (id, host, workers, started_at, seen_at)
VALUES ($1, $2, $3, $4::timestamptz, $5::timestamptz)
ON CONFLICT (id) DO UPDATE SET seen_at = EXCLUDED.seen_at
`

type UpsertDispatcherParams struct {
	ID        string
	Host      string
	Workers   int32
	StartedAt time.Time
	Now       time.Time
}

// Dispatcher heartbeats. Owned by the jobs module.
func (q *Queries) UpsertDispatcher(ctx context.Context, arg UpsertDispatcherParams) error {
	_, err := q.db.Exec(ctx, upsertDispatcher,
		arg.ID,
		arg.Host,
		arg.Workers,
		arg.StartedAt,
		arg.Now,
	)
	return err
}
