// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
	"time"
)

const countLiveLeases = `-- name: CountLiveLeases :one
SELECT count(*)::bigint FROM jobs
WHERE kind = $1 AND state = 'running' AND leased_until >= $2::timestamptz
`

type CountLiveLeasesParams struct {
	Kind string
	Now  time.Time
}

// CountLiveLeases is a kind's rows running on a live lease, the same
// count KindBacklog calls running.
func (q *Queries) CountLiveLeases(ctx context.Context, arg CountLiveLeasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveLeases, arg.Kind, arg.Now)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countQueuedJobs = `-- name: CountQueuedJobs :one
SELECT count(*) FROM jobs WHERE kind = $1 AND state = 'queued'
`

func (q *Queries) CountQueuedJobs(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRow(ctx, countQueuedJobs, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const discardLane = `-- name: DiscardLane :execrows
UPDATE jobs
SET state = 'discarded', finished_at = $1::timestamptz, leased_until = NULL, error = $2,
    args = '{}'::jsonb
WHERE lane = $3::text AND state = 'queued'
`

type DiscardLaneParams struct {
	Now   time.Time
	Error string
	Lane  string
}

// DiscardLane ends a lane's queued rows; a running one finishes on its
// own. Their arguments are not kept: the lane's owner is going away.
func (q *Queries) DiscardLane(ctx context.Context, arg DiscardLaneParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardLane, arg.Now, arg.Error, arg.Lane)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendJobLease = `-- name: ExtendJobLease :execrows
UPDATE jobs SET leased_until = GREATEST(leased_until, $1::timestamptz)
WHERE id = $2 AND attempt = $3 AND state = 'running'
`

type ExtendJobLeaseParams struct {
	Until   time.Time
	ID      string
	Attempt int32
}

// ExtendJobLease never moves a deadline earlier: a renewal keeps an
// Extend the performer asked for.
func (q *Queries) ExtendJobLease(ctx context.Context, arg ExtendJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendJobLease, arg.Until, arg.ID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishJob = `-- name: FinishJob :execrows
UPDATE jobs
SET state = $1, finished_at = $2::timestamptz, leased_until = NULL,
    error = $3, counters = $4,
    args = CASE WHEN $1::text = 'succeeded' THEN '{}'::jsonb ELSE args END
WHERE id = $5 AND attempt = $6
`

type FinishJobParams struct {
	State    string
	Now      time.Time
	Error    string
	Counters []byte
	ID       string
	Attempt  int32
}

// The outcome writes match the attempt they were leased for, so a stale
// attempt whose lease lapsed changes nothing. A succeeded job's arguments
// are not kept: nothing reads them, and they may carry content.
func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishJob,
		arg.State,
		arg.Now,
		arg.Error,
		arg.Counters,
		arg.ID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, kind, args, lane, sequence, state, attempt, max_attempts, not_before, leased_until, started_at, finished_at, error, counters, created_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Args,
		&i.Lane,
		&i.Sequence,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NotBefore,
		&i.LeasedUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.Counters,
		&i.CreatedAt,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT id, kind, args, lane, sequence, state, attempt, max_attempts, not_before, leased_until, started_at, finished_at, error, counters, created_at FROM jobs WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetJobs(ctx context.Context, ids []string) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Args,
			&i.Lane,
			&i.Sequence,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NotBefore,
			&i.LeasedUntil,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.Counters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertJob = `-- name: InsertJob :exec

WITH inserted AS (
    INSERT INTO jobs (id, kind, args, lane, sequence, state, attempt, max_attempts, not_before, created_at)
    VALUES ($1, $2, $3, $4, $5, 'queued', 0,
            $6, $7::timestamptz, $8::timestamptz)
    RETURNING id
)
SELECT pg_notify('stoop_jobs', '') FROM inserted
`

type InsertJobParams struct {
	ID          string
	Kind        string
	Args        []byte
	Lane        *string
	Sequence    *int64
	MaxAttempts int32
	NotBefore   time.Time
	Now         time.Time
}

// The job queue. Owned by the jobs module; only internal/jobs may use
// these queries. The clock is always the caller's, never now(), so one
// clock decides due-ness and leases. See docs/proposals/jobs.md.
// InsertJob raises jobs.NotifyChannel, so the dispatcher wakes without a trigger.
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob,
		arg.ID,
		arg.Kind,
		arg.Args,
		arg.Lane,
		arg.Sequence,
		arg.MaxAttempts,
		arg.NotBefore,
		arg.Now,
	)
	return err
}

const kindBacklog = `-- name: KindBacklog :one
SELECT
    count(*) FILTER (WHERE j.state = 'queued' OR j.leased_until < $1::timestamptz)::bigint AS queued,
    count(*) FILTER (WHERE j.state = 'running' AND j.leased_until >= $1::timestamptz)::bigint AS running,
    COALESCE(min(j.not_before) FILTER (WHERE (j.state = 'queued' OR j.leased_until < $1::timestamptz)
                                       AND j.not_before <= $1::timestamptz
                                       AND (j.lane IS NULL OR NOT EXISTS (
                                           SELECT 1 FROM jobs o
                                           WHERE o.lane = j.lane AND o.state IN ('queued', 'running')
                                             AND (o.sequence, o.id) < (j.sequence, j.id)
                                       ))),
             '0001-01-01 00:00:00+00'::timestamptz)::timestamptz AS oldest_due
FROM jobs j
WHERE j.kind = $2 AND j.state IN ('queued', 'running')
`

type KindBacklogParams struct {
	Now  time.Time
	Kind string
}

type KindBacklogRow struct {
	Queued    int64
	Running   int64
	OldestDue time.Time
}

// KindBacklog counts a kind's unfinished rows: waiting (queued, or running
// with a lapsed lease), running on a live lease, and the earliest due
// not_before among the waiting rows the dispatcher could lease (a row
// held behind its lane's head is not one), the zero time when none is.
func (q *Queries) KindBacklog(ctx context.Context, arg KindBacklogParams) (KindBacklogRow, error) {
	row := q.db.QueryRow(ctx, kindBacklog, arg.Now, arg.Kind)
	var i KindBacklogRow
	err := row.Scan(&i.Queued, &i.Running, &i.OldestDue)
	return i, err
}

const lastStartedJob = `-- name: LastStartedJob :one
SELECT id, kind, args, lane, sequence, state, attempt, max_attempts, not_before, leased_until, started_at, finished_at, error, counters, created_at FROM jobs WHERE kind = $1 AND started_at IS NOT NULL ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) LastStartedJob(ctx context.Context, kind string) (Job, error) {
	row := q.db.QueryRow(ctx, lastStartedJob, kind)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Args,
		&i.Lane,
		&i.Sequence,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NotBefore,
		&i.LeasedUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.Counters,
		&i.CreatedAt,
	)
	return i, err
}

const lastSucceededJob = `-- name: LastSucceededJob :one
SELECT id, kind, args, lane, sequence, state, attempt, max_attempts, not_before, leased_until, started_at, finished_at, error, counters, created_at FROM jobs WHERE kind = $1 AND state = 'succeeded' ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) LastSucceededJob(ctx context.Context, kind string) (Job, error) {
	row := q.db.QueryRow(ctx, lastSucceededJob, kind)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Args,
		&i.Lane,
		&i.Sequence,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NotBefore,
		&i.LeasedUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.Counters,
		&i.CreatedAt,
	)
	return i, err
}

const leaseJobs = `-- name: LeaseJobs :many
UPDATE jobs j
SET state = 'running', leased_until = $1::timestamptz, started_at = $2::timestamptz,
    finished_at = NULL, attempt = j.attempt + 1
WHERE j.id IN (
    SELECT c.id FROM jobs c
    WHERE c.state IN ('queued', 'running')
      AND c.kind = ANY($3::text[])
      AND c.not_before <= $2::timestamptz
      AND (c.leased_until IS NULL OR c.leased_until < $2::timestamptz)
      AND NOT (c.id = ANY($4::uuid[]))
      AND (c.lane IS NULL OR NOT EXISTS (
          SELECT 1 FROM jobs o
          WHERE o.lane = c.lane AND o.state IN ('queued', 'running')
            AND (o.sequence, o.id) < (c.sequence, c.id)
      ))
    ORDER BY c.not_before, c.created_at
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
RETURNING j.id, j.kind, j.args, j.lane, j.sequence, j.state, j.attempt, j.max_attempts, j.not_before, j.leased_until, j.started_at, j.finished_at, j.error, j.counters, j.created_at
`

type LeaseJobsParams struct {
	Until    time.Time
	Now      time.Time
	Kinds    []string
	Excluded []string
	Limit    int32
}

// LeaseJobs claims due rows of the kinds this dispatcher performs whose
// lease is absent or lapsed, skipping the rows it still has in flight. A
// lapsed lease claimed again is a new attempt. A row with a lane is its
// lane's head: no other unfinished row in the lane has a lower
// (sequence, id). A head waiting on its backoff holds the lane.
func (q *Queries) LeaseJobs(ctx context.Context, arg LeaseJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, leaseJobs,
		arg.Until,
		arg.Now,
		arg.Kinds,
		arg.Excluded,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Args,
			&i.Lane,
			&i.Sequence,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NotBefore,
			&i.LeasedUntil,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.Counters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockKindLeasing = `-- name: LockKindLeasing :exec
SELECT pg_advisory_xact_lock(4207020, hashtext($1::text))
`

// LockKindLeasing serialises the lease of one capped kind across
// dispatchers for the transaction, so the count below and the LeaseJobs
// that follows it see no concurrent lease. 4207020 is this lock's
// namespace; the storage quota lock in files.sql is 4207011.
func (q *Queries) LockKindLeasing(ctx context.Context, kind string) error {
	_, err := q.db.Exec(ctx, lockKindLeasing, kind)
	return err
}

const releaseJobs = `-- name: ReleaseJobs :exec
UPDATE jobs SET state = 'queued', leased_until = NULL, attempt = attempt - 1
WHERE state = 'running'
  AND (id, attempt) IN (SELECT unnest($1::uuid[]), unnest($2::int[]))
`

type ReleaseJobsParams struct {
	Ids      []string
	Attempts []int32
}

// ReleaseJobs clears the lease on a dispatcher's in-flight rows at
// shutdown and gives back the attempt the lease counted, so the next start
// retries them at no cost.
func (q *Queries) ReleaseJobs(ctx context.Context, arg ReleaseJobsParams) error {
	_, err := q.db.Exec(ctx, releaseJobs, arg.Ids, arg.Attempts)
	return err
}

const requeueJob = `-- name: RequeueJob :execrows
UPDATE jobs
SET state = 'queued', leased_until = NULL, finished_at = $1::timestamptz,
    error = $2, counters = $3, not_before = $4::timestamptz
WHERE id = $5 AND attempt = $6
`

type RequeueJobParams struct {
	Now       time.Time
	Error     string
	Counters  []byte
	NotBefore time.Time
	ID        string
	Attempt   int32
}

func (q *Queries) RequeueJob(ctx context.Context, arg RequeueJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueJob,
		arg.Now,
		arg.Error,
		arg.Counters,
		arg.NotBefore,
		arg.ID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepFinishedJobs = `-- name: SweepFinishedJobs :execrows
DELETE FROM jobs WHERE state IN ('succeeded', 'discarded') AND finished_at < $1::timestamptz
`

func (q *Queries) SweepFinishedJobs(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepFinishedJobs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
