// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
	"time"
)

const countQueuedJobs = `-- name: CountQueuedJobs :one
SELECT count(*) FROM jobs WHERE kind = $1 AND state = 'queued'
`

func (q *Queries) CountQueuedJobs(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRow(ctx, countQueuedJobs, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const extendJobLease = `-- name: ExtendJobLease :execrows
UPDATE jobs SET leased_until = GREATEST(leased_until, $1::timestamptz)
WHERE id = $2 AND attempt = $3 AND state = 'running'
`

type ExtendJobLeaseParams struct {
	Until   time.Time
	ID      string
	Attempt int32
}

// ExtendJobLease never moves a deadline earlier: a renewal keeps an
// Extend the performer asked for.
func (q *Queries) ExtendJobLease(ctx context.Context, arg ExtendJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendJobLease, arg.Until, arg.ID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishJob = `-- name: FinishJob :execrows
UPDATE jobs
SET state = $1, finished_at = $2::timestamptz, leased_until = NULL,
    error = $3, counters = $4
WHERE id = $5 AND attempt = $6
`

type FinishJobParams struct {
	State    string
	Now      time.Time
	Error    string
	Counters []byte
	ID       string
	Attempt  int32
}

// The outcome writes match the attempt they were leased for, so a stale
// attempt whose lease lapsed changes nothing.
func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishJob,
		arg.State,
		arg.Now,
		arg.Error,
		arg.Counters,
		arg.ID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, kind, args, lane, sequence, state, attempt, max_attempts, not_before, leased_until, started_at, finished_at, error, counters, created_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Args,
		&i.Lane,
		&i.Sequence,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NotBefore,
		&i.LeasedUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.Counters,
		&i.CreatedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec

INSERT INTO jobs (id, kind, args, state, attempt, max_attempts, not_before, created_at)
VALUES ($1, $2, $3, 'queued', 0, $4, $5::timestamptz, $6::timestamptz)
`

type InsertJobParams struct {
	ID          string
	Kind        string
	Args        []byte
	MaxAttempts int32
	NotBefore   time.Time
	Now         time.Time
}

// The job queue. Owned by the jobs module; only internal/jobs may use
// these queries. The clock is always the caller's, never now(), so one
// clock decides due-ness and leases. See docs/proposals/jobs.md.
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob,
		arg.ID,
		arg.Kind,
		arg.Args,
		arg.MaxAttempts,
		arg.NotBefore,
		arg.Now,
	)
	return err
}

const lastStartedJob = `-- name: LastStartedJob :one
SELECT id, kind, args, lane, sequence, state, attempt, max_attempts, not_before, leased_until, started_at, finished_at, error, counters, created_at FROM jobs WHERE kind = $1 AND started_at IS NOT NULL ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) LastStartedJob(ctx context.Context, kind string) (Job, error) {
	row := q.db.QueryRow(ctx, lastStartedJob, kind)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Args,
		&i.Lane,
		&i.Sequence,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NotBefore,
		&i.LeasedUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.Counters,
		&i.CreatedAt,
	)
	return i, err
}

const lastSucceededJob = `-- name: LastSucceededJob :one
SELECT id, kind, args, lane, sequence, state, attempt, max_attempts, not_before, leased_until, started_at, finished_at, error, counters, created_at FROM jobs WHERE kind = $1 AND state = 'succeeded' ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) LastSucceededJob(ctx context.Context, kind string) (Job, error) {
	row := q.db.QueryRow(ctx, lastSucceededJob, kind)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Args,
		&i.Lane,
		&i.Sequence,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NotBefore,
		&i.LeasedUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.Counters,
		&i.CreatedAt,
	)
	return i, err
}

const leaseJobs = `-- name: LeaseJobs :many
UPDATE jobs j
SET state = 'running', leased_until = $1::timestamptz, started_at = $2::timestamptz,
    finished_at = NULL, attempt = j.attempt + 1
WHERE j.id IN (
    SELECT c.id FROM jobs c
    WHERE c.state IN ('queued', 'running')
      AND c.kind = ANY($3::text[])
      AND c.not_before <= $2::timestamptz
      AND (c.leased_until IS NULL OR c.leased_until < $2::timestamptz)
    ORDER BY c.not_before, c.created_at
    LIMIT $4
    FOR UPDATE SKIP LOCKED
)
RETURNING j.id, j.kind, j.args, j.lane, j.sequence, j.state, j.attempt, j.max_attempts, j.not_before, j.leased_until, j.started_at, j.finished_at, j.error, j.counters, j.created_at
`

type LeaseJobsParams struct {
	Until time.Time
	Now   time.Time
	Kinds []string
	Limit int32
}

// LeaseJobs claims due rows of the kinds this dispatcher performs whose
// lease is absent or lapsed. A lapsed lease claimed again is a new attempt.
func (q *Queries) LeaseJobs(ctx context.Context, arg LeaseJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, leaseJobs,
		arg.Until,
		arg.Now,
		arg.Kinds,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Args,
			&i.Lane,
			&i.Sequence,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NotBefore,
			&i.LeasedUntil,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.Counters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseJobs = `-- name: ReleaseJobs :exec
UPDATE jobs SET state = 'queued', leased_until = NULL
WHERE state = 'running'
  AND (id, attempt) IN (SELECT unnest($1::uuid[]), unnest($2::int[]))
`

type ReleaseJobsParams struct {
	Ids      []string
	Attempts []int32
}

// ReleaseJobs clears the lease on a dispatcher's in-flight rows at
// shutdown, so the next start retries them.
func (q *Queries) ReleaseJobs(ctx context.Context, arg ReleaseJobsParams) error {
	_, err := q.db.Exec(ctx, releaseJobs, arg.Ids, arg.Attempts)
	return err
}

const requeueJob = `-- name: RequeueJob :execrows
UPDATE jobs
SET state = 'queued', leased_until = NULL, finished_at = $1::timestamptz,
    error = $2, counters = $3, not_before = $4::timestamptz
WHERE id = $5 AND attempt = $6
`

type RequeueJobParams struct {
	Now       time.Time
	Error     string
	Counters  []byte
	NotBefore time.Time
	ID        string
	Attempt   int32
}

func (q *Queries) RequeueJob(ctx context.Context, arg RequeueJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueJob,
		arg.Now,
		arg.Error,
		arg.Counters,
		arg.NotBefore,
		arg.ID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepFinishedJobs = `-- name: SweepFinishedJobs :execrows
DELETE FROM jobs WHERE state IN ('succeeded', 'discarded') AND finished_at < $1::timestamptz
`

func (q *Queries) SweepFinishedJobs(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepFinishedJobs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
