// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package dbgen

import (
	"context"
	"time"
)

const deleteMessageLinks = `-- name: DeleteMessageLinks :exec
DELETE FROM message_links WHERE message_id = $1
`

func (q *Queries) DeleteMessageLinks(ctx context.Context, messageID string) error {
	_, err := q.db.Exec(ctx, deleteMessageLinks, messageID)
	return err
}

const ensureLinkPreview = `-- name: EnsureLinkPreview :exec

INSERT INTO link_previews (url) VALUES ($1)
ON CONFLICT (url) DO NOTHING
`

// Link previews. Owned by the chat module.
// EnsureLinkPreview creates a pending row for a URL nobody has linked
// before; an existing row is left alone.
func (q *Queries) EnsureLinkPreview(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, ensureLinkPreview, url)
	return err
}

const getLinkPreview = `-- name: GetLinkPreview :one
SELECT url, state, fetched_at, title, description, site_name, image_file_id, image_width, image_height FROM link_previews WHERE url = $1
`

func (q *Queries) GetLinkPreview(ctx context.Context, url string) (LinkPreview, error) {
	row := q.db.QueryRow(ctx, getLinkPreview, url)
	var i LinkPreview
	err := row.Scan(
		&i.Url,
		&i.State,
		&i.FetchedAt,
		&i.Title,
		&i.Description,
		&i.SiteName,
		&i.ImageFileID,
		&i.ImageWidth,
		&i.ImageHeight,
	)
	return i, err
}

const insertMessageLink = `-- name: InsertMessageLink :exec
INSERT INTO message_links (message_id, position, url) VALUES ($1, $2, $3)
`

type InsertMessageLinkParams struct {
	MessageID string
	Position  int32
	Url       string
}

func (q *Queries) InsertMessageLink(ctx context.Context, arg InsertMessageLinkParams) error {
	_, err := q.db.Exec(ctx, insertMessageLink, arg.MessageID, arg.Position, arg.Url)
	return err
}

const listLinkPreviewsForMessages = `-- name: ListLinkPreviewsForMessages :many
SELECT ml.message_id, ml.position, p.url, p.state, p.fetched_at, p.title, p.description, p.site_name, p.image_file_id, p.image_width, p.image_height
FROM message_links ml
JOIN link_previews p ON p.url = ml.url
WHERE ml.message_id = ANY($1::uuid[]) AND p.state = 'ok'
ORDER BY ml.message_id, ml.position
`

type ListLinkPreviewsForMessagesRow struct {
	MessageID   string
	Position    int32
	Url         string
	State       string
	FetchedAt   *time.Time
	Title       string
	Description string
	SiteName    string
	ImageFileID *string
	ImageWidth  int32
	ImageHeight int32
}

func (q *Queries) ListLinkPreviewsForMessages(ctx context.Context, dollar_1 []string) ([]ListLinkPreviewsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, listLinkPreviewsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkPreviewsForMessagesRow
	for rows.Next() {
		var i ListLinkPreviewsForMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Position,
			&i.Url,
			&i.State,
			&i.FetchedAt,
			&i.Title,
			&i.Description,
			&i.SiteName,
			&i.ImageFileID,
			&i.ImageWidth,
			&i.ImageHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLinkPreview = `-- name: SetLinkPreview :exec
UPDATE link_previews
SET state = $2, fetched_at = now(), title = $3, description = $4, site_name = $5,
    image_file_id = $6, image_width = $7, image_height = $8
WHERE url = $1
`

type SetLinkPreviewParams struct {
	Url         string
	State       string
	Title       string
	Description string
	SiteName    string
	ImageFileID *string
	ImageWidth  int32
	ImageHeight int32
}

func (q *Queries) SetLinkPreview(ctx context.Context, arg SetLinkPreviewParams) error {
	_, err := q.db.Exec(ctx, setLinkPreview,
		arg.Url,
		arg.State,
		arg.Title,
		arg.Description,
		arg.SiteName,
		arg.ImageFileID,
		arg.ImageWidth,
		arg.ImageHeight,
	)
	return err
}
