// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package dbgen

import (
	"context"
)

const createSpaceMember = `-- name: CreateSpaceMember :exec

INSERT INTO space_members (space_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type CreateSpaceMemberParams struct {
	SpaceID string
	UserID  string
	Role    string
}

// Space membership and roles. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) CreateSpaceMember(ctx context.Context, arg CreateSpaceMemberParams) error {
	_, err := q.db.Exec(ctx, createSpaceMember, arg.SpaceID, arg.UserID, arg.Role)
	return err
}

const deleteSpaceMember = `-- name: DeleteSpaceMember :execrows
DELETE FROM space_members WHERE space_id = $1 AND user_id = $2
`

type DeleteSpaceMemberParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) DeleteSpaceMember(ctx context.Context, arg DeleteSpaceMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpaceMember, arg.SpaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSpaceMember = `-- name: GetSpaceMember :one
SELECT space_id, user_id, joined_at, role FROM space_members WHERE space_id = $1 AND user_id = $2
`

type GetSpaceMemberParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) GetSpaceMember(ctx context.Context, arg GetSpaceMemberParams) (SpaceMember, error) {
	row := q.db.QueryRow(ctx, getSpaceMember, arg.SpaceID, arg.UserID)
	var i SpaceMember
	err := row.Scan(
		&i.SpaceID,
		&i.UserID,
		&i.JoinedAt,
		&i.Role,
	)
	return i, err
}

const getSpaceMemberRole = `-- name: GetSpaceMemberRole :one
SELECT role FROM space_members WHERE space_id = $1 AND user_id = $2
`

type GetSpaceMemberRoleParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) GetSpaceMemberRole(ctx context.Context, arg GetSpaceMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getSpaceMemberRole, arg.SpaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS (
    SELECT 1
    FROM channels c
    LEFT JOIN space_members m ON m.space_id = c.space_id AND m.user_id = $2
    LEFT JOIN dm_members d ON d.channel_id = c.id AND d.user_id = $2
    WHERE c.id = $1 AND (m.user_id IS NOT NULL OR d.user_id IS NOT NULL)
) AS is_member
`

type IsChannelMemberParams struct {
	ID     string
	UserID string
}

// IsChannelMember: a member of the channel's space, or a participant in
// the direct message.
func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMember, arg.ID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const isSpaceMember = `-- name: IsSpaceMember :one
SELECT EXISTS (
    SELECT 1 FROM space_members WHERE space_id = $1 AND user_id = $2
) AS is_member
`

type IsSpaceMemberParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) IsSpaceMember(ctx context.Context, arg IsSpaceMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSpaceMember, arg.SpaceID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listSpaceIDsByUser = `-- name: ListSpaceIDsByUser :many
SELECT space_id FROM space_members WHERE user_id = $1
`

func (q *Queries) ListSpaceIDsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSpaceIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var space_id string
		if err := rows.Scan(&space_id); err != nil {
			return nil, err
		}
		items = append(items, space_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceMembers = `-- name: ListSpaceMembers :many
SELECT space_id, user_id, joined_at, role FROM space_members
WHERE space_id = $1
ORDER BY CASE role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END, joined_at
`

func (q *Queries) ListSpaceMembers(ctx context.Context, spaceID string) ([]SpaceMember, error) {
	rows, err := q.db.Query(ctx, listSpaceMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpaceMember
	for rows.Next() {
		var i SpaceMember
		if err := rows.Scan(
			&i.SpaceID,
			&i.UserID,
			&i.JoinedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSpaceMemberRole = `-- name: SetSpaceMemberRole :execrows
UPDATE space_members SET role = $3 WHERE space_id = $1 AND user_id = $2
`

type SetSpaceMemberRoleParams struct {
	SpaceID string
	UserID  string
	Role    string
}

func (q *Queries) SetSpaceMemberRole(ctx context.Context, arg SetSpaceMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSpaceMemberRole, arg.SpaceID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
