// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbgen

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages (id, channel_id, author_id, content, mentions_everyone, mentions_here, reply_to_message_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at
`

type CreateMessageParams struct {
	ID               string
	ChannelID        string
	AuthorID         string
	Content          string
	MentionsEveryone bool
	MentionsHere     bool
	ReplyToMessageID *string
}

// Messages. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Content,
		arg.MentionsEveryone,
		arg.MentionsHere,
		arg.ReplyToMessageID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.MentionsEveryone,
		&i.ReplyToMessageID,
		&i.MentionsHere,
		&i.EditedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.MentionsEveryone,
		&i.ReplyToMessageID,
		&i.MentionsHere,
		&i.EditedAt,
	)
	return i, err
}

const insertMessageMention = `-- name: InsertMessageMention :exec
INSERT INTO message_mentions (message_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertMessageMentionParams struct {
	MessageID string
	UserID    string
}

func (q *Queries) InsertMessageMention(ctx context.Context, arg InsertMessageMentionParams) error {
	_, err := q.db.Exec(ctx, insertMessageMention, arg.MessageID, arg.UserID)
	return err
}

const listMentionsForMessages = `-- name: ListMentionsForMessages :many
SELECT message_id, user_id FROM message_mentions
WHERE message_id = ANY($1::uuid[])
`

func (q *Queries) ListMentionsForMessages(ctx context.Context, dollar_1 []string) ([]MessageMention, error) {
	rows, err := q.db.Query(ctx, listMentionsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageMention
	for rows.Next() {
		var i MessageMention
		if err := rows.Scan(&i.MessageID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT m.id, m.channel_id, m.author_id, m.content, m.created_at, m.mentions_everyone, m.reply_to_message_id, m.mentions_here, m.edited_at, p.author_id AS reply_author_id, p.content AS reply_content,
    COALESCE((SELECT a.file_id::text FROM message_attachments a WHERE a.message_id = p.id ORDER BY a.position LIMIT 1), '')::text AS reply_first_file_id
FROM messages m
LEFT JOIN messages p ON p.id = m.reply_to_message_id
WHERE m.channel_id = $1
  AND (m.id > $3::uuid OR ($4::bool AND m.id = $3::uuid))
ORDER BY m.id ASC
LIMIT $2
`

type ListMessagesAfterParams struct {
	ChannelID string
	Limit     int32
	AfterID   string
	Inclusive bool
}

type ListMessagesAfterRow struct {
	Message          Message
	ReplyAuthorID    *string
	ReplyContent     *string
	ReplyFirstFileID string
}

// ListMessagesAfter is the forward counterpart: the oldest `limit` messages
// newer than after_id (or from it, when inclusive), oldest-first.
func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter,
		arg.ChannelID,
		arg.Limit,
		arg.AfterID,
		arg.Inclusive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesAfterRow
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.ChannelID,
			&i.Message.AuthorID,
			&i.Message.Content,
			&i.Message.CreatedAt,
			&i.Message.MentionsEveryone,
			&i.Message.ReplyToMessageID,
			&i.Message.MentionsHere,
			&i.Message.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT m.id, m.channel_id, m.author_id, m.content, m.created_at, m.mentions_everyone, m.reply_to_message_id, m.mentions_here, m.edited_at, p.author_id AS reply_author_id, p.content AS reply_content,
    COALESCE((SELECT a.file_id::text FROM message_attachments a WHERE a.message_id = p.id ORDER BY a.position LIMIT 1), '')::text AS reply_first_file_id
FROM messages m
LEFT JOIN messages p ON p.id = m.reply_to_message_id
WHERE m.channel_id = $1
  AND ($3::uuid IS NULL OR m.id < $3::uuid)
ORDER BY m.id DESC
LIMIT $2
`

type ListMessagesBeforeParams struct {
	ChannelID string
	Limit     int32
	BeforeID  *string
}

type ListMessagesBeforeRow struct {
	Message          Message
	ReplyAuthorID    *string
	ReplyContent     *string
	ReplyFirstFileID string
}

// ListMessagesBefore joins the replied-to message (if any) so the client
// can render a quote without a second round trip.
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.ChannelID, arg.Limit, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesBeforeRow
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.ChannelID,
			&i.Message.AuthorID,
			&i.Message.Content,
			&i.Message.CreatedAt,
			&i.Message.MentionsEveryone,
			&i.Message.ReplyToMessageID,
			&i.Message.MentionsHere,
			&i.Message.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeChannelLastMessage = `-- name: RecomputeChannelLastMessage :exec
UPDATE channels c
SET last_message_id = (SELECT m.id FROM messages m WHERE m.channel_id = c.id ORDER BY m.id DESC LIMIT 1)
WHERE c.id = $1
`

// RecomputeChannelLastMessage repoints a channel at its newest remaining
// message after a delete.
func (q *Queries) RecomputeChannelLastMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, recomputeChannelLastMessage, id)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages SET content = $2, edited_at = now() WHERE id = $1 RETURNING id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at
`

type UpdateMessageContentParams struct {
	ID      string
	Content string
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.MentionsEveryone,
		&i.ReplyToMessageID,
		&i.MentionsHere,
		&i.EditedAt,
	)
	return i, err
}
