// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbgen

import (
	"context"
	"time"
)

const countExpiredMessages = `-- name: CountExpiredMessages :one
WITH expired AS (
    SELECT m.id FROM messages m
    WHERE m.id < $1::uuid
      AND m.thread_root_id IS NULL
      AND NOT EXISTS (SELECT 1 FROM channel_pins p WHERE p.message_id = m.id)
)
SELECT ((SELECT count(*) FROM expired)
    + (SELECT count(*) FROM messages r WHERE r.thread_root_id IN (SELECT id FROM expired)))::bigint
`

// CountExpiredMessages is what the sweep would delete: the expired roots
// and every reply under them.
func (q *Queries) CountExpiredMessages(ctx context.Context, cutoff string) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiredMessages, cutoff)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRepliesUnder = `-- name: CountRepliesUnder :one
SELECT count(*)::bigint FROM messages WHERE thread_root_id = ANY($1::uuid[])
`

// CountRepliesUnder counts the replies the cascade will take with these
// roots.
func (q *Queries) CountRepliesUnder(ctx context.Context, ids []string) (int64, error) {
	row := q.db.QueryRow(ctx, countRepliesUnder, ids)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages (id, channel_id, author_id, content, mentions_channel, mentions_here, reply_to_message_id,
    thread_root_id, in_channel)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, thread_root_id, in_channel, deleted_at, mentions_channel
`

type CreateMessageParams struct {
	ID               string
	ChannelID        string
	AuthorID         string
	Content          string
	MentionsChannel  bool
	MentionsHere     bool
	ReplyToMessageID *string
	ThreadRootID     *string
	InChannel        bool
}

type CreateMessageRow struct {
	ID               string
	ChannelID        string
	AuthorID         string
	Content          string
	CreatedAt        time.Time
	MentionsEveryone bool
	ReplyToMessageID *string
	MentionsHere     bool
	EditedAt         *time.Time
	ThreadRootID     *string
	InChannel        bool
	DeletedAt        *time.Time
	MentionsChannel  bool
}

// Messages. Owned by the chat module.
// Only internal/chat may use these queries.
//
// A message goes to a client through the message_with_reply view, which
// leaves out messages.search and adds the reply quote. The queries here
// that skip the view list the same columns. A new messages column goes in
// each list and in the view; see docs/architecture/messaging.md → Search.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Content,
		arg.MentionsChannel,
		arg.MentionsHere,
		arg.ReplyToMessageID,
		arg.ThreadRootID,
		arg.InChannel,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.MentionsEveryone,
		&i.ReplyToMessageID,
		&i.MentionsHere,
		&i.EditedAt,
		&i.ThreadRootID,
		&i.InChannel,
		&i.DeletedAt,
		&i.MentionsChannel,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const deleteMessagesByIDs = `-- name: DeleteMessagesByIDs :exec
DELETE FROM messages WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteMessagesByIDs(ctx context.Context, ids []string) error {
	_, err := q.db.Exec(ctx, deleteMessagesByIDs, ids)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, thread_root_id, in_channel, deleted_at, mentions_channel
FROM messages WHERE id = $1
`

type GetMessageRow struct {
	ID               string
	ChannelID        string
	AuthorID         string
	Content          string
	CreatedAt        time.Time
	MentionsEveryone bool
	ReplyToMessageID *string
	MentionsHere     bool
	EditedAt         *time.Time
	ThreadRootID     *string
	InChannel        bool
	DeletedAt        *time.Time
	MentionsChannel  bool
}

func (q *Queries) GetMessage(ctx context.Context, id string) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.MentionsEveryone,
		&i.ReplyToMessageID,
		&i.MentionsHere,
		&i.EditedAt,
		&i.ThreadRootID,
		&i.InChannel,
		&i.DeletedAt,
		&i.MentionsChannel,
	)
	return i, err
}

const getMessageWithReply = `-- name: GetMessageWithReply :one
SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, reply_author_id, reply_content, reply_first_file_id, thread_root_id, in_channel, deleted_at, thread_reply_count, thread_last_reply_at, thread_recent_author_ids, mentions_channel FROM message_with_reply m
WHERE m.id = $1
`

// GetMessageWithReply is one message with the reply columns, for the
// events that resend a message after it changes.
func (q *Queries) GetMessageWithReply(ctx context.Context, id string) (MessageWithReply, error) {
	row := q.db.QueryRow(ctx, getMessageWithReply, id)
	var i MessageWithReply
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.MentionsEveryone,
		&i.ReplyToMessageID,
		&i.MentionsHere,
		&i.EditedAt,
		&i.ReplyAuthorID,
		&i.ReplyContent,
		&i.ReplyFirstFileID,
		&i.ThreadRootID,
		&i.InChannel,
		&i.DeletedAt,
		&i.ThreadReplyCount,
		&i.ThreadLastReplyAt,
		&i.ThreadRecentAuthorIds,
		&i.MentionsChannel,
	)
	return i, err
}

const insertMessageMentions = `-- name: InsertMessageMentions :exec
INSERT INTO message_mentions (message_id, user_id)
SELECT $1::uuid, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type InsertMessageMentionsParams struct {
	MessageID string
	UserIds   []string
}

func (q *Queries) InsertMessageMentions(ctx context.Context, arg InsertMessageMentionsParams) error {
	_, err := q.db.Exec(ctx, insertMessageMentions, arg.MessageID, arg.UserIds)
	return err
}

const listExpiredMessages = `-- name: ListExpiredMessages :many
SELECT m.id, m.channel_id FROM messages m
WHERE m.id < $1::uuid
  AND m.thread_root_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM channel_pins p WHERE p.message_id = m.id)
ORDER BY m.id
LIMIT $2
`

type ListExpiredMessagesParams struct {
	Cutoff string
	Limit  int32
}

type ListExpiredMessagesRow struct {
	ID        string
	ChannelID string
}

// Message retention: top-level messages older than the cutoff id
// (UUIDv7, so id order is time order), less pinned ones, oldest first. A
// thread goes by its root's age, so replies are never listed: deleting
// the root takes them, however recent.
func (q *Queries) ListExpiredMessages(ctx context.Context, arg ListExpiredMessagesParams) ([]ListExpiredMessagesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredMessages, arg.Cutoff, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredMessagesRow
	for rows.Next() {
		var i ListExpiredMessagesRow
		if err := rows.Scan(&i.ID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsForMessages = `-- name: ListMentionsForMessages :many
SELECT message_id, user_id FROM message_mentions
WHERE message_id = ANY($1::uuid[])
`

func (q *Queries) ListMentionsForMessages(ctx context.Context, dollar_1 []string) ([]MessageMention, error) {
	rows, err := q.db.Query(ctx, listMentionsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageMention
	for rows.Next() {
		var i MessageMention
		if err := rows.Scan(&i.MessageID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, reply_author_id, reply_content, reply_first_file_id, thread_root_id, in_channel, deleted_at, thread_reply_count, thread_last_reply_at, thread_recent_author_ids, mentions_channel FROM message_with_reply m
WHERE m.channel_id = $1
  AND m.in_channel
  AND (m.id > $3::uuid OR ($4::bool AND m.id = $3::uuid))
ORDER BY m.id ASC
LIMIT $2
`

type ListMessagesAfterParams struct {
	ChannelID string
	Limit     int32
	AfterID   string
	Inclusive bool
}

// ListMessagesAfter is the forward counterpart: the oldest `limit` messages
// newer than after_id (or from it, when inclusive), oldest-first.
func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]MessageWithReply, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter,
		arg.ChannelID,
		arg.Limit,
		arg.AfterID,
		arg.Inclusive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageWithReply
	for rows.Next() {
		var i MessageWithReply
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.MentionsEveryone,
			&i.ReplyToMessageID,
			&i.MentionsHere,
			&i.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
			&i.ThreadRootID,
			&i.InChannel,
			&i.DeletedAt,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.ThreadRecentAuthorIds,
			&i.MentionsChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, reply_author_id, reply_content, reply_first_file_id, thread_root_id, in_channel, deleted_at, thread_reply_count, thread_last_reply_at, thread_recent_author_ids, mentions_channel FROM message_with_reply m
WHERE m.channel_id = $1
  AND m.in_channel
  AND ($3::uuid IS NULL OR m.id < $3::uuid)
ORDER BY m.id DESC
LIMIT $2
`

type ListMessagesBeforeParams struct {
	ChannelID string
	Limit     int32
	BeforeID  *string
}

// ListMessagesBefore carries the replied-to message's quote (if any) so
// the client can render it without a second round trip. Only rows that
// show in the channel: a thread's replies are paged by ListThreadBefore.
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]MessageWithReply, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.ChannelID, arg.Limit, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageWithReply
	for rows.Next() {
		var i MessageWithReply
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.MentionsEveryone,
			&i.ReplyToMessageID,
			&i.MentionsHere,
			&i.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
			&i.ThreadRootID,
			&i.InChannel,
			&i.DeletedAt,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.ThreadRecentAuthorIds,
			&i.MentionsChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeChannelLastMessage = `-- name: RecomputeChannelLastMessage :exec
UPDATE channels c
SET last_message_id = (SELECT m.id FROM messages m WHERE m.channel_id = c.id AND m.in_channel ORDER BY m.id DESC LIMIT 1)
WHERE c.id = $1
`

// RecomputeChannelLastMessage repoints a channel at its newest remaining
// message that shows in the channel, after a delete.
func (q *Queries) RecomputeChannelLastMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, recomputeChannelLastMessage, id)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages SET content = $2, edited_at = now() WHERE id = $1 AND deleted_at IS NULL
RETURNING id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, thread_root_id, in_channel, deleted_at, mentions_channel
`

type UpdateMessageContentParams struct {
	ID      string
	Content string
}

type UpdateMessageContentRow struct {
	ID               string
	ChannelID        string
	AuthorID         string
	Content          string
	CreatedAt        time.Time
	MentionsEveryone bool
	ReplyToMessageID *string
	MentionsHere     bool
	EditedAt         *time.Time
	ThreadRootID     *string
	InChannel        bool
	DeletedAt        *time.Time
	MentionsChannel  bool
}

// UpdateMessageContent never writes onto a root kept as a placeholder: no
// row comes back, even when the placeholder landed after the caller's
// check.
func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (UpdateMessageContentRow, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.ID, arg.Content)
	var i UpdateMessageContentRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.MentionsEveryone,
		&i.ReplyToMessageID,
		&i.MentionsHere,
		&i.EditedAt,
		&i.ThreadRootID,
		&i.InChannel,
		&i.DeletedAt,
		&i.MentionsChannel,
	)
	return i, err
}
