// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type ActivityItem struct {
	ID        string
	UserID    string
	Kind      string
	SpaceID   *string
	ChannelID string
	MessageID *string
	ActorID   string
	CreatedAt time.Time
	ReadAt    *time.Time
}

type Channel struct {
	ID            string
	SpaceID       *string
	Name          string
	Kind          int16
	Position      int32
	CreatedAt     time.Time
	LastMessageID *string
	DmKey         *string
	Topic         string
	PostPolicy    string
}

type ChannelMute struct {
	UserID    string
	ChannelID string
	CreatedAt time.Time
}

type ChannelPin struct {
	MessageID string
	ChannelID string
	PinnedBy  string
	PinnedAt  time.Time
}

type ChannelRead struct {
	UserID            string
	ChannelID         string
	LastReadMessageID string
	UpdatedAt         time.Time
}

type Credential struct {
	ID         string
	HolderID   string
	Kind       string
	TokenHash  []byte
	Name       string
	Grants     []string
	Bounded    bool
	CreatedBy  *string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	Hint       string
	UserAgent  string
}

type CredentialBound struct {
	CredentialID string
	SpaceID      *string
	ChannelID    *string
}

type DmMember struct {
	ChannelID string
	UserID    string
	ClosedAt  *time.Time
}

type File struct {
	ID          string
	Kind        string
	OwnerID     string
	SpaceID     *string
	ContentType string
	Size        int64
	Sha256      []byte
	StorageKey  string
	CreatedAt   time.Time
	Name        string
	ExpiredAt   *time.Time
}

type IncomingWebhook struct {
	ID             string
	SpaceID        string
	ChannelID      string
	BotUserID      string
	CredentialID   *string
	Name           string
	CreatedBy      string
	CreatedAt      time.Time
	DisabledAt     *time.Time
	DisabledReason string
}

type InstanceSetting struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}

type Invite struct {
	ID        string
	SpaceID   string
	Code      string
	CreatedBy string
	ExpiresAt *time.Time
	MaxUses   *int32
	UseCount  int32
	RevokedAt *time.Time
	CreatedAt time.Time
	Role      string
}

type LinkPreview struct {
	Url         string
	State       string
	FetchedAt   *time.Time
	Title       string
	Description string
	SiteName    string
	ImageFileID *string
	ImageWidth  int32
	ImageHeight int32
}

type Message struct {
	ID               string
	ChannelID        string
	AuthorID         string
	Content          string
	CreatedAt        time.Time
	MentionsEveryone bool
	ReplyToMessageID *string
	MentionsHere     bool
	EditedAt         *time.Time
	Search           interface{}
}

type MessageAttachment struct {
	MessageID string
	FileID    string
	Position  int32
}

type MessageLink struct {
	MessageID string
	Position  int32
	Url       string
}

type MessageMention struct {
	MessageID string
	UserID    string
}

type MessageReaction struct {
	MessageID string
	UserID    string
	Emoji     string
	CreatedAt time.Time
}

type OutgoingWebhook struct {
	ID             string
	SpaceID        string
	ChannelID      *string
	Url            string
	Secret         []byte
	EventTypes     []string
	Sequence       int64
	Name           string
	CreatedBy      string
	CreatedAt      time.Time
	DisabledAt     *time.Time
	DisabledReason string
}

type SchemaFloor struct {
	MinMigration int64
}

type Session struct {
	ID        string
	UserID    string
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Space struct {
	ID               string
	Name             string
	OwnerID          string
	CreatedAt        time.Time
	MembersCanInvite bool
	IconFileID       *string
	Description      string
	Welcome          string
	DefaultChannelID *string
}

type SpaceBan struct {
	SpaceID   string
	UserID    string
	BannedBy  *string
	Reason    string
	CreatedAt time.Time
}

type SpaceMember struct {
	SpaceID  string
	UserID   string
	JoinedAt time.Time
	Role     string
}

type SpaceMute struct {
	UserID    string
	SpaceID   string
	CreatedAt time.Time
}

type User struct {
	ID              string
	Username        string
	DisplayName     string
	PasswordHash    *string
	CreatedAt       time.Time
	Role            string
	DeactivatedAt   *time.Time
	AvatarFileID    *string
	UsernamePending bool
	UsernameFrozen  bool
	Pronouns        string
	Bio             string
	Kind            string
	Dnd             bool
	DndUntil        *time.Time
	DeletedAt       *time.Time
	IsOwner         bool
}

type UserBlock struct {
	BlockerID string
	BlockedID string
	CreatedAt time.Time
}

type UserIdentity struct {
	Provider  string
	Subject   string
	UserID    string
	Email     string
	CreatedAt time.Time
}

type WebhookDelivery struct {
	ID          string
	Lane        string
	EventType   string
	Sequence    int64
	Body        []byte
	Attempts    int32
	NotBefore   time.Time
	LeasedUntil *time.Time
	FinishedAt  *time.Time
	StatusCode  *int32
	Response    string
	Error       string
	CreatedAt   time.Time
}
