// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type ActivityItem struct {
	ID        string
	UserID    string
	Kind      string
	SpaceID   *string
	ChannelID string
	MessageID *string
	ActorID   string
	CreatedAt time.Time
	ReadAt    *time.Time
}

type Channel struct {
	ID            string
	SpaceID       *string
	Name          string
	Kind          int16
	Position      int32
	CreatedAt     time.Time
	LastMessageID *string
	DmKey         *string
	Topic         string
}

type ChannelMute struct {
	UserID    string
	ChannelID string
	CreatedAt time.Time
}

type ChannelRead struct {
	UserID            string
	ChannelID         string
	LastReadMessageID string
	UpdatedAt         time.Time
}

type DmMember struct {
	ChannelID string
	UserID    string
}

type File struct {
	ID          string
	Kind        string
	OwnerID     string
	SpaceID     *string
	ContentType string
	Size        int64
	Sha256      []byte
	StorageKey  string
	CreatedAt   time.Time
	Name        string
}

type InstanceSetting struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}

type Invite struct {
	ID        string
	SpaceID   string
	Code      string
	CreatedBy string
	ExpiresAt *time.Time
	MaxUses   *int32
	UseCount  int32
	RevokedAt *time.Time
	CreatedAt time.Time
	Role      string
}

type LinkPreview struct {
	Url         string
	State       string
	FetchedAt   *time.Time
	Title       string
	Description string
	SiteName    string
	ImageFileID *string
	ImageWidth  int32
	ImageHeight int32
}

type Message struct {
	ID               string
	ChannelID        string
	AuthorID         string
	Content          string
	CreatedAt        time.Time
	MentionsEveryone bool
	ReplyToMessageID *string
	MentionsHere     bool
	EditedAt         *time.Time
	Search           interface{}
}

type MessageAttachment struct {
	MessageID string
	FileID    string
	Position  int32
}

type MessageLink struct {
	MessageID string
	Position  int32
	Url       string
}

type MessageMention struct {
	MessageID string
	UserID    string
}

type MessageReaction struct {
	MessageID string
	UserID    string
	Emoji     string
	CreatedAt time.Time
}

type SchemaFloor struct {
	MinMigration int64
}

type Session struct {
	ID        string
	UserID    string
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Space struct {
	ID               string
	Name             string
	OwnerID          string
	CreatedAt        time.Time
	MembersCanInvite bool
	IconFileID       *string
	Description      string
	Welcome          string
	DefaultChannelID *string
}

type SpaceBan struct {
	SpaceID   string
	UserID    string
	BannedBy  *string
	Reason    string
	CreatedAt time.Time
}

type SpaceMember struct {
	SpaceID  string
	UserID   string
	JoinedAt time.Time
	Role     string
}

type SpaceMute struct {
	UserID    string
	SpaceID   string
	CreatedAt time.Time
}

type User struct {
	ID              string
	Username        string
	DisplayName     string
	PasswordHash    *string
	CreatedAt       time.Time
	Role            string
	DeactivatedAt   *time.Time
	AvatarFileID    *string
	UsernamePending bool
	UsernameFrozen  bool
	Pronouns        string
	Bio             string
}

type UserBlock struct {
	BlockerID string
	BlockedID string
	CreatedAt time.Time
}

type UserIdentity struct {
	Provider  string
	Subject   string
	UserID    string
	Email     string
	CreatedAt time.Time
}
