// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mutes.sql

package dbgen

import (
	"context"
)

const isMutedFor = `-- name: IsMutedFor :one
SELECT (EXISTS (SELECT 1 FROM channel_mutes cm WHERE cm.user_id = $1::uuid AND cm.channel_id = $2::uuid)
    OR EXISTS (SELECT 1 FROM space_mutes sm WHERE sm.user_id = $1::uuid AND sm.space_id = $3::uuid))::bool
`

type IsMutedForParams struct {
	UserID    string
	ChannelID string
	SpaceID   *string
}

// IsMutedFor answers, for one recipient, whether where something
// happened is effectively muted for them: their own channel row or
// their own space row. space_id is NULL for a direct message.
func (q *Queries) IsMutedFor(ctx context.Context, arg IsMutedForParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMutedFor, arg.UserID, arg.ChannelID, arg.SpaceID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const muteChannel = `-- name: MuteChannel :exec

INSERT INTO channel_mutes (user_id, channel_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MuteChannelParams struct {
	UserID    string
	ChannelID string
}

// Per-channel and per-space mutes. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) MuteChannel(ctx context.Context, arg MuteChannelParams) error {
	_, err := q.db.Exec(ctx, muteChannel, arg.UserID, arg.ChannelID)
	return err
}

const muteSpace = `-- name: MuteSpace :exec
INSERT INTO space_mutes (user_id, space_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MuteSpaceParams struct {
	UserID  string
	SpaceID string
}

func (q *Queries) MuteSpace(ctx context.Context, arg MuteSpaceParams) error {
	_, err := q.db.Exec(ctx, muteSpace, arg.UserID, arg.SpaceID)
	return err
}

const unmuteChannel = `-- name: UnmuteChannel :exec
DELETE FROM channel_mutes WHERE user_id = $1 AND channel_id = $2
`

type UnmuteChannelParams struct {
	UserID    string
	ChannelID string
}

func (q *Queries) UnmuteChannel(ctx context.Context, arg UnmuteChannelParams) error {
	_, err := q.db.Exec(ctx, unmuteChannel, arg.UserID, arg.ChannelID)
	return err
}

const unmuteSpace = `-- name: UnmuteSpace :exec
DELETE FROM space_mutes WHERE user_id = $1 AND space_id = $2
`

type UnmuteSpaceParams struct {
	UserID  string
	SpaceID string
}

func (q *Queries) UnmuteSpace(ctx context.Context, arg UnmuteSpaceParams) error {
	_, err := q.db.Exec(ctx, unmuteSpace, arg.UserID, arg.SpaceID)
	return err
}
