// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mutes.sql

package dbgen

import (
	"context"
)

const muteChannel = `-- name: MuteChannel :exec

INSERT INTO channel_mutes (user_id, channel_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MuteChannelParams struct {
	UserID    string
	ChannelID string
}

// Per-channel and per-space mutes. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) MuteChannel(ctx context.Context, arg MuteChannelParams) error {
	_, err := q.db.Exec(ctx, muteChannel, arg.UserID, arg.ChannelID)
	return err
}

const muteSpace = `-- name: MuteSpace :exec
INSERT INTO space_mutes (user_id, space_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MuteSpaceParams struct {
	UserID  string
	SpaceID string
}

func (q *Queries) MuteSpace(ctx context.Context, arg MuteSpaceParams) error {
	_, err := q.db.Exec(ctx, muteSpace, arg.UserID, arg.SpaceID)
	return err
}

const mutedAmong = `-- name: MutedAmong :many
SELECT cm.user_id FROM channel_mutes cm
WHERE cm.channel_id = $1::uuid AND cm.user_id = ANY($2::uuid[])
UNION
SELECT sm.user_id FROM space_mutes sm
WHERE sm.space_id = $3::uuid AND sm.user_id = ANY($2::uuid[])
UNION
SELECT tm.user_id FROM thread_mutes tm
WHERE tm.root_message_id = $4::uuid AND tm.user_id = ANY($2::uuid[])
`

type MutedAmongParams struct {
	ChannelID    string
	UserIds      []string
	SpaceID      *string
	ThreadRootID *string
}

// MutedAmong: which of these recipients have muted where something
// happened, by their own channel, space or thread row. space_id is NULL
// for a direct message, thread_root_id outside a thread.
func (q *Queries) MutedAmong(ctx context.Context, arg MutedAmongParams) ([]string, error) {
	rows, err := q.db.Query(ctx, mutedAmong,
		arg.ChannelID,
		arg.UserIds,
		arg.SpaceID,
		arg.ThreadRootID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unmuteChannel = `-- name: UnmuteChannel :exec
DELETE FROM channel_mutes WHERE user_id = $1 AND channel_id = $2
`

type UnmuteChannelParams struct {
	UserID    string
	ChannelID string
}

func (q *Queries) UnmuteChannel(ctx context.Context, arg UnmuteChannelParams) error {
	_, err := q.db.Exec(ctx, unmuteChannel, arg.UserID, arg.ChannelID)
	return err
}

const unmuteSpace = `-- name: UnmuteSpace :exec
DELETE FROM space_mutes WHERE user_id = $1 AND space_id = $2
`

type UnmuteSpaceParams struct {
	UserID  string
	SpaceID string
}

func (q *Queries) UnmuteSpace(ctx context.Context, arg UnmuteSpaceParams) error {
	_, err := q.db.Exec(ctx, unmuteSpace, arg.UserID, arg.SpaceID)
	return err
}
