// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outgoing_webhooks.sql

package dbgen

import (
	"context"
)

const countOutgoingWebhooksBySpace = `-- name: CountOutgoingWebhooksBySpace :one
SELECT count(*) FROM outgoing_webhooks WHERE space_id = $1
`

func (q *Queries) CountOutgoingWebhooksBySpace(ctx context.Context, spaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOutgoingWebhooksBySpace, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOutgoingWebhook = `-- name: CreateOutgoingWebhook :one

INSERT INTO outgoing_webhooks (id, space_id, channel_id, url, secret, event_types, name, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, space_id, channel_id, url, secret, event_types, sequence, name, created_by, created_at, disabled_at, disabled_reason
`

type CreateOutgoingWebhookParams struct {
	ID         string
	SpaceID    string
	ChannelID  *string
	Url        string
	Secret     []byte
	EventTypes []string
	Name       string
	CreatedBy  string
}

// Outgoing webhooks. Owned by the integrations module.
// Only internal/integrations may use these queries.
func (q *Queries) CreateOutgoingWebhook(ctx context.Context, arg CreateOutgoingWebhookParams) (OutgoingWebhook, error) {
	row := q.db.QueryRow(ctx, createOutgoingWebhook,
		arg.ID,
		arg.SpaceID,
		arg.ChannelID,
		arg.Url,
		arg.Secret,
		arg.EventTypes,
		arg.Name,
		arg.CreatedBy,
	)
	var i OutgoingWebhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Sequence,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const deleteOutgoingWebhook = `-- name: DeleteOutgoingWebhook :one
DELETE FROM outgoing_webhooks WHERE id = $1 RETURNING id, space_id, channel_id, url, secret, event_types, sequence, name, created_by, created_at, disabled_at, disabled_reason
`

func (q *Queries) DeleteOutgoingWebhook(ctx context.Context, id string) (OutgoingWebhook, error) {
	row := q.db.QueryRow(ctx, deleteOutgoingWebhook, id)
	var i OutgoingWebhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Sequence,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const disableOutgoingWebhook = `-- name: DisableOutgoingWebhook :exec
UPDATE outgoing_webhooks SET disabled_at = now(), disabled_reason = $2 WHERE id = $1
`

type DisableOutgoingWebhookParams struct {
	ID             string
	DisabledReason string
}

func (q *Queries) DisableOutgoingWebhook(ctx context.Context, arg DisableOutgoingWebhookParams) error {
	_, err := q.db.Exec(ctx, disableOutgoingWebhook, arg.ID, arg.DisabledReason)
	return err
}

const enableOutgoingWebhook = `-- name: EnableOutgoingWebhook :exec
UPDATE outgoing_webhooks SET disabled_at = NULL, disabled_reason = '' WHERE id = $1
`

func (q *Queries) EnableOutgoingWebhook(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, enableOutgoingWebhook, id)
	return err
}

const getOutgoingWebhook = `-- name: GetOutgoingWebhook :one
SELECT id, space_id, channel_id, url, secret, event_types, sequence, name, created_by, created_at, disabled_at, disabled_reason FROM outgoing_webhooks WHERE id = $1
`

func (q *Queries) GetOutgoingWebhook(ctx context.Context, id string) (OutgoingWebhook, error) {
	row := q.db.QueryRow(ctx, getOutgoingWebhook, id)
	var i OutgoingWebhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Sequence,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const listEnabledOutgoingWebhooksBySpace = `-- name: ListEnabledOutgoingWebhooksBySpace :many
SELECT id, space_id, channel_id, url, secret, event_types, sequence, name, created_by, created_at, disabled_at, disabled_reason FROM outgoing_webhooks WHERE space_id = $1 AND disabled_at IS NULL ORDER BY id
`

// ListEnabledOutgoingWebhooksBySpace is the subscriber's match list.
func (q *Queries) ListEnabledOutgoingWebhooksBySpace(ctx context.Context, spaceID string) ([]OutgoingWebhook, error) {
	rows, err := q.db.Query(ctx, listEnabledOutgoingWebhooksBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutgoingWebhook
	for rows.Next() {
		var i OutgoingWebhook
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Sequence,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingWebhooks = `-- name: ListOutgoingWebhooks :many
SELECT id, space_id, channel_id, url, secret, event_types, sequence, name, created_by, created_at, disabled_at, disabled_reason FROM outgoing_webhooks ORDER BY space_id, created_at, id
`

func (q *Queries) ListOutgoingWebhooks(ctx context.Context) ([]OutgoingWebhook, error) {
	rows, err := q.db.Query(ctx, listOutgoingWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutgoingWebhook
	for rows.Next() {
		var i OutgoingWebhook
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Sequence,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingWebhooksBySpace = `-- name: ListOutgoingWebhooksBySpace :many
SELECT id, space_id, channel_id, url, secret, event_types, sequence, name, created_by, created_at, disabled_at, disabled_reason FROM outgoing_webhooks WHERE space_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListOutgoingWebhooksBySpace(ctx context.Context, spaceID string) ([]OutgoingWebhook, error) {
	rows, err := q.db.Query(ctx, listOutgoingWebhooksBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutgoingWebhook
	for rows.Next() {
		var i OutgoingWebhook
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Sequence,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOutgoingSequence = `-- name: NextOutgoingSequence :one
UPDATE outgoing_webhooks SET sequence = sequence + 1 WHERE id = $1 RETURNING sequence
`

// NextOutgoingSequence takes the Stoop-Sequence number for one delivery.
func (q *Queries) NextOutgoingSequence(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, nextOutgoingSequence, id)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const setOutgoingWebhookSecret = `-- name: SetOutgoingWebhookSecret :exec
UPDATE outgoing_webhooks SET secret = $2 WHERE id = $1
`

type SetOutgoingWebhookSecretParams struct {
	ID     string
	Secret []byte
}

func (q *Queries) SetOutgoingWebhookSecret(ctx context.Context, arg SetOutgoingWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, setOutgoingWebhookSecret, arg.ID, arg.Secret)
	return err
}

const updateOutgoingWebhook = `-- name: UpdateOutgoingWebhook :exec
UPDATE outgoing_webhooks
SET name = $2, url = $3, channel_id = $4, event_types = $5
WHERE id = $1
`

type UpdateOutgoingWebhookParams struct {
	ID         string
	Name       string
	Url        string
	ChannelID  *string
	EventTypes []string
}

func (q *Queries) UpdateOutgoingWebhook(ctx context.Context, arg UpdateOutgoingWebhookParams) error {
	_, err := q.db.Exec(ctx, updateOutgoingWebhook,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.ChannelID,
		arg.EventTypes,
	)
	return err
}
