// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package dbgen

import (
	"context"
)

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT t.id, t.user_id, u.username
FROM email_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1::bytea
  AND t.purpose = 'reset_password'
  AND t.used_at IS NULL
  AND t.expires_at > now()
  AND u.deactivated_at IS NULL
  AND u.kind = 'person'
  AND u.email = t.address
`

type GetPasswordResetTokenRow struct {
	ID       string
	UserID   string
	Username string
}

// GetPasswordResetToken is a live reset link whose address is still the
// account's confirmed one, on an active person's account.
func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash []byte) (GetPasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i GetPasswordResetTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.Username)
	return i, err
}

const lockPasswordResetToken = `-- name: LockPasswordResetToken :one
SELECT t.id, t.user_id, u.username
FROM email_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1::bytea
  AND t.purpose = 'reset_password'
  AND t.used_at IS NULL
  AND t.expires_at > now()
  AND u.deactivated_at IS NULL
  AND u.kind = 'person'
  AND u.email = t.address
FOR UPDATE OF t
`

type LockPasswordResetTokenRow struct {
	ID       string
	UserID   string
	Username string
}

// LockPasswordResetToken is GetPasswordResetToken with the link locked;
// the account already is (LockUserEmail).
func (q *Queries) LockPasswordResetToken(ctx context.Context, tokenHash []byte) (LockPasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, lockPasswordResetToken, tokenHash)
	var i LockPasswordResetTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.Username)
	return i, err
}

const passwordResetAccount = `-- name: PasswordResetAccount :one

SELECT id, role, kind, (deactivated_at IS NOT NULL)::bool AS deactivated
FROM users
WHERE email = $1::citext
`

type PasswordResetAccountRow struct {
	ID          string
	Role        string
	Kind        string
	Deactivated bool
}

// Password reset by email. Owned by the auth module.
// Only internal/auth may use these queries.
// PasswordResetAccount is the account whose confirmed address this is.
func (q *Queries) PasswordResetAccount(ctx context.Context, address string) (PasswordResetAccountRow, error) {
	row := q.db.QueryRow(ctx, passwordResetAccount, address)
	var i PasswordResetAccountRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Kind,
		&i.Deactivated,
	)
	return i, err
}
