// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pins.sql

package dbgen

import (
	"context"
	"time"
)

const getPin = `-- name: GetPin :one
SELECT message_id, channel_id, pinned_by, pinned_at FROM channel_pins WHERE message_id = $1
`

func (q *Queries) GetPin(ctx context.Context, messageID string) (ChannelPin, error) {
	row := q.db.QueryRow(ctx, getPin, messageID)
	var i ChannelPin
	err := row.Scan(
		&i.MessageID,
		&i.ChannelID,
		&i.PinnedBy,
		&i.PinnedAt,
	)
	return i, err
}

const listChannelPins = `-- name: ListChannelPins :many
SELECT m.id, m.channel_id, m.author_id, m.content, m.created_at, m.mentions_everyone, m.reply_to_message_id, m.mentions_here, m.edited_at, m.search, p.author_id AS reply_author_id, p.content AS reply_content,
    COALESCE((SELECT a.file_id::text FROM message_attachments a WHERE a.message_id = p.id ORDER BY a.position LIMIT 1), '')::text AS reply_first_file_id,
    pin.pinned_by, pin.pinned_at
FROM channel_pins pin
JOIN messages m ON m.id = pin.message_id
LEFT JOIN messages p ON p.id = m.reply_to_message_id
WHERE pin.channel_id = $1::uuid
ORDER BY pin.pinned_at DESC, pin.message_id DESC
LIMIT $2
`

type ListChannelPinsParams struct {
	ChannelID string
	Lim       int32
}

type ListChannelPinsRow struct {
	Message          Message
	ReplyAuthorID    *string
	ReplyContent     *string
	ReplyFirstFileID string
	PinnedBy         string
	PinnedAt         time.Time
}

// ListChannelPins carries the same reply columns as ListMessagesBefore so
// the rows hydrate through one path (internal/chat/messages.go); keep the
// two column lists in step.
func (q *Queries) ListChannelPins(ctx context.Context, arg ListChannelPinsParams) ([]ListChannelPinsRow, error) {
	rows, err := q.db.Query(ctx, listChannelPins, arg.ChannelID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelPinsRow
	for rows.Next() {
		var i ListChannelPinsRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.ChannelID,
			&i.Message.AuthorID,
			&i.Message.Content,
			&i.Message.CreatedAt,
			&i.Message.MentionsEveryone,
			&i.Message.ReplyToMessageID,
			&i.Message.MentionsHere,
			&i.Message.EditedAt,
			&i.Message.Search,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
			&i.PinnedBy,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinMessage = `-- name: PinMessage :one

INSERT INTO channel_pins (message_id, channel_id, pinned_by)
SELECT $1::uuid, $2::uuid, $3::uuid
WHERE (SELECT count(*) FROM channel_pins WHERE channel_id = $2::uuid) < $4::int
ON CONFLICT (message_id) DO NOTHING
RETURNING message_id, channel_id, pinned_by, pinned_at
`

type PinMessageParams struct {
	MessageID string
	ChannelID string
	PinnedBy  string
	Cap       int32
}

// Pinned messages. Owned by the chat module.
// Only internal/chat may use these queries.
// PinMessage is the cap check and the insert in one statement, so a pin
// cannot read a stale count and then write. No row comes back when the
// message is already pinned or the channel is full; the caller tells
// those apart with GetPin.
func (q *Queries) PinMessage(ctx context.Context, arg PinMessageParams) (ChannelPin, error) {
	row := q.db.QueryRow(ctx, pinMessage,
		arg.MessageID,
		arg.ChannelID,
		arg.PinnedBy,
		arg.Cap,
	)
	var i ChannelPin
	err := row.Scan(
		&i.MessageID,
		&i.ChannelID,
		&i.PinnedBy,
		&i.PinnedAt,
	)
	return i, err
}

const pinnedMessageIDs = `-- name: PinnedMessageIDs :many
SELECT message_id FROM channel_pins WHERE message_id = ANY($1::uuid[])
`

// PinnedMessageIDs stamps the pinned flag on a page of messages: one
// primary-key lookup over a table holding at most the cap per channel.
func (q *Queries) PinnedMessageIDs(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, pinnedMessageIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message_id string
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unpinMessage = `-- name: UnpinMessage :execrows
DELETE FROM channel_pins WHERE message_id = $1
`

func (q *Queries) UnpinMessage(ctx context.Context, messageID string) (int64, error) {
	result, err := q.db.Exec(ctx, unpinMessage, messageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
