// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reactions.sql

package dbgen

import (
	"context"
)

const addReaction = `-- name: AddReaction :execrows

INSERT INTO message_reactions (message_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	MessageID string
	UserID    string
	Emoji     string
}

// Emoji reactions. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReactionsForMessages = `-- name: ListReactionsForMessages :many
SELECT message_id, emoji, user_id
FROM message_reactions
WHERE message_id = ANY($1::uuid[])
ORDER BY message_id, emoji, created_at, user_id
`

type ListReactionsForMessagesRow struct {
	MessageID string
	Emoji     string
	UserID    string
}

// ListReactionsForMessages feeds one grouped pass per page. Ordered by
// emoji, then by when each reaction was added, so chip order is stable
// and the reactor lists are in arrival order.
func (q *Queries) ListReactionsForMessages(ctx context.Context, dollar_1 []string) ([]ListReactionsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, listReactionsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionsForMessagesRow
	for rows.Next() {
		var i ListReactionsForMessagesRow
		if err := rows.Scan(&i.MessageID, &i.Emoji, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :execrows
DELETE FROM message_reactions
WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID string
	UserID    string
	Emoji     string
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
