// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"
	"time"
)

const getChannelInSpaceByName = `-- name: GetChannelInSpaceByName :one
SELECT id, space_id, name, kind, position, created_at, last_message_id, dm_key, topic, post_policy, required FROM channels
WHERE space_id = $1::uuid AND lower(name) = lower($2)
ORDER BY (name = $2) DESC, position, created_at
LIMIT 1
`

type GetChannelInSpaceByNameParams struct {
	SpaceID string
	Name    string
}

// GetChannelInSpaceByName resolves an in:#name filter. Names from before
// the naming rule may repeat or carry capitals: an exact match wins, then
// the first by position, as in the sidebar.
func (q *Queries) GetChannelInSpaceByName(ctx context.Context, arg GetChannelInSpaceByNameParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelInSpaceByName, arg.SpaceID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Kind,
		&i.Position,
		&i.CreatedAt,
		&i.LastMessageID,
		&i.DmKey,
		&i.Topic,
		&i.PostPolicy,
		&i.Required,
	)
	return i, err
}

const searchMessages = `-- name: SearchMessages :many

SELECT m.id, m.channel_id, m.author_id, m.content, m.created_at, m.mentions_everyone, m.reply_to_message_id, m.mentions_here, m.edited_at, m.reply_author_id, m.reply_content, m.reply_first_file_id, m.thread_root_id, m.in_channel, m.deleted_at, m.thread_reply_count, m.thread_last_reply_at, m.thread_recent_author_ids, m.mentions_channel FROM message_with_reply m
JOIN messages indexed ON indexed.id = m.id
WHERE m.channel_id IN (SELECT c.id FROM channels c WHERE c.space_id = $1::uuid
        AND ($2::bool OR c.kind <> 2))
  AND indexed.search @@ (CASE
      WHEN $3::text = '' THEN websearch_to_tsquery('simple', $4::text)
      WHEN $4::text = '' THEN to_tsquery('simple', $3::text)
      ELSE websearch_to_tsquery('simple', $4::text) && to_tsquery('simple', $3::text)
      END)
  AND ($5::uuid IS NULL OR m.channel_id = $5::uuid)
  AND ($6::uuid IS NULL OR m.author_id = $6::uuid)
  AND ($7::timestamptz IS NULL OR m.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR m.created_at < $8::timestamptz)
  AND ($9::uuid IS NULL OR m.id < $9::uuid)
ORDER BY m.id DESC
LIMIT $10
`

type SearchMessagesParams struct {
	SpaceID   string
	WithVoice bool
	Prefix    string
	Words     string
	ChannelID *string
	AuthorID  *string
	AfterAt   *time.Time
	BeforeAt  *time.Time
	BeforeID  *string
	Lim       int32
}

// Message search. Owned by the chat module.
// Only internal/chat may use these queries.
// SearchMessages: one space's channels, newest first, read from
// message_with_reply like ListMessagesBefore, joined back to messages
// for the search vector the view leaves out. `words` is websearch
// syntax; `prefix` is a quoted lexeme with :* or "" (see
// internal/chat/search_query.go). Dates bound created_at; the cursor
// bounds id. Hidden voice channels (kind 2) are left out.
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]MessageWithReply, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.SpaceID,
		arg.WithVoice,
		arg.Prefix,
		arg.Words,
		arg.ChannelID,
		arg.AuthorID,
		arg.AfterAt,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageWithReply
	for rows.Next() {
		var i MessageWithReply
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.MentionsEveryone,
			&i.ReplyToMessageID,
			&i.MentionsHere,
			&i.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
			&i.ThreadRootID,
			&i.InChannel,
			&i.DeletedAt,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.ThreadRecentAuthorIds,
			&i.MentionsChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
