// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"
	"time"
)

const getChannelInSpaceByName = `-- name: GetChannelInSpaceByName :one
SELECT id, space_id, name, kind, position, created_at, last_message_id, dm_key, topic FROM channels
WHERE space_id = $1::uuid AND name = $2
ORDER BY position, created_at
LIMIT 1
`

type GetChannelInSpaceByNameParams struct {
	SpaceID string
	Name    string
}

// GetChannelInSpaceByName resolves an in:#name filter. Names are not
// unique within a space; the first by position wins, as in the sidebar.
func (q *Queries) GetChannelInSpaceByName(ctx context.Context, arg GetChannelInSpaceByNameParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelInSpaceByName, arg.SpaceID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Kind,
		&i.Position,
		&i.CreatedAt,
		&i.LastMessageID,
		&i.DmKey,
		&i.Topic,
	)
	return i, err
}

const searchMessages = `-- name: SearchMessages :many

SELECT m.id, m.channel_id, m.author_id, m.content, m.created_at, m.mentions_everyone, m.reply_to_message_id, m.mentions_here, m.edited_at, m.search, p.author_id AS reply_author_id, p.content AS reply_content,
    COALESCE((SELECT a.file_id::text FROM message_attachments a WHERE a.message_id = p.id ORDER BY a.position LIMIT 1), '')::text AS reply_first_file_id
FROM messages m
LEFT JOIN messages p ON p.id = m.reply_to_message_id
WHERE m.channel_id IN (SELECT c.id FROM channels c WHERE c.space_id = $1::uuid)
  AND m.search @@ (CASE WHEN $2::text = ''
      THEN websearch_to_tsquery('simple', $3::text)
      ELSE websearch_to_tsquery('simple', $3::text) && to_tsquery('simple', $2::text)
      END)
  AND ($4::uuid IS NULL OR m.channel_id = $4::uuid)
  AND ($5::uuid IS NULL OR m.author_id = $5::uuid)
  AND ($6::timestamptz IS NULL OR m.created_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR m.created_at < $7::timestamptz)
  AND ($8::uuid IS NULL OR m.id < $8::uuid)
ORDER BY m.id DESC
LIMIT $9
`

type SearchMessagesParams struct {
	SpaceID   string
	Prefix    string
	Words     string
	ChannelID *string
	AuthorID  *string
	AfterAt   *time.Time
	BeforeAt  *time.Time
	BeforeID  *string
	Lim       int32
}

type SearchMessagesRow struct {
	Message          Message
	ReplyAuthorID    *string
	ReplyContent     *string
	ReplyFirstFileID string
}

// Message search. Owned by the chat module.
// Only internal/chat may use these queries.
// SearchMessages: one space's channels, newest first, with the same reply
// columns as ListMessagesBefore so rows hydrate through one path. `words`
// is websearch syntax; `prefix` is a quoted lexeme with :* or "" (see
// internal/chat/search_query.go). Dates bound created_at; the cursor
// bounds id.
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.SpaceID,
		arg.Prefix,
		arg.Words,
		arg.ChannelID,
		arg.AuthorID,
		arg.AfterAt,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.ChannelID,
			&i.Message.AuthorID,
			&i.Message.Content,
			&i.Message.CreatedAt,
			&i.Message.MentionsEveryone,
			&i.Message.ReplyToMessageID,
			&i.Message.MentionsHere,
			&i.Message.EditedAt,
			&i.Message.Search,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
