// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: send_window.sql

package dbgen

import (
	"context"
	"time"
)

const takeSendSlot = `-- name: TakeSendSlot :one

INSERT INTO instance_settings (key, value)
VALUES ('smtp_send_window', jsonb_build_object('start', $1::timestamptz, 'count', 1))
ON CONFLICT (key) DO UPDATE SET
    value = CASE
        WHEN (instance_settings.value->>'start')::timestamptz <= $2::timestamptz
            THEN jsonb_build_object('start', $1::timestamptz, 'count', 1)
        ELSE jsonb_set(instance_settings.value, '{count}',
            to_jsonb((instance_settings.value->>'count')::int + 1))
    END,
    updated_at = now()
WHERE (instance_settings.value->>'start')::timestamptz <= $2::timestamptz
   OR (instance_settings.value->>'count')::int < $3::int
RETURNING value
`

type TakeSendSlotParams struct {
	Now           time.Time
	ExpiredBefore time.Time
	HourlyLimit   int32
}

// The outbound email cap: one fixed one-hour window in the settings row
// smtp_send_window ({start, count}). Owned by the instance module.
// TakeSendSlot counts one send, starting a new window when the saved one
// started at or before expired_before (an hour ago). No row comes back
// when the window is full.
func (q *Queries) TakeSendSlot(ctx context.Context, arg TakeSendSlotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, takeSendSlot, arg.Now, arg.ExpiredBefore, arg.HourlyLimit)
	var value []byte
	err := row.Scan(&value)
	return value, err
}
