// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :execrows
DELETE FROM instance_settings WHERE key = $1
`

// DeleteSetting removes a saved value, so the next start seeds it from the
// environment again (stoop admin setting reset).
func (q *Queries) DeleteSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSetting = `-- name: GetSetting :one

SELECT value FROM instance_settings WHERE key = $1
`

// Instance settings. Owned by the instance module.
// Only internal/instance may use these queries.
func (q *Queries) GetSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const seedSetting = `-- name: SeedSetting :exec
INSERT INTO instance_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
`

type SeedSettingParams struct {
	Key   string
	Value []byte
}

// SeedSetting only inserts when the key is absent.
func (q *Queries) SeedSetting(ctx context.Context, arg SeedSettingParams) error {
	_, err := q.db.Exec(ctx, seedSetting, arg.Key, arg.Value)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO instance_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
