// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package dbgen

import (
	"context"
)

const clearSpaceDefaultChannel = `-- name: ClearSpaceDefaultChannel :one
UPDATE spaces SET default_channel_id = NULL
WHERE id = $1::uuid
  AND default_channel_id = $2::uuid
RETURNING id, name, owner_id, created_at, members_can_invite, icon_file_id, description, welcome, default_channel_id
`

type ClearSpaceDefaultChannelParams struct {
	ID        string
	ChannelID string
}

// Clears the landing channel, but only while it is still the channel
// being deleted. Returning a row is how the caller learns it cleared
// anything: reading the space and comparing would leave a window for
// another admin's edit between the read and the delete. The UPDATE takes
// the space's row lock, so a concurrent UpdateSpaceSettings waits.
func (q *Queries) ClearSpaceDefaultChannel(ctx context.Context, arg ClearSpaceDefaultChannelParams) (Space, error) {
	row := q.db.QueryRow(ctx, clearSpaceDefaultChannel, arg.ID, arg.ChannelID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.MembersCanInvite,
		&i.IconFileID,
		&i.Description,
		&i.Welcome,
		&i.DefaultChannelID,
	)
	return i, err
}

const createSpace = `-- name: CreateSpace :one

INSERT INTO spaces (id, name, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, owner_id, created_at, members_can_invite, icon_file_id, description, welcome, default_channel_id
`

type CreateSpaceParams struct {
	ID      string
	Name    string
	OwnerID string
}

// Spaces: the community-level container. Owned by the chat module.
// Only internal/chat may use these queries.
func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace, arg.ID, arg.Name, arg.OwnerID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.MembersCanInvite,
		&i.IconFileID,
		&i.Description,
		&i.Welcome,
		&i.DefaultChannelID,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getSpace = `-- name: GetSpace :one
SELECT id, name, owner_id, created_at, members_can_invite, icon_file_id, description, welcome, default_channel_id FROM spaces WHERE id = $1
`

func (q *Queries) GetSpace(ctx context.Context, id string) (Space, error) {
	row := q.db.QueryRow(ctx, getSpace, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.MembersCanInvite,
		&i.IconFileID,
		&i.Description,
		&i.Welcome,
		&i.DefaultChannelID,
	)
	return i, err
}

const getSpaceIconForUpdate = `-- name: GetSpaceIconForUpdate :one
SELECT icon_file_id FROM spaces WHERE id = $1 FOR UPDATE
`

// The icon pointer is replaced in a transaction: lock the row and read the
// current file id, then update, so the caller can delete the old blob
// without racing another upload.
func (q *Queries) GetSpaceIconForUpdate(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getSpaceIconForUpdate, id)
	var icon_file_id *string
	err := row.Scan(&icon_file_id)
	return icon_file_id, err
}

const listSpacesByUser = `-- name: ListSpacesByUser :many
SELECT s.id, s.name, s.owner_id, s.created_at, s.members_can_invite, s.icon_file_id, s.description, s.welcome, s.default_channel_id, m.role AS my_role,
    EXISTS (SELECT 1 FROM space_mutes sm WHERE sm.space_id = s.id AND sm.user_id = m.user_id) AS muted,
    EXISTS (
        SELECT 1 FROM channels c
        LEFT JOIN channel_reads r ON r.channel_id = c.id AND r.user_id = m.user_id
        WHERE c.space_id = s.id
          AND c.last_message_id IS NOT NULL
          AND (r.last_read_message_id IS NULL OR c.last_message_id > r.last_read_message_id)
          AND NOT EXISTS (SELECT 1 FROM channel_mutes cm WHERE cm.channel_id = c.id AND cm.user_id = m.user_id)
    ) AS has_unread
FROM spaces s
JOIN space_members m ON m.space_id = s.id
WHERE m.user_id = $1
ORDER BY m.joined_at
`

type ListSpacesByUserRow struct {
	Space     Space
	MyRole    string
	Muted     bool
	HasUnread bool
}

// ListSpacesByUser also returns the caller's role in each space, whether
// any channel there has messages newer than their read marker, and their
// own mute for the space. has_unread does not know about space mutes; the
// client derives the effective state from both flags.
func (q *Queries) ListSpacesByUser(ctx context.Context, userID string) ([]ListSpacesByUserRow, error) {
	rows, err := q.db.Query(ctx, listSpacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpacesByUserRow
	for rows.Next() {
		var i ListSpacesByUserRow
		if err := rows.Scan(
			&i.Space.ID,
			&i.Space.Name,
			&i.Space.OwnerID,
			&i.Space.CreatedAt,
			&i.Space.MembersCanInvite,
			&i.Space.IconFileID,
			&i.Space.Description,
			&i.Space.Welcome,
			&i.Space.DefaultChannelID,
			&i.MyRole,
			&i.Muted,
			&i.HasUnread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSpaceIcon = `-- name: SetSpaceIcon :exec
UPDATE spaces SET icon_file_id = $2 WHERE id = $1
`

type SetSpaceIconParams struct {
	ID         string
	IconFileID *string
}

func (q *Queries) SetSpaceIcon(ctx context.Context, arg SetSpaceIconParams) error {
	_, err := q.db.Exec(ctx, setSpaceIcon, arg.ID, arg.IconFileID)
	return err
}

const updateSpaceOwner = `-- name: UpdateSpaceOwner :exec
UPDATE spaces SET owner_id = $2 WHERE id = $1
`

type UpdateSpaceOwnerParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) UpdateSpaceOwner(ctx context.Context, arg UpdateSpaceOwnerParams) error {
	_, err := q.db.Exec(ctx, updateSpaceOwner, arg.ID, arg.OwnerID)
	return err
}

const updateSpaceSettings = `-- name: UpdateSpaceSettings :one
UPDATE spaces
SET name = COALESCE($2, name),
    members_can_invite = COALESCE($3, members_can_invite),
    description = COALESCE($4, description),
    welcome = COALESCE($5, welcome),
    default_channel_id = CASE WHEN $6::boolean
        THEN $7::uuid
        ELSE default_channel_id END
WHERE id = $1
RETURNING id, name, owner_id, created_at, members_can_invite, icon_file_id, description, welcome, default_channel_id
`

type UpdateSpaceSettingsParams struct {
	ID                string
	Name              *string
	MembersCanInvite  *bool
	Description       *string
	Welcome           *string
	SetDefaultChannel bool
	DefaultChannelID  *string
}

// Every column here is COALESCE'd so an unset parameter leaves it alone,
// except default_channel_id: it is nullable, so NULL is a value a caller
// can mean ("go back to the first channel") and COALESCE could not tell
// that apart from "don't touch it". A separate boolean says whether to
// write the column at all.
func (q *Queries) UpdateSpaceSettings(ctx context.Context, arg UpdateSpaceSettingsParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpaceSettings,
		arg.ID,
		arg.Name,
		arg.MembersCanInvite,
		arg.Description,
		arg.Welcome,
		arg.SetDefaultChannel,
		arg.DefaultChannelID,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.MembersCanInvite,
		&i.IconFileID,
		&i.Description,
		&i.Welcome,
		&i.DefaultChannelID,
	)
	return i, err
}
