// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package dbgen

import (
	"context"
	"time"
)

const listThreadAfter = `-- name: ListThreadAfter :many
SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, reply_author_id, reply_content, reply_first_file_id, thread_root_id, in_channel, deleted_at, thread_reply_count, thread_last_reply_at, thread_recent_author_ids FROM message_with_reply m
WHERE m.thread_root_id = $1::uuid
  AND (m.id > $2::uuid OR ($3::bool AND m.id = $2::uuid))
ORDER BY m.id ASC
LIMIT $4
`

type ListThreadAfterParams struct {
	RootID    string
	AfterID   string
	Inclusive bool
	Limit     int32
}

func (q *Queries) ListThreadAfter(ctx context.Context, arg ListThreadAfterParams) ([]MessageWithReply, error) {
	rows, err := q.db.Query(ctx, listThreadAfter,
		arg.RootID,
		arg.AfterID,
		arg.Inclusive,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageWithReply
	for rows.Next() {
		var i MessageWithReply
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.MentionsEveryone,
			&i.ReplyToMessageID,
			&i.MentionsHere,
			&i.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
			&i.ThreadRootID,
			&i.InChannel,
			&i.DeletedAt,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.ThreadRecentAuthorIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadBefore = `-- name: ListThreadBefore :many

SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, reply_author_id, reply_content, reply_first_file_id, thread_root_id, in_channel, deleted_at, thread_reply_count, thread_last_reply_at, thread_recent_author_ids FROM message_with_reply m
WHERE m.thread_root_id = $1::uuid
  AND ($2::uuid IS NULL OR m.id < $2::uuid)
ORDER BY m.id DESC
LIMIT $3
`

type ListThreadBeforeParams struct {
	RootID   string
	BeforeID *string
	Limit    int32
}

// Threads: a root's replies and its summary row. Owned by the chat module.
// Only internal/chat may use these queries. docs/architecture/messaging.md.
// ListThreadBefore pages a thread backwards, like ListMessagesBefore; the
// root itself is not a reply and is not returned.
func (q *Queries) ListThreadBefore(ctx context.Context, arg ListThreadBeforeParams) ([]MessageWithReply, error) {
	rows, err := q.db.Query(ctx, listThreadBefore, arg.RootID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageWithReply
	for rows.Next() {
		var i MessageWithReply
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.MentionsEveryone,
			&i.ReplyToMessageID,
			&i.MentionsHere,
			&i.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
			&i.ThreadRootID,
			&i.InChannel,
			&i.DeletedAt,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.ThreadRecentAuthorIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordThreadReply = `-- name: RecordThreadReply :one
INSERT INTO threads (root_message_id, reply_count, last_reply_id, last_reply_at, recent_author_ids)
VALUES ($1, 1, $2, $3, ARRAY[$4::uuid])
ON CONFLICT (root_message_id) DO UPDATE SET
    reply_count = threads.reply_count + 1,
    last_reply_id = EXCLUDED.last_reply_id,
    last_reply_at = EXCLUDED.last_reply_at,
    recent_author_ids = (ARRAY[$4::uuid] || array_remove(threads.recent_author_ids, $4::uuid))[1:3]
RETURNING root_message_id, reply_count, last_reply_id, last_reply_at, recent_author_ids
`

type RecordThreadReplyParams struct {
	RootID   string
	ReplyID  *string
	ReplyAt  *time.Time
	AuthorID string
}

// RecordThreadReply counts a new reply into its root's summary: the
// author moves to the front of the recent authors, which keep three.
func (q *Queries) RecordThreadReply(ctx context.Context, arg RecordThreadReplyParams) (Thread, error) {
	row := q.db.QueryRow(ctx, recordThreadReply,
		arg.RootID,
		arg.ReplyID,
		arg.ReplyAt,
		arg.AuthorID,
	)
	var i Thread
	err := row.Scan(
		&i.RootMessageID,
		&i.ReplyCount,
		&i.LastReplyID,
		&i.LastReplyAt,
		&i.RecentAuthorIds,
	)
	return i, err
}
