// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package dbgen

import (
	"context"
	"time"
)

const deleteThreadSummary = `-- name: DeleteThreadSummary :exec
DELETE FROM threads WHERE root_message_id = $1
`

func (q *Queries) DeleteThreadSummary(ctx context.Context, rootMessageID string) error {
	_, err := q.db.Exec(ctx, deleteThreadSummary, rootMessageID)
	return err
}

const listThreadAfter = `-- name: ListThreadAfter :many
SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, reply_author_id, reply_content, reply_first_file_id, thread_root_id, in_channel, deleted_at, thread_reply_count, thread_last_reply_at, thread_recent_author_ids FROM message_with_reply m
WHERE m.thread_root_id = $1::uuid
  AND (m.id > $2::uuid OR ($3::bool AND m.id = $2::uuid))
ORDER BY m.id ASC
LIMIT $4
`

type ListThreadAfterParams struct {
	RootID    string
	AfterID   string
	Inclusive bool
	Limit     int32
}

func (q *Queries) ListThreadAfter(ctx context.Context, arg ListThreadAfterParams) ([]MessageWithReply, error) {
	rows, err := q.db.Query(ctx, listThreadAfter,
		arg.RootID,
		arg.AfterID,
		arg.Inclusive,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageWithReply
	for rows.Next() {
		var i MessageWithReply
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.MentionsEveryone,
			&i.ReplyToMessageID,
			&i.MentionsHere,
			&i.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
			&i.ThreadRootID,
			&i.InChannel,
			&i.DeletedAt,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.ThreadRecentAuthorIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadBefore = `-- name: ListThreadBefore :many

SELECT id, channel_id, author_id, content, created_at, mentions_everyone, reply_to_message_id, mentions_here, edited_at, reply_author_id, reply_content, reply_first_file_id, thread_root_id, in_channel, deleted_at, thread_reply_count, thread_last_reply_at, thread_recent_author_ids FROM message_with_reply m
WHERE m.thread_root_id = $1::uuid
  AND ($2::uuid IS NULL OR m.id < $2::uuid)
ORDER BY m.id DESC
LIMIT $3
`

type ListThreadBeforeParams struct {
	RootID   string
	BeforeID *string
	Limit    int32
}

// Threads: a root's replies and its summary row. Owned by the chat module.
// Only internal/chat may use these queries. docs/architecture/messaging.md.
// ListThreadBefore pages a thread backwards, like ListMessagesBefore; the
// root itself is not a reply and is not returned.
func (q *Queries) ListThreadBefore(ctx context.Context, arg ListThreadBeforeParams) ([]MessageWithReply, error) {
	rows, err := q.db.Query(ctx, listThreadBefore, arg.RootID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageWithReply
	for rows.Next() {
		var i MessageWithReply
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.MentionsEveryone,
			&i.ReplyToMessageID,
			&i.MentionsHere,
			&i.EditedAt,
			&i.ReplyAuthorID,
			&i.ReplyContent,
			&i.ReplyFirstFileID,
			&i.ThreadRootID,
			&i.InChannel,
			&i.DeletedAt,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.ThreadRecentAuthorIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadFileIDs = `-- name: ListThreadFileIDs :many
SELECT a.file_id FROM message_attachments a
JOIN messages m ON m.id = a.message_id
WHERE m.id = $1::uuid OR m.thread_root_id = $1::uuid
`

// ListThreadFileIDs lists the files of a root and every reply under it,
// for Delete thread.
func (q *Queries) ListThreadFileIDs(ctx context.Context, rootID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listThreadFileIDs, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_id string
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockThread = `-- name: LockThread :one
SELECT reply_count FROM threads WHERE root_message_id = $1 FOR UPDATE
`

// LockThread takes a root's summary row for the rest of the transaction,
// so a delete's recount and a concurrent send's increment can't miss
// each other. No row means the root has no replies.
func (q *Queries) LockThread(ctx context.Context, rootMessageID string) (int32, error) {
	row := q.db.QueryRow(ctx, lockThread, rootMessageID)
	var reply_count int32
	err := row.Scan(&reply_count)
	return reply_count, err
}

const makePlaceholder = `-- name: MakePlaceholder :exec
WITH attachments AS (DELETE FROM message_attachments WHERE message_id = $1::uuid),
links AS (DELETE FROM message_links WHERE message_id = $1::uuid),
reactions AS (DELETE FROM message_reactions WHERE message_id = $1::uuid),
mentions AS (DELETE FROM message_mentions WHERE message_id = $1::uuid),
pins AS (DELETE FROM channel_pins WHERE message_id = $1::uuid),
activity AS (DELETE FROM activity_items WHERE message_id = $1::uuid)
UPDATE messages SET content = '', mentions_everyone = false, mentions_here = false,
    edited_at = NULL, deleted_at = now()
WHERE id = $1::uuid
`

// MakePlaceholder keeps a root whose thread still has replies as an empty
// row: no text, attachments, previews, reactions, mentions, pin or
// activity. Its files are deleted through the port afterwards.
func (q *Queries) MakePlaceholder(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, makePlaceholder, id)
	return err
}

const recomputeThread = `-- name: RecomputeThread :one
WITH replies AS (
    SELECT id, author_id, created_at FROM messages WHERE thread_root_id = $1::uuid
), latest AS (
    SELECT id, created_at FROM replies ORDER BY id DESC LIMIT 1
), authors AS (
    SELECT author_id, id FROM (
        SELECT DISTINCT ON (author_id) author_id, id FROM replies ORDER BY author_id, id DESC
    ) newest_per_author ORDER BY id DESC LIMIT 3
)
UPDATE threads SET
    reply_count = (SELECT count(*) FROM replies),
    last_reply_id = (SELECT id FROM latest),
    last_reply_at = (SELECT created_at FROM latest),
    recent_author_ids = COALESCE((SELECT array_agg(author_id ORDER BY id DESC) FROM authors), '{}')
WHERE root_message_id = $1::uuid
RETURNING root_message_id, reply_count, last_reply_id, last_reply_at, recent_author_ids
`

// RecomputeThread recounts a root's summary from its remaining replies,
// after one is deleted.
func (q *Queries) RecomputeThread(ctx context.Context, rootID string) (Thread, error) {
	row := q.db.QueryRow(ctx, recomputeThread, rootID)
	var i Thread
	err := row.Scan(
		&i.RootMessageID,
		&i.ReplyCount,
		&i.LastReplyID,
		&i.LastReplyAt,
		&i.RecentAuthorIds,
	)
	return i, err
}

const recordThreadReply = `-- name: RecordThreadReply :one
INSERT INTO threads (root_message_id, reply_count, last_reply_id, last_reply_at, recent_author_ids)
VALUES ($1, 1, $2, $3, ARRAY[$4::uuid])
ON CONFLICT (root_message_id) DO UPDATE SET
    reply_count = threads.reply_count + 1,
    last_reply_id = EXCLUDED.last_reply_id,
    last_reply_at = EXCLUDED.last_reply_at,
    recent_author_ids = (ARRAY[$4::uuid] || array_remove(threads.recent_author_ids, $4::uuid))[1:3]
RETURNING root_message_id, reply_count, last_reply_id, last_reply_at, recent_author_ids
`

type RecordThreadReplyParams struct {
	RootID   string
	ReplyID  *string
	ReplyAt  *time.Time
	AuthorID string
}

// RecordThreadReply counts a new reply into its root's summary: the
// author moves to the front of the recent authors, which keep three.
func (q *Queries) RecordThreadReply(ctx context.Context, arg RecordThreadReplyParams) (Thread, error) {
	row := q.db.QueryRow(ctx, recordThreadReply,
		arg.RootID,
		arg.ReplyID,
		arg.ReplyAt,
		arg.AuthorID,
	)
	var i Thread
	err := row.Scan(
		&i.RootMessageID,
		&i.ReplyCount,
		&i.LastReplyID,
		&i.LastReplyAt,
		&i.RecentAuthorIds,
	)
	return i, err
}

const threadParticipants = `-- name: ThreadParticipants :many
SELECT DISTINCT m.author_id FROM messages m
JOIN channels c ON c.id = m.channel_id
WHERE (m.id = $1::uuid
       OR (m.thread_root_id = $1::uuid AND m.id < $2::uuid))
  AND (EXISTS (SELECT 1 FROM space_members sm WHERE sm.space_id = c.space_id AND sm.user_id = m.author_id)
       OR EXISTS (SELECT 1 FROM dm_members dm WHERE dm.channel_id = c.id AND dm.user_id = m.author_id))
`

type ThreadParticipantsParams struct {
	RootID  string
	ReplyID string
}

// ThreadParticipants are the root's author and everyone who replied
// before reply_id, for the phase 1 thread notifications, less anyone no
// longer in the space (or, for a DM, the conversation): message rows
// outlive a leave or a kick.
func (q *Queries) ThreadParticipants(ctx context.Context, arg ThreadParticipantsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, threadParticipants, arg.RootID, arg.ReplyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var author_id string
		if err := rows.Scan(&author_id); err != nil {
			return nil, err
		}
		items = append(items, author_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
