// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thread_mutes.sql

package dbgen

import (
	"context"
)

const listThreadMutes = `-- name: ListThreadMutes :many
SELECT m.id, m.channel_id, m.author_id, m.content, m.created_at, m.mentions_everyone, m.reply_to_message_id, m.mentions_here, m.edited_at, m.reply_author_id, m.reply_content, m.reply_first_file_id, m.thread_root_id, m.in_channel, m.deleted_at, m.thread_reply_count, m.thread_last_reply_at, m.thread_recent_author_ids, m.mentions_channel, c.id, c.space_id, c.name, c.kind, c.position, c.created_at, c.last_message_id, c.dm_key, c.topic, c.post_policy, c.required
FROM thread_mutes tm
JOIN message_with_reply m ON m.id = tm.root_message_id
JOIN channels c ON c.id = m.channel_id
WHERE tm.user_id = $1
  AND (EXISTS (SELECT 1 FROM space_members sm WHERE sm.space_id = c.space_id AND sm.user_id = $1)
       OR EXISTS (SELECT 1 FROM dm_members dm WHERE dm.channel_id = c.id AND dm.user_id = $1))
ORDER BY tm.created_at DESC
LIMIT 200
`

type ListThreadMutesRow struct {
	MessageWithReply MessageWithReply
	Channel          Channel
}

// ListThreadMutes is Profile → Muted's threads, newest mute first, in
// channels the person is still a member of; the caller drops hidden voice
// channels, as accessChannel does.
func (q *Queries) ListThreadMutes(ctx context.Context, userID string) ([]ListThreadMutesRow, error) {
	rows, err := q.db.Query(ctx, listThreadMutes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadMutesRow
	for rows.Next() {
		var i ListThreadMutesRow
		if err := rows.Scan(
			&i.MessageWithReply.ID,
			&i.MessageWithReply.ChannelID,
			&i.MessageWithReply.AuthorID,
			&i.MessageWithReply.Content,
			&i.MessageWithReply.CreatedAt,
			&i.MessageWithReply.MentionsEveryone,
			&i.MessageWithReply.ReplyToMessageID,
			&i.MessageWithReply.MentionsHere,
			&i.MessageWithReply.EditedAt,
			&i.MessageWithReply.ReplyAuthorID,
			&i.MessageWithReply.ReplyContent,
			&i.MessageWithReply.ReplyFirstFileID,
			&i.MessageWithReply.ThreadRootID,
			&i.MessageWithReply.InChannel,
			&i.MessageWithReply.DeletedAt,
			&i.MessageWithReply.ThreadReplyCount,
			&i.MessageWithReply.ThreadLastReplyAt,
			&i.MessageWithReply.ThreadRecentAuthorIds,
			&i.MessageWithReply.MentionsChannel,
			&i.Channel.ID,
			&i.Channel.SpaceID,
			&i.Channel.Name,
			&i.Channel.Kind,
			&i.Channel.Position,
			&i.Channel.CreatedAt,
			&i.Channel.LastMessageID,
			&i.Channel.DmKey,
			&i.Channel.Topic,
			&i.Channel.PostPolicy,
			&i.Channel.Required,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markThreadRead = `-- name: MarkThreadRead :one
INSERT INTO thread_reads (user_id, root_message_id, last_read_message_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, root_message_id) DO UPDATE
SET last_read_message_id = GREATEST(thread_reads.last_read_message_id, EXCLUDED.last_read_message_id),
    updated_at = now()
RETURNING last_read_message_id
`

type MarkThreadReadParams struct {
	UserID            string
	RootMessageID     string
	LastReadMessageID string
}

// MarkThreadRead moves a read marker forward only, and returns where it
// ends up.
func (q *Queries) MarkThreadRead(ctx context.Context, arg MarkThreadReadParams) (string, error) {
	row := q.db.QueryRow(ctx, markThreadRead, arg.UserID, arg.RootMessageID, arg.LastReadMessageID)
	var last_read_message_id string
	err := row.Scan(&last_read_message_id)
	return last_read_message_id, err
}

const muteThread = `-- name: MuteThread :exec

INSERT INTO thread_mutes (user_id, root_message_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MuteThreadParams struct {
	UserID        string
	RootMessageID string
}

// Thread mutes and read markers (STOOP-433). Owned by the chat module.
// Only internal/chat may use these queries. docs/architecture/messaging.md.
func (q *Queries) MuteThread(ctx context.Context, arg MuteThreadParams) error {
	_, err := q.db.Exec(ctx, muteThread, arg.UserID, arg.RootMessageID)
	return err
}

const threadLastReply = `-- name: ThreadLastReply :one
SELECT last_reply_id FROM threads WHERE root_message_id = $1
`

func (q *Queries) ThreadLastReply(ctx context.Context, rootMessageID string) (*string, error) {
	row := q.db.QueryRow(ctx, threadLastReply, rootMessageID)
	var last_reply_id *string
	err := row.Scan(&last_reply_id)
	return last_reply_id, err
}

const threadViewerStates = `-- name: ThreadViewerStates :many
SELECT r.id AS root_id,
    (r.author_id = $1::uuid
     OR EXISTS (SELECT 1 FROM messages m
                WHERE m.thread_root_id = r.id AND m.author_id = $1::uuid)
     OR EXISTS (SELECT 1 FROM message_mentions mm JOIN messages m ON m.id = mm.message_id
                WHERE mm.user_id = $1::uuid
                  AND (m.id = r.id OR m.thread_root_id = r.id)
                  AND NOT m.mentions_everyone AND NOT m.mentions_here AND NOT m.mentions_channel))::bool AS participating,
    EXISTS (SELECT 1 FROM thread_mutes tm
            WHERE tm.user_id = $1::uuid AND tm.root_message_id = r.id)::bool AS muted,
    (SELECT count(*) FROM messages m
     WHERE m.thread_root_id = r.id AND m.author_id <> $1::uuid
       AND m.id > COALESCE((SELECT tr.last_read_message_id FROM thread_reads tr
                            WHERE tr.user_id = $1::uuid AND tr.root_message_id = r.id),
                           '00000000-0000-0000-0000-000000000000'::uuid))::int AS unread_count
FROM messages r
WHERE r.id = ANY($2::uuid[])
`

type ThreadViewerStatesParams struct {
	UserID  string
	RootIds []string
}

type ThreadViewerStatesRow struct {
	RootID        string
	Participating bool
	Muted         bool
	UnreadCount   int32
}

// ThreadViewerStates is one person's view of each root: whether they are
// in its thread (started it, replied, or were @mentioned by name in it;
// @everyone and @here don't count), whether they muted it, and how many
// replies by others came after their read marker.
func (q *Queries) ThreadViewerStates(ctx context.Context, arg ThreadViewerStatesParams) ([]ThreadViewerStatesRow, error) {
	rows, err := q.db.Query(ctx, threadViewerStates, arg.UserID, arg.RootIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadViewerStatesRow
	for rows.Next() {
		var i ThreadViewerStatesRow
		if err := rows.Scan(
			&i.RootID,
			&i.Participating,
			&i.Muted,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unmuteThread = `-- name: UnmuteThread :exec
DELETE FROM thread_mutes WHERE user_id = $1 AND root_message_id = $2
`

type UnmuteThreadParams struct {
	UserID        string
	RootMessageID string
}

func (q *Queries) UnmuteThread(ctx context.Context, arg UnmuteThreadParams) error {
	_, err := q.db.Exec(ctx, unmuteThread, arg.UserID, arg.RootMessageID)
	return err
}
