// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"
)

const adminSetUsername = `-- name: AdminSetUsername :one
UPDATE users SET username = $2, username_pending = false
WHERE id = $1
RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type AdminSetUsernameParams struct {
	ID       string
	Username string
}

// AdminSetUsername is the admin rename; it bypasses the freeze, so an
// admin can fix an offensive handle and then lock it.
func (q *Queries) AdminSetUsername(ctx context.Context, arg AdminSetUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, adminSetUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const clearOwner = `-- name: ClearOwner :exec
UPDATE users SET is_owner = false WHERE is_owner
`

// ClearOwner and SetOwner hand ownership on, in that order inside one
// transaction: the unique index allows no moment with two owners.
func (q *Queries) ClearOwner(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearOwner)
	return err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND kind = 'person' AND deactivated_at IS NULL
`

// CountAdmins counts people: a bot admin can't be the one left to recover
// the instance.
func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, display_name, password_hash, role, username_pending, is_owner)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type CreateUserParams struct {
	ID              string
	Username        string
	DisplayName     string
	PasswordHash    *string
	Role            string
	UsernamePending bool
	IsOwner         bool
}

// Users and the instance role. Owned by the auth module.
// Only internal/auth may use these queries.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.UsernamePending,
		arg.IsOwner,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
UPDATE users
SET deleted_at = now(),
    deactivated_at = COALESCE(deactivated_at, now()),
    display_name = username,
    avatar_file_id = NULL,
    pronouns = '',
    bio = '',
    dnd = false,
    dnd_until = NULL,
    password_hash = NULL
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

// DeleteAccount is what a person's own deletion leaves: the row, its id
// and username, and nothing that was theirs to show. The password goes
// too; there is no signing in to a deleted account.
func (q *Queries) DeleteAccount(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, deleteAccount, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

// DeleteUser undoes a registration whose invite turned out to be spent.
// Only ever a brand-new row: nothing references it yet.
func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getDoNotDisturb = `-- name: GetDoNotDisturb :one
SELECT dnd, dnd_until FROM users WHERE id = $1
`

type GetDoNotDisturbRow struct {
	Dnd      bool
	DndUntil *time.Time
}

// GetDoNotDisturb is the stored state for the gateway's lookup; whether it
// has ended is decided by the caller against the clock.
func (q *Queries) GetDoNotDisturb(ctx context.Context, id string) (GetDoNotDisturbRow, error) {
	row := q.db.QueryRow(ctx, getDoNotDisturb, id)
	var i GetDoNotDisturbRow
	err := row.Scan(&i.Dnd, &i.DndUntil)
	return i, err
}

const getUserAvatarForUpdate = `-- name: GetUserAvatarForUpdate :one
SELECT avatar_file_id FROM users WHERE id = $1 FOR UPDATE
`

// The avatar pointer is replaced in a transaction: lock the row and read
// the current file id, then update, so the caller can delete the old blob
// without racing another upload.
func (q *Queries) GetUserAvatarForUpdate(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getUserAvatarForUpdate, id)
	var avatar_file_id *string
	err := row.Scan(&avatar_file_id)
	return avatar_file_id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, username, display_name, avatar_file_id, pronouns, bio, kind, dnd, dnd_until, deleted_at
FROM users WHERE id = $1
`

type GetUserProfileRow struct {
	ID           string
	Username     string
	DisplayName  string
	AvatarFileID *string
	Pronouns     string
	Bio          string
	Kind         string
	Dnd          bool
	DndUntil     *time.Time
	DeletedAt    *time.Time
}

// GetUserProfile is one person's public face, for their profile card. Its
// own query rather than GetUserByID because that one is SELECT * and would
// put the password hash one line away from a response.
func (q *Queries) GetUserProfile(ctx context.Context, id string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, display_name, role, kind, avatar_file_id, deleted_at FROM users WHERE id = ANY($1::uuid[])
`

type GetUsersByIDsRow struct {
	ID           string
	Username     string
	DisplayName  string
	Role         string
	Kind         string
	AvatarFileID *string
	DeletedAt    *time.Time
}

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []string) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.Kind,
			&i.AvatarFileID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.Role,
			&i.DeactivatedAt,
			&i.AvatarFileID,
			&i.UsernamePending,
			&i.UsernameFrozen,
			&i.Pronouns,
			&i.Bio,
			&i.Kind,
			&i.Dnd,
			&i.DndUntil,
			&i.DeletedAt,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminRoster = `-- name: LockAdminRoster :exec
SELECT pg_advisory_xact_lock(7002)
`

// LockAdminRoster serialises anything that could remove an admin, so two
// demotions can't both see "two admins left" and leave none.
func (q *Queries) LockAdminRoster(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAdminRoster)
	return err
}

const lockUserBootstrap = `-- name: LockUserBootstrap :exec
SELECT pg_advisory_xact_lock(7001)
`

func (q *Queries) LockUserBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockUserBootstrap)
	return err
}

const oldestOtherAdmin = `-- name: OldestOtherAdmin :one
SELECT id FROM users
WHERE role = 'admin' AND kind = 'person' AND deactivated_at IS NULL AND id <> $1
ORDER BY created_at LIMIT 1
`

// OldestOtherAdmin is the instance admin who has served longest, apart
// from one person: where a deleted owner's space goes when no space admin
// can take it.
func (q *Queries) OldestOtherAdmin(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, oldestOtherAdmin, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const referencedAvatarFileIDs = `-- name: ReferencedAvatarFileIDs :many
SELECT avatar_file_id::uuid AS id FROM users WHERE avatar_file_id = ANY($1::uuid[])
`

// ReferencedAvatarFileIDs: which of these files are someone's current
// avatar. For the files module's sweep, through its port.
func (q *Queries) ReferencedAvatarFileIDs(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, referencedAvatarFileIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDoNotDisturb = `-- name: SetDoNotDisturb :one
UPDATE users SET dnd = $2, dnd_until = $3
WHERE id = $1
RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type SetDoNotDisturbParams struct {
	ID       string
	Dnd      bool
	DndUntil *time.Time
}

// SetDoNotDisturb turns do not disturb on, with an optional end, or off.
// Turning it off passes a null end, which users_dnd_until_needs_dnd
// requires.
func (q *Queries) SetDoNotDisturb(ctx context.Context, arg SetDoNotDisturbParams) (User, error) {
	row := q.db.QueryRow(ctx, setDoNotDisturb, arg.ID, arg.Dnd, arg.DndUntil)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const setOwner = `-- name: SetOwner :one
UPDATE users SET is_owner = true WHERE id = $1 RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

func (q *Queries) SetOwner(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, setOwner, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const setUserAvatar = `-- name: SetUserAvatar :exec
UPDATE users SET avatar_file_id = $2 WHERE id = $1
`

type SetUserAvatarParams struct {
	ID           string
	AvatarFileID *string
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) error {
	_, err := q.db.Exec(ctx, setUserAvatar, arg.ID, arg.AvatarFileID)
	return err
}

const setUserDeactivated = `-- name: SetUserDeactivated :one
UPDATE users
SET deactivated_at = CASE WHEN $2::boolean THEN now() ELSE NULL END
WHERE id = $1
RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type SetUserDeactivatedParams struct {
	ID          string
	Deactivated bool
}

func (q *Queries) SetUserDeactivated(ctx context.Context, arg SetUserDeactivatedParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserDeactivated, arg.ID, arg.Deactivated)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2 WHERE id = $1 RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type SetUserRoleParams struct {
	ID   string
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const setUserRoleByUsername = `-- name: SetUserRoleByUsername :one
UPDATE users SET role = $2 WHERE username = $1 RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type SetUserRoleByUsernameParams struct {
	Username string
	Role     string
}

func (q *Queries) SetUserRoleByUsername(ctx context.Context, arg SetUserRoleByUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRoleByUsername, arg.Username, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const setUsername = `-- name: SetUsername :one
UPDATE users SET username = $2, username_pending = false
WHERE id = $1 AND NOT username_frozen
RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type SetUsernameParams struct {
	ID       string
	Username string
}

// SetUsername renames the handle (self-service). Usernames are freely
// changeable — the id is the durable identity everywhere — unless an
// admin froze the handle; it also settles the "derived from a login
// provider" flag.
func (q *Queries) SetUsername(ctx context.Context, arg SetUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const setUsernameFrozen = `-- name: SetUsernameFrozen :one
UPDATE users SET username_frozen = $2 WHERE id = $1 RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type SetUsernameFrozenParams struct {
	ID             string
	UsernameFrozen bool
}

func (q *Queries) SetUsernameFrozen(ctx context.Context, arg SetUsernameFrozenParams) (User, error) {
	row := q.db.QueryRow(ctx, setUsernameFrozen, arg.ID, arg.UsernameFrozen)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           string
	PasswordHash *string
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    display_name = coalesce($2::text, display_name),
    pronouns     = coalesce($3::text,     pronouns),
    bio          = coalesce($4::text,          bio)
WHERE id = $1
RETURNING id, username, display_name, password_hash, created_at, role, deactivated_at, avatar_file_id, username_pending, username_frozen, pronouns, bio, kind, dnd, dnd_until, deleted_at, is_owner
`

type UpdateUserProfileParams struct {
	ID          string
	DisplayName *string
	Pronouns    *string
	Bio         *string
}

// UpdateUserProfile writes the fields a person (or an admin acting on
// their account) may change; a null argument leaves that column alone.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Pronouns,
		arg.Bio,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.DeactivatedAt,
		&i.AvatarFileID,
		&i.UsernamePending,
		&i.UsernameFrozen,
		&i.Pronouns,
		&i.Bio,
		&i.Kind,
		&i.Dnd,
		&i.DndUntil,
		&i.DeletedAt,
		&i.IsOwner,
	)
	return i, err
}

const usernameTaken = `-- name: UsernameTaken :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameTaken(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameTaken, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
