#!/usr/bin/env node
// Regenerates web/src/api/emojiData.ts from Unicode's emoji-test.txt.
//
//   node scripts/gen-emoji.mjs [path-or-url]
//
// Defaults to the latest published file. Keeps fully-qualified emoji in
// CLDR order with their group, skipping skin-tone variants (the picker has
// no tone selector yet) and anything over the server's 16-byte reaction
// limit. Run `pnpm format` in web/ afterwards.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE =
  process.argv[2] ?? "https://unicode.org/Public/emoji/latest/emoji-test.txt";
const MAX_BYTES = 16;
const out = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "web/src/api/emojiData.ts",
);

const text = /^https?:/.test(SOURCE)
  ? await (await fetch(SOURCE)).text()
  : await readFile(SOURCE, "utf8");

const version = text.match(/^# Version: (.+)$/m)?.[1] ?? "unknown";
const groups = [];
let group = null;
let skippedTone = 0;
let skippedSize = 0;
for (const line of text.split("\n")) {
  const g = line.match(/^# group: (.+)$/);
  if (g) {
    group = { name: g[1], entries: [] };
    groups.push(group);
    continue;
  }
  const m = line.match(
    /^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E[\d.]+\s+(.+)$/,
  );
  if (!m || !group) continue;
  const [, , emoji, name] = m;
  if (/skin tone/.test(name)) {
    skippedTone++;
    continue;
  }
  if (Buffer.byteLength(emoji, "utf8") > MAX_BYTES) {
    skippedSize++;
    continue;
  }
  group.entries.push([emoji, name]);
}
const kept = groups.reduce((n, g) => n + g.entries.length, 0);

const body = groups
  .filter((g) => g.entries.length > 0)
  .map(
    (g) =>
      `  [\n    ${JSON.stringify(g.name)},\n    [\n${g.entries
        .map(([e, n]) => `      [${JSON.stringify(e)}, ${JSON.stringify(n)}],`)
        .join("\n")}\n    ],\n  ],`,
  )
  .join("\n");

await writeFile(
  out,
  `// GENERATED by scripts/gen-emoji.mjs from Unicode emoji-test.txt
// (Emoji ${version}) — do not edit by hand. ${kept} emoji in CLDR order;
// skin-tone variants and sequences over ${MAX_BYTES} bytes are left out.

export type EmojiGroup = [name: string, entries: [emoji: string, name: string][]];

export const EMOJI_GROUPS: EmojiGroup[] = [
${body}
];
`,
);
console.log(
  `wrote ${out}: ${kept} emoji in ${groups.length} groups (Emoji ${version}; skipped ${skippedTone} skin-tone variants, ${skippedSize} over ${MAX_BYTES} bytes)`,
);
